import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { AttendanceReview, AttendanceReadinessCard } from "@/app/(ntg)/payroll/attendance-source/attendance-review";
import type { AttendanceReadiness } from "@/lib/payroll/attendanceResolutionModel";

// Fictional fixtures only. The preview bundle replaces server actions and has no network access.
const record = (id: string, type: "IN" | "OUT", capturedAt: string, flags: string[]) => ({ eventId: id, branchId: "Example branch", employeeId: "552", employeeName: "Example employee", originalEmployeeId: "552", originalEmployeeName: "Example employee", type, capturedAt, receivedAt: capturedAt, updatedAt: capturedAt, status: "VALID" as const, clockFlag: false, reviewFlags: flags, reviewResolved: false, correctionVersion: "original" });
export const previewData: AttendanceReadiness = { periodId: "00000000-0000-4000-8000-000000000001", code: "2026-09-B", startDate: "2026-09-16", endDate: "2026-09-30", periodOpen: true, runState: "Complete", syncedAt: "2026-10-05T06:00:00Z", needsSync: false, summariesOutdated: true, ready: false, blockers: ["Review the missing OUT, sync attendance, then refresh DTR before recomputing."], counts: { withheld: 1, boundaryReview: 1 }, people: [{ sourceId: "552", name: "Example employee", employeeId: "00000000-0000-4000-8000-000000000003", employeeNo: "00552", employeeName: "Example employee", classification: "Active", version: "fictional-version", records: [record("00000000-0000-4000-8000-000000000010", "IN", "2026-09-30T13:00:00Z", ["NO_FOLLOWING_OUT"]), record("00000000-0000-4000-8000-000000000011", "IN", "2026-10-01T01:00:00Z", ["CONSECUTIVE_IN", "NO_FOLLOWING_OUT"])], relevantIds: ["00000000-0000-4000-8000-000000000010"], issues: ["Missing IN or OUT", "Period boundary needs a partner"], contextOnly: false, resolution: null }], history: [], historyHasMore: false, sourceCorrectionsEnabled: true };
function Preview() {
  const [data, setData] = useState(previewData);
  return <main className="mx-auto max-w-5xl space-y-5 p-4 text-slate-900"><header className="rounded-xl bg-slate-900 p-5 text-white"><strong>Integra · Production component preview</strong><p className="mt-2 text-sm">Fictional records only. This downloadable preview does not connect to production.</p><button className="mt-3 rounded border px-3 py-2" onClick={() => { previewData.people[0].resolution = null; previewData.history = []; setData(structuredClone(previewData)); }}>Reset example</button></header><AttendanceReadinessCard data={data} /><AttendanceReview data={data} refresh={() => setData(structuredClone(previewData))} /><section id="reconcile-title" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Attendance & sync</h2><p className="mt-2 text-sm">In the live app: sync this period → resolve and approve cases → refresh DTR summaries → recompute and review. This sample has no production actions.</p></section></main>;
}
createRoot(document.getElementById("root")!).render(<Preview />);
