import React from "react";
import {createRoot} from "react-dom/client";
import { AttendanceWorkbench } from "@/app/(ntg)/payroll/attendance-source/workbench";
import type { WorkBoard, WorkRecord } from "@/lib/payroll/attendanceWorkbenchModel";
const records:WorkRecord[]=[{id:"00000000-0000-4000-8000-000000000031",source:"API",employeeId:"example",sourceEmployeeId:"3",type:"OUT",originalType:"OUT",at:"2026-09-29T23:42:31.725Z",originalAt:"2026-09-29T23:42:31.725Z",status:"VALID",clockFlag:false},{id:"00000000-0000-4000-8000-000000000032",source:"API",employeeId:"example",sourceEmployeeId:"3",type:"OUT",originalType:"OUT",at:"2026-09-30T09:07:54.000Z",originalAt:"2026-09-30T09:07:54.000Z",status:"VALID",clockFlag:false}];
export const board:WorkBoard={period:{id:"fictional-period",code:"2026-09-B · Fictional example",startDate:"2026-09-16",endDate:"2026-09-30",posted:false},employees:[{id:"example",no:"00003",name:"Ernesto Example",sourceIds:["3"],mappingEvidence:{},hired:null,separated:null,days:[{day:"2026-09-30",schedule:{checkInTime:"08:00",checkOutTime:"17:00",hoursPerDay:8,breakMinutes:60},rest:false,leave:0,leaveEvidence:[],configuration:{},records,status:"Review records",issues:["Repeated OUT or missing IN"],suggestions:[{label:"Review OUT → IN",explanation:"Changing the first capture’s direction makes a complete pair. Verify using supervisor evidence; time of day is not proof.",changes:[{kind:"Direction",eventId:records[0].id,type:"IN",day:"2026-09-30"}]},{label:"Add verified missing IN",explanation:"Check uploads first. Supply only a time supported by actual evidence.",changes:[{kind:"Manual",type:"IN",day:"2026-09-30"}]}],version:"fictional-evidence-1",resolved:false}]}],plans:[],adjustments:[],owners:[{id:"admin",name:"Example administrator"}],statuses:{sync:"Up to date",review:"Needs review",delivery:"Up to date",dtr:"Refresh needed",payroll:"Draft — recompute explicitly"},enabled:true};
board.employees.push({id:"missing-example",no:"00042",name:"Maria Example",sourceIds:["42"],mappingEvidence:{},hired:null,separated:null,days:["2026-09-29","2026-09-30"].map(day=>({day,schedule:{checkInTime:"08:00",checkOutTime:"17:00",hoursPerDay:8,breakMinutes:60},rest:false,leave:0,leaveEvidence:[],configuration:{},records:[],status:"Missing workday",issues:["Verify missing workday or confirm no attendance"],suggestions:[],version:`fictional-${day}`,resolved:false}))});
export const previewState:{failNext:boolean;drafts:unknown[];revision:number}={failNext:false,drafts:[],revision:0};
createRoot(document.getElementById("root")!).render(<main className="mx-auto max-w-6xl p-2 sm:p-6"><div className="mb-3 rounded-lg bg-amber-100 p-3 text-sm"><strong>Fictional component preview</strong><p>No production data or credentials. Buttons simulate the workflow.</p><button className="my-2 rounded border bg-white p-2" onClick={()=>{previewState.failNext=true;}}>Simulate next approval timing out</button></div><AttendanceWorkbench initial={board}/></main>);
