import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {eq,sql} from "drizzle-orm";
import {matchingDatabase} from "./attendanceTest/matchingDatabase";
import {employees,employeesTimekeeping,payrollPeriods,payrollRuns,attendanceRawLogs,attendanceImportBatches,employeesGeneralInfo,employeesLeaveRecords,employeeLeaveRecordDays} from "@/db/schema";
import {attendanceSourceMappings,attendanceSourceRuns} from "@/db/attendanceSourceSchema";
import {workPlans,adjustmentCases} from "@/db/attendanceWorkbenchSchema";
import {workEmployees,draftVersion,saveWorkDraft,prepareWorkApproval,approveWorkBatch,previewWork,workDayRecords} from "@/lib/payroll/attendanceWorkbench";
import {processWorkDelivery,undoWorkDraft} from "@/lib/payroll/attendanceWorkbenchDelivery";
import {reconcileAttendanceSource} from "@/lib/payroll/attendanceSourceSync";
import {missingDateRanges,sequenceProblems,type WorkDraft,type WorkChange,type WorkRecord} from "@/lib/payroll/attendanceWorkbenchModel";
import type {SourcePunch} from "@/lib/payroll/attendanceSourceClient";
import type {DbClient,db} from "@/db";
async function main(){
 process.env.ATTENDANCE_WORKBENCH_ENABLED="true";process.env.ATTENDANCE_SOURCE_ENABLED="true";process.env.ATTENDANCE_SOURCE_ORIGIN="https://fictional.invalid";process.env.ATTENDANCE_CORRECTION_TOKEN="fixture-only-token-".repeat(4);
 const {pg,database,client}=await matchingDatabase();const dbClient=database as unknown as typeof db;
 try{
  const actor=randomUUID(),a=randomUUID(),b=randomUUID(),sept=randomUUID(),oct=randomUUID();
  for(const [id,no] of [[a,"00001"],[b,"00002"]]){await database.insert(employees).values({id,employeeNo:no,firstName:"Fictional",lastName:no});await database.insert(employeesTimekeeping).values({employeeId:id,checkInTime:"08:00:00",checkOutTime:"17:00:00",hoursWorked:"8"});await database.insert(attendanceSourceMappings).values({sourceEmployeeId:String(Number(no)),employeeId:id,actorUserId:actor,reason:"Verified fictional identity"});}
  for(const [id,month,start,end] of [[sept,9,"2026-09-29","2026-09-30"],[oct,10,"2026-10-01","2026-10-02"]] as const)await database.insert(payrollPeriods).values({id,code:`FIXTURE-${month}`,payrollTerms:"Semi-Monthly",cycle:"B",year:2026,month,startDate:start,endDate:end,nominalPayDate:end,adjustedPayDate:end});
  let records:SourcePunch[]=(["IN","OUT"] as const).map((type,i)=>({eventId:randomUUID(),employeeId:"1",employeeName:"Fictional 00001",originalEmployeeId:"1",originalEmployeeName:"Fictional 00001",branchId:"B1",type,originalType:type,capturedAt:`2026-09-30T0${i?9:0}:00:00.123Z`,originalCapturedAt:`2026-09-30T0${i?9:0}:00:00.123Z`,receivedAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z",status:"VALID",clockFlag:false,clockVerified:false,reviewFlags:[],reviewResolved:false,correctionVersion:"original",effectiveRevision:"original"}));
  let upload=true,writes=0,interruptSync=false;const applied=new Map<string,unknown>();
  const fetcher:typeof fetch=async(_url,init)=>{const p=JSON.parse(String(init?.body));if(p.operation==="context")return Response.json({version:1,contextToken:"b".repeat(64),uploadCoverage:{state:upload?"Confirmed":"Needs upload check",through:upload?"2026-10-04T00:00:00.000Z":null},records:records.filter(r=>p.employeeIds.includes(r.employeeId)).map(r=>({eventId:r.eventId,employeeId:r.employeeId,employeeName:r.employeeName,type:r.type,capturedAt:r.capturedAt,status:r.status,clockVerified:r.clockVerified,revision:r.effectiveRevision}))});if(p.operation==="plan-status")return Response.json(applied.get(p.id)??{state:"Not found",changes:[]});if(!applied.has(p.id)){writes++;const changes=p.changes.map((c:Record<string,unknown>)=>{const r=records.find(r=>r.eventId===c.eventId)!;const before={employeeId:r.employeeId,employeeName:r.employeeName,type:r.type,capturedAt:r.capturedAt,status:r.status,clockVerified:r.clockVerified};const revision=randomUUID();Object.assign(r,...["employeeId","type","capturedAt","status"].filter(k=>c[k]!==undefined).map(k=>({[k]:c[k]})),{employeeName:`Fictional 0000${c.employeeId??r.employeeId}`,effectiveRevision:revision,correctionVersion:revision,updatedAt:new Date().toISOString(),clockVerified:c.clockVerified??(c.capturedAt?true:r.clockVerified)});return {event_id:r.eventId,revision,before_json:JSON.stringify(before),after_json:JSON.stringify({employeeId:r.employeeId,employeeName:r.employeeName,type:r.type,capturedAt:r.capturedAt,status:r.status,clockVerified:r.clockVerified})};});applied.set(p.id,{state:"Applied",changes});}return Response.json({accepted:true});};
  async function sync(id:string=sept){if(interruptSync&&id===oct)throw Error("Fictional restart before second-period sync");const runId=randomUUID();await database.insert(attendanceSourceRuns).values({id:runId,payrollPeriodId:id,actorUserId:actor,state:"Fetching",fromDate:id===sept?"2026-09-28":"2026-09-30",throughDate:id===sept?"2026-10-01":"2026-10-03",startedAt:sql`clock_timestamp()`});return reconcileAttendanceSource(dbClient,id,runId,actor,records);}
  await sync();await sync(oct);
  const verified={reason:"Supervisor verified fixture",evidence:"Fictional signed incident\nExact records checked",verified:true};
  const change=(kind:WorkChange["kind"],values:Partial<WorkChange>={}):WorkChange=>({id:randomUUID(),day:"2026-09-30",kind,...verified,...values});
  async function draft(employeeId:string,changes:WorkChange[],period=sept):Promise<WorkDraft>{const person=(await workEmployees(period,client)).find(p=>p.id===employeeId)!;const days=[...new Set(changes.map(c=>c.day))].sort();return {employeeId,changes,days,reason:verified.reason,ownerId:actor,needed:"",rejected:false,version:draftVersion(person,days)};}
  async function save(drafts:WorkDraft[],period=sept){return database.transaction(tx=>saveWorkDraft(tx as unknown as DbClient,actor,period,drafts));}
  async function approve(drafts:WorkDraft[],period=sept){const saved=await save(drafts,period),preview=await prepareWorkApproval(period,saved.id,saved.revision,client,fetcher);await approveWorkBatch(actor,period,saved.id,saved.revision,preview.digest,dbClient,fetcher);return {saved,preview};}
  const bPerson=(await workEmployees(sept,client)).find(p=>p.id===b)!;assert.equal(missingDateRanges(bPerson.days)[0].days.length,2);
  const missing=await draft(b,[change("Manual",{type:"OUT"})]);assert.ok(previewWork(bPerson,missing).errors.some(e=>e.includes("verified date")));
  const transfer=[await draft(a,[...records.map(r=>change("Employee",{eventId:r.eventId,targetEmployeeId:b})),change("NoAttendance")]),await draft(b,[change("ConfirmSequence")])];
  const held=await save(transfer);upload=false;await assert.rejects(()=>prepareWorkApproval(sept,held.id,held.revision,client,fetcher),/Uploads still need verification/);upload=true;
  const moved=await approve(transfer);assert.equal(moved.preview.prepared[0].sourceRequest?.id,moved.preview.prepared[1].sourceRequest?.id);await processWorkDelivery(actor,{database:dbClient,batchId:moved.saved.id,fetcher,sync});assert.equal(writes,1,"Related employees share one atomic source request");assert.equal((await database.select().from(attendanceRawLogs)).filter(r=>r.employeeId===b).length,2,"Receiving employee owns the effective pair");
  const transferred=(await database.select().from(workPlans)).find(p=>p.batchId===moved.saved.id&&p.employeeId===a)!;const undo=await undoWorkDraft(client,actor,transferred.id);assert.equal(undo.length,2);assert.equal(undo.flatMap(d=>d.changes).filter(c=>c.kind==="UndoCapture").length,2);
  const reversal=await approve(undo.map(d=>({...d,changes:d.changes.map(c=>({...c,...verified}))})));await processWorkDelivery(actor,{database:dbClient,batchId:reversal.saved.id,fetcher,sync});assert.equal(writes,2);assert.ok(records.every(r=>r.employeeId==="1"));await assert.rejects(()=>undoWorkDraft(client,actor,transferred.id),/Later attendance|later source/);
  // Move a verified full pair into a posted period; before evidence must come from that period.
  await database.insert(payrollRuns).values({payrollPeriodId:oct,runNumber:1,status:"Posted"});const postedBefore=await database.select().from(payrollRuns),rawBefore=(await database.select().from(attendanceRawLogs)).filter(r=>r.logDate.startsWith("2026-10"));
  const shifted=await approve([await draft(a,records.map((r,i)=>change("Time",{eventId:r.eventId,at:`2026-10-02T${i?"17":"08"}:00:00.123`})))]);
  assert.ok(shifted.preview.prepared[0].periodEvidence.some(p=>p.id===oct&&p.posted));const cases=await database.select().from(adjustmentCases);assert.ok((cases[0].beforeEvidence as {days:{day:string}[]}).days.every(d=>d.day.startsWith("2026-10")));
  interruptSync=true;await processWorkDelivery(actor,{database:dbClient,batchId:shifted.saved.id,fetcher,sync});assert.equal((await database.select().from(workPlans).where(eq(workPlans.batchId,shifted.saved.id)))[0].state,"Sync pending");const writesBefore=writes;interruptSync=false;await processWorkDelivery(actor,{database:dbClient,batchId:shifted.saved.id,fetcher,sync});assert.equal(writes,writesBefore);assert.equal((await database.select().from(workPlans).where(eq(workPlans.batchId,shifted.saved.id)))[0].state,"Resolved");assert.deepEqual(await database.select().from(payrollRuns),postedBefore);assert.deepEqual((await database.select().from(attendanceRawLogs)).filter(r=>r.logDate.startsWith("2026-10")),rawBefore);assert.ok((await database.select().from(adjustmentCases))[0].impact);
  // File/API source selection and late originals retain evidence without double counting.
  records=records.map((r,i)=>({...r,employeeId:"2",employeeName:"Fictional 00002",capturedAt:`2026-09-29T0${i?9:0}:00:00.123Z`,effectiveRevision:randomUUID(),updatedAt:new Date(Date.now()+10).toISOString()}));await sync();
  const [file]=await database.insert(attendanceImportBatches).values({payrollPeriodId:sept,sourceFileName:"fictional.csv",sourceFormat:"CSV",status:"Processed"}).returning();
  for(const [i,type] of (["IN","OUT"] as const).entries())await database.insert(attendanceRawLogs).values({batchId:file.id,employeeId:b,employeeNo:"00002",direction:type,loggedAt:sql`${`2026-09-29 ${i?"17":"08"}:00:00.123`}::timestamp`,logDate:"2026-09-29",logTime:`${i?"17":"08"}:00:00.123`,rawText:"Fictional file evidence",normalizedHash:randomUUID()});
  const overlaps=(await workEmployees(sept,client)).find(p=>p.id===b)!;assert.ok(overlaps.days[0].issues.some(e=>e.includes("overlapping")));
  const selected=await approve([await draft(b,records.map(r=>change("Exclude",{eventId:r.eventId,day:"2026-09-29"})))]);await processWorkDelivery(actor,{database:dbClient,batchId:selected.saved.id,fetcher,sync});assert.equal((await workEmployees(sept,client)).find(p=>p.id===b)!.days[0].issues.length,0);const fileBefore=await database.select().from(attendanceRawLogs).where(eq(attendanceRawLogs.batchId,file.id));await sync();assert.deepEqual(await database.select().from(attendanceRawLogs).where(eq(attendanceRawLogs.batchId,file.id)),fileBefore);
  records.push({...records[0],eventId:randomUUID(),capturedAt:"2026-09-29T00:01:00.000Z",originalCapturedAt:"2026-09-29T00:01:00.000Z",effectiveRevision:"original"});await sync();assert.ok((await workEmployees(sept,client)).find(p=>p.id===b)!.days[0].issues.length>0,"Late originals invalidate prior sequence acceptance");
  const overnight:WorkRecord[]=[{id:"in",source:"Manual",employeeId:a,type:"IN",at:"2026-09-30T14:00:00Z",status:"VALID",clockFlag:false},{id:"out",source:"Manual",employeeId:a,type:"OUT",at:"2026-09-30T22:00:00Z",status:"VALID",clockFlag:false}];assert.equal(workDayRecords(overnight,"2026-09-30").length,2);assert.ok(sequenceProblems(overnight,null).warnings.some(w=>w.includes("Overnight")));assert.equal(workDayRecords([{...overnight[0],excluded:true},overnight[1]],"2026-10-01").length,1,"Excluded context cannot supply an overnight partner");
  const hired=randomUUID();await database.insert(employees).values({id:hired,employeeNo:"00444",firstName:"New",lastName:"Fictional"});await database.insert(employeesGeneralInfo).values({employeeId:hired,dateHired:"2026-09-30",separationDate:"2026-09-30"});await database.insert(employeesTimekeeping).values({employeeId:hired,checkInTime:"08:00:00",checkOutTime:"17:00:00",hoursWorked:"8"});await database.insert(attendanceSourceMappings).values({sourceEmployeeId:"444",employeeId:hired,actorUserId:actor,reason:"Fictional verified identity"});
  const [leave]=await database.insert(employeesLeaveRecords).values({employeeId:hired,dateFiled:"2026-09-29",leaveStartDate:"2026-09-30",leaveEndDate:"2026-09-30",leaveType:"Vacation",noOfDays:"1",leaveStatus:"Approved"}).returning();await database.insert(employeeLeaveRecordDays).values({leaveRecordId:leave.id,leaveDate:"2026-09-30",quantity:"1"});
  const employed=(await workEmployees(sept,client)).find(p=>p.id===hired)!;assert.deepEqual(employed.days.map(d=>d.day),["2026-09-30"]);assert.equal(employed.days[0].status,"Approved leave");assert.equal(employed.days[0].issues.length,0);assert.ok(!(await workEmployees(oct,client)).some(p=>p.id===hired));
  const wrongOwner=await draft(b,[change("Direction",{eventId:records[0].eventId,type:"OUT",day:"2026-09-30"})]);wrongOwner.employeeId=a;const ownerA=(await workEmployees(sept,client)).find(p=>p.id===a)!;assert.ok(previewWork(ownerA,wrongOwner).errors.some(e=>e.includes("another employee")));
  process.env.ATTENDANCE_WORKBENCH_APPROVALS_ENABLED="false";await assert.rejects(()=>approveWorkBatch(actor,sept,selected.saved.id,selected.saved.revision,"ignored",dbClient,fetcher),/approvals are paused/);delete process.env.ATTENDANCE_WORKBENCH_APPROVALS_ENABLED;
  console.log("PASS: related-employee atomic delivery/Undo, upload holds, multi-period restart, posted-period evidence, source selection, late originals and overnight context");
 }finally{await pg.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
