import assert from "node:assert/strict";
import { batchReviewFixture, completeChange } from "./attendanceTest/batchReviewFixture";
import { adoptIncomingDraft, affectedWorkDates, appendManualDraft, buildNoWorkDrafts, deliverySummary, sourceDeliveryLabel, uniqueDayTargets } from "@/lib/payroll/attendanceStage6Model";
import { draftVersion, reconcileDraftVerification, simulateWork, type WorkPlanView } from "@/lib/payroll/attendanceWorkbenchModel";
const {board,drafts}=batchReviewFixture();let id=0;const uuid=()=>`test-${++id}`;
const person=board.employees[0],day=person.days[0].day;
const targets=[{employeeId:person.id,day},{employeeId:person.id,day}];
assert.equal(uniqueDayTargets(targets).length,1);
const next=buildNoWorkDrafts([drafts[1]],board.employees,targets,"approved",uuid);
assert.deepEqual(next[0],drafts[1],"Unselected employee drafts remain intact");
assert.equal(next[1].changes.length,3);assert.ok(next[1].changes.every(c=>!c.verified));
assert.equal(simulateWork(person.contextRecords??[],next[1].changes,person.id).records.filter(r=>r.status==="VALID"&&!r.excluded).length,0);
assert.throws(()=>buildNoWorkDrafts(drafts,board.employees,targets,"approved",uuid),/already has draft edits/);
assert.throws(()=>buildNoWorkDrafts([],board.employees,targets,"",uuid),/reason/);
const manual=completeChange({id:"manual",kind:"Manual",eventId:undefined,at:`${day}T08:00`,reason:"approved",evidence:"approved",verified:true});
const withManual=appendManualDraft([drafts[1]],person,manual,"approved");
assert.equal(appendManualDraft(withManual,person,manual,"approved")[1].changes.length,1,"Retry updates same draft row, never duplicates it");
assert.equal(reconcileDraftVerification(withManual,appendManualDraft(withManual,person,{...manual,at:`${day}T08:01`},"approved"),board.employees)[1].changes[0].verified,false);
assert.equal(reconcileDraftVerification([],withManual,[{...person,days:[{...person.days[0],version:"changed"}]},board.employees[1]])[1].changes[0].verified,false);
const decision={revision:"1",reason:"approved",approvedAt:"2026-10-01T00:00:00Z",incomingDigest:"new",incomingRecords:person.contextRecords??[],lateConflict:true};
const incoming={...person,days:[{...person.days[0],decision}]};
const previous={...drafts[0],changes:[completeChange({verified:true}),completeChange({id:"unrelated",day:"2026-09-29",verified:true})]};
const adopted=adoptIncomingDraft(incoming,previous,day,uuid);
assert.equal(adopted.changes.length,3);assert.deepEqual(adopted.changes[0],{...previous.changes[0],verified:false});assert.deepEqual(adopted.changes[1],previous.changes[1]);assert.equal(adopted.reason,previous.reason);
assert.equal(adoptIncomingDraft(incoming,adopted,day,uuid).changes.length,3,"Repeated adoption retains edits without extra reopen rows");
const overnight={...person,contextRecords:[...person.contextRecords!,{...person.contextRecords![1],id:"next-out",at:"2026-09-30T22:00:00Z"}],days:[{...person.days[0],records:[...person.contextRecords!,{...person.contextRecords![1],id:"next-out",at:"2026-09-30T22:00:00Z"}]}]};
const overnightDraft=buildNoWorkDrafts([], [overnight],targets,"approved",uuid)[0];assert.ok(overnightDraft.changes.some(c=>c.eventId==="next-out"),"Displayed adjacent-date capture is explicitly selected");
assert.equal(overnightDraft.version,draftVersion(overnight,[day]));
const plan:WorkPlanView={id:"p",batchId:"b",revision:1,state:"Needs fresh review",draft:drafts[0],approved:true,updatedAt:"2026-10-01T00:00:00Z",result:null};
assert.match(sourceDeliveryLabel(plan),/approved decision retained/);assert.match(deliverySummary([plan]),/1 source reviews/);assert.equal(deliverySummary([{...plan,supersededBy:["later"]}]),"Up to date");
assert.match(deliverySummary([{...plan,state:"Failed"}]),/failed/);assert.match(deliverySummary([{...plan,state:"Applying"}]),/pending/);
console.log("PASS Stage 6 draft retention, exact no-work selection, overnight context, manual retry/edit reset, stale evidence and truthful delivery counts");

assert.deepEqual(affectedWorkDates({...drafts[0],changes:[completeChange({kind:"Exclude",eventId:undefined,rawLogId:42})]},[{...person.contextRecords![0],rawLogId:42,at:"2026-10-01T01:00:00Z"}]),["2026-09-30","2026-10-01"],"Adjacent raw captures participate in affected-period validation");
