import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { db } from "@/db";
import { authAccounts, department, employees, employeesGeneralInfo, employeesTimekeeping, employeeShiftAssignments, employeeWeeklyShiftPatterns, employeeWeeklyShiftPatternDays, payrollPeriods, payrollRuns, payrollRunEmployees, shiftTables, shiftTableBreaks, scheduleDecisionRevisions, scheduleWorkspaceDrafts, attendanceDailySummaries } from "@/db/schema";
import { eq, sql, and } from "drizzle-orm";
import { archiveWeeklySchedule, mutatePeriodSchedule, readScheduleReceipt, readScheduleWorkspace, saveWeeklySchedules, type ScheduleActor } from "@/lib/scheduling/service";
import type { SchedulePeriodCommand } from "@/lib/scheduling/workspace-types";
import { resolveEmployeeScheduleForDate } from "@/lib/payroll/scheduleResolver";

async function main() {
  assert.equal(new URL(process.env.DATABASE_URL!).hostname, "127.0.0.1", "Write tests require an isolated loopback database");
  const tables = ["employees", "employees_general_info", "employees_timekeeping", "department", "payroll_periods", "payroll_runs", "payroll_run_employees", "payroll_run_events", "employee_shift_assignments", "employee_weekly_shift_patterns", "employee_weekly_shift_pattern_days", "shift_tables", "shift_table_breaks", "schedule_workspace_drafts", "schedule_decision_revisions", "schedule_request_receipts", "attendance_daily_summaries", "admin_audit_events"];
  const fingerprint = async () => (await db.execute(sql.raw(tables.map(table => `select '${table}' as name,count(*)::int as count,md5(coalesce(string_agg(to_jsonb(t)::text,E'\\n' order by to_jsonb(t)::text),'')) as hash from ${table} t`).join(" union all ")))).rows;
  const before = await fingerprint(), rollback = new Error("test rollback");
  try {
    await db.transaction(async tx => {
      const database = { ...db, transaction: async (fn: Parameters<typeof db.transaction>[0]) => tx.transaction(fn) } as typeof db;
      const [account] = await tx.select().from(authAccounts).limit(1);
      const actor: ScheduleActor = { userId: account.id, role: "ADMIN" };
      const suffix = randomUUID().slice(0, 8);
      const [branch] = await tx.insert(department).values({ name: `Schedule QA ${suffix}`, code: `SCH-${suffix}` }).returning();
      const people = await tx.insert(employees).values([1, 2, 3].map(index => ({ employeeNo: `SCH-${suffix}-${index}`, firstName: "Schedule", lastName: `Fixture ${index}` }))).returning();
      await tx.insert(employeesGeneralInfo).values(people.map(person => ({ employeeId: person.id, departmentId: branch.id, dateHired: "2098-09-01" })));
      await tx.insert(employeesTimekeeping).values({ employeeId: people[2].id, hoursWorked: "8.00" });
      const [shift] = await tx.insert(shiftTables).values({ code: `QA-${suffix}`, description: "Schedule QA shift", regularStartTime: "08:00", regularEndTime: "17:00" }).returning();
      await tx.insert(shiftTableBreaks).values({ shiftTableId: shift.id, slotKey: "mid_break", label: "Lunch", fromTime: "12:00", toTime: "13:00", deduct: true, deductHours: 1, deductMinutes: 0, sortOrder: 1 });
      const [night] = await tx.insert(shiftTables).values({ code: `QN-${suffix}`, description: "Overnight QA", regularStartTime: "22:00", regularEndTime: "06:00" }).returning();
      const periodId = randomUUID();
      await tx.insert(payrollPeriods).values({ id: periodId, code: `SQ-${suffix}`, year: 2098, month: 9, cycle: "B", payrollTerms: "Semi-Monthly", startDate: "2098-09-28", endDate: "2098-09-30", nominalPayDate: "2098-10-05", adjustedPayDate: "2098-10-05", status: "Open" });
      const query = { departmentId: branch.id, periodId, effectiveDate: "2098-09-28" };
      let workspace = await readScheduleWorkspace(actor, query, tx);
      assert.equal(workspace.cells.length, 9); assert.equal(workspace.cells.filter(cell => cell.snapshot.kind === "unconfigured").length, 6);
      await saveWeeklySchedules(actor, { requestId: randomUUID(), departmentId: branch.id, sourceDigest: workspace.weeklyDigest, effectiveFrom: "2098-09-28", effectiveTo: null, employeeIds: [people[0].id], days: [{ weekday: "Sunday", value: String(shift.id) }, { weekday: "Tuesday", value: String(shift.id) }] }, database);
      workspace = await readScheduleWorkspace(actor, query, tx);
      const weekday = new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "UTC" }).format(new Date("2098-09-28T12:00:00Z"));
      const sundayCell = workspace.cells.find(cell => cell.employeeId === people[0].id && new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "UTC" }).format(new Date(`${cell.day}T12:00:00Z`)) === "Sunday");
      if (sundayCell) assert.equal(sundayCell.snapshot.shiftTableId, shift.id);
      assert.ok(workspace.employees[0].weeklyDays.some(day => day.weekday !== "Sunday" && day.value === "unconfigured"), "Partial weekdays retain Unconfigured rather than inventing rest");
      assert.ok(weekday);
      const [originalRange] = await tx.insert(employeeShiftAssignments).values({ employeeId: people[0].id, shiftTableId: shift.id, shiftName: "Original ranged override", effectiveFrom: "2098-09-30", effectiveTo: "2098-10-02", checkInTime: "08:00", checkOutTime: "17:00", hoursPerDay: "8.00" }).returning();
      const [adjacentSummary] = await tx.insert(attendanceDailySummaries).values({ employeeId: people[0].id, attendanceDate: "2098-10-01", shiftAssignmentId: originalRange.id, workedMinutes: 480 }).returning();
      workspace = await readScheduleWorkspace(actor, query, tx);
      const command = (): SchedulePeriodCommand => ({ requestId: randomUUID(), departmentId: branch.id, periodId, sourceDigest: workspace.draft?.sourceDigest ?? workspace.sourceDigest, expectedDraftRevision: workspace.draft?.revision ?? null, expectedDraftId: workspace.draft?.id ?? null, changes: [] });
      const draft = { ...command(), changes: [{ employeeId: people[0].id, day: "2098-09-29", value: String(shift.id) }, { employeeId: people[0].id, day: "2098-09-30", value: String(night.id) }] };
      assert.equal((await mutatePeriodSchedule(actor, draft, "draft_saved", database)).draftRevision, 1);
      assert.deepEqual(await tx.select().from(employeeShiftAssignments).where(eq(employeeShiftAssignments.employeeId, people[0].id)), [originalRange], "Saving draft has no payroll-effective assignment mutations");
      assert.equal((await mutatePeriodSchedule(actor, draft, "draft_saved", database)).draftRevision, 1, "Retry returns durable receipt");
      await assert.rejects(() => mutatePeriodSchedule(actor, { ...draft, requestId: randomUUID() }, "draft_saved", database), /Another administrator/);
      workspace = await readScheduleWorkspace(actor, query, tx); assert.equal(workspace.draft?.cells.length, 9);
      assert.ok(Math.abs(Date.parse(workspace.draft!.updatedAt) - Date.now()) < 120_000, "Draft audit timestamp round-trips as the actual instant regardless of database session timezone");
      const confirm = command(), receipt = await mutatePeriodSchedule(actor, confirm, "confirmed", database);
      assert.equal(receipt.changedCount, 9); assert.deepEqual(await readScheduleReceipt(actor, confirm.requestId, tx), receipt);
      assert.deepEqual(await mutatePeriodSchedule(actor, confirm, "confirmed", database), receipt);
      assert.equal((await tx.select().from(scheduleDecisionRevisions).where(eq(scheduleDecisionRevisions.periodId, periodId))).length, 9, "Idempotency prevents duplicate day revisions");
      assert.deepEqual((await tx.select().from(employeeShiftAssignments).where(eq(employeeShiftAssignments.id, originalRange.id)))[0], originalRange, "Original ranged override is preserved, including neighboring dates");
      assert.deepEqual((await tx.select().from(attendanceDailySummaries).where(eq(attendanceDailySummaries.id, adjacentSummary.id)))[0], adjacentSummary, "Adjacent summary and foreign-key provenance are unchanged");
      const assignments = await tx.select().from(employeeShiftAssignments).where(eq(employeeShiftAssignments.employeeId, people[0].id));
      const savedDay = assignments.find(row => row.effectiveFrom === "2098-09-29")!;
      assert.equal(savedDay.confirmedSchedule?.breaks[0].fromTime, "12:00:00");
      const flexible = (await tx.select().from(employeeShiftAssignments).where(eq(employeeShiftAssignments.employeeId, people[2].id)))[0];
      const resolvedFlexible = resolveEmployeeScheduleForDate({ attendanceDate: flexible.effectiveFrom, assignments: [flexible], weeklyPatterns: [], legacyTimekeeping: null });
      assert.equal(resolvedFlexible.shiftWindow.checkInTime, null); assert.equal(resolvedFlexible.hoursPerDay, 8);
      const missing = (await tx.select().from(employeeShiftAssignments).where(eq(employeeShiftAssignments.employeeId, people[1].id)))[0];
      assert.equal(resolveEmployeeScheduleForDate({ attendanceDate: missing.effectiveFrom, assignments: [missing], weeklyPatterns: [], legacyTimekeeping: null }).configured, false);
      await tx.update(shiftTableBreaks).set({ fromTime: "11:00" }).where(eq(shiftTableBreaks.shiftTableId, shift.id));
      workspace = await readScheduleWorkspace(actor, query, tx);
      assert.equal(workspace.cells.find(cell => cell.employeeId === people[0].id && cell.day === "2098-09-29")!.snapshot.breaks[0].fromTime, "12:00:00", "Confirmed break data is frozen");
      const oldDigest = workspace.sourceDigest;
      await saveWeeklySchedules(actor, { requestId: randomUUID(), departmentId: branch.id, sourceDigest: workspace.weeklyDigest, effectiveFrom: "2098-09-28", effectiveTo: null, employeeIds: [people[0].id], days: [{ weekday: "Monday", value: "rest" }] }, database);
      await assert.rejects(() => mutatePeriodSchedule(actor, { ...command(), sourceDigest: oldDigest }, "confirmed", database), /changed/);
      workspace = await readScheduleWorkspace(actor, query, tx);
      assert.equal(workspace.cells.find(cell => cell.employeeId === people[0].id && cell.day === "2098-09-29")!.snapshot.checkInTime?.slice(0, 5), "08:00", "Weekly changes retain confirmed facts");
      // A deleted template must not make an immutable captured default unrestorable.
      await tx.delete(shiftTables).where(eq(shiftTables.id, shift.id));
      workspace = await readScheduleWorkspace(actor, query, tx);
      await mutatePeriodSchedule(actor, { ...command(), changes: [{ employeeId: people[0].id, day: "2098-09-30", value: "default" }] }, "confirmed", database);
      const restoredRows = await tx.select().from(employeeShiftAssignments).where(and(eq(employeeShiftAssignments.employeeId, people[0].id), eq(employeeShiftAssignments.effectiveFrom, "2098-09-30")));
      const restoredDefault = restoredRows.find(row => row.scheduleDecisionId)!;
      assert.equal(restoredDefault.shiftTableId, null); assert.equal(restoredDefault.confirmedSchedule?.shiftTableId, shift.id); assert.equal(restoredDefault.confirmedSchedule?.checkInTime?.slice(0, 5), "08:00");
      workspace = await readScheduleWorkspace(actor, query, tx);
      const runId = randomUUID(); await tx.insert(payrollRuns).values({ id: runId, payrollPeriodId: periodId, runNumber: 1, status: "Posted", inputSnapshot: { payrollGroup: "Daily" } });
      await tx.insert(payrollRunEmployees).values({ payrollRunId: runId, employeeId: people[0].id, employeeNoSnapshot: people[0].employeeNo, employeeNameSnapshot: "QA only" });
      await assert.rejects(() => mutatePeriodSchedule(actor, { ...command(), changes: [{ employeeId: people[0].id, day: "2098-09-29", value: "rest" }] }, "confirmed", database), /Posted/);
      assert.equal((await tx.select().from(employeeShiftAssignments).where(and(eq(employeeShiftAssignments.employeeId, people[0].id), eq(employeeShiftAssignments.effectiveFrom, "2098-09-29"))))[0].checkInTime, "08:00:00");
      // Historically older periods also receive posted protection, irrespective of picker size.
      const historicalPeriodId = randomUUID();
      await tx.insert(payrollPeriods).values({ id: historicalPeriodId, code: `SO-${suffix}`, year: 2001, month: 1, cycle: "A", payrollTerms: "Semi-Monthly", startDate: "2001-01-01", endDate: "2001-01-15", nominalPayDate: "2001-01-20", adjustedPayDate: "2001-01-20", status: "Open" });
      const historicalRunId = randomUUID(); await tx.insert(payrollRuns).values({ id: historicalRunId, payrollPeriodId: historicalPeriodId, runNumber: 1, status: "Posted", inputSnapshot: { payrollGroup: "Legacy" } });
      await tx.insert(payrollRunEmployees).values({ payrollRunId: historicalRunId, employeeId: people[1].id, employeeNoSnapshot: people[1].employeeNo, employeeNameSnapshot: "Historical QA" });
      workspace = await readScheduleWorkspace(actor, query, tx);
      await assert.rejects(() => saveWeeklySchedules(actor, { requestId: randomUUID(), departmentId: branch.id, sourceDigest: workspace.weeklyDigest, effectiveFrom: "2001-01-01", effectiveTo: "2001-01-15", employeeIds: [people[1].id], days: [{ weekday: "Monday", value: String(night.id) }] }, database), /Posted/);
      const unused = { ...command(), changes: [{ employeeId: people[1].id, day: "2098-09-29", value: "rest" }] };
      await mutatePeriodSchedule(actor, unused, "draft_saved", database); workspace = await readScheduleWorkspace(actor, query, tx);
      const oldDraftCommand = command();
      await mutatePeriodSchedule(actor, command(), "draft_deleted", database);
      assert.equal((await tx.select().from(scheduleWorkspaceDrafts).where(eq(scheduleWorkspaceDrafts.periodId, periodId))).length, 0);
      workspace = await readScheduleWorkspace(actor, query, tx);
      await mutatePeriodSchedule(actor, command(), "draft_saved", database);
      await assert.rejects(() => mutatePeriodSchedule(actor, { ...oldDraftCommand, requestId: randomUUID() }, "confirmed", database), /Another administrator/, "Deleted/recreated revision-one draft must reject stale identity");
      workspace = await readScheduleWorkspace(actor, query, tx);
      await mutatePeriodSchedule(actor, command(), "draft_deleted", database);
      await assert.rejects(() => readScheduleWorkspace({ userId: randomUUID(), role: "MANAGER" }, query, tx), /not assigned/);
      workspace = await readScheduleWorkspace(actor, query, tx);
      const pattern = workspace.employees.find(row => row.id === people[0].id)!.weeklyHistory[0];
      await archiveWeeklySchedule(actor, { requestId: randomUUID(), departmentId: branch.id, sourceDigest: workspace.weeklyDigest, employeeId: people[0].id, patternId: pattern.id, endDate: "2098-09-30" }, database);
      assert.equal((await tx.select().from(employeeWeeklyShiftPatterns).where(eq(employeeWeeklyShiftPatterns.id, pattern.id)))[0].effectiveTo, "2098-09-30");
      assert.equal((await tx.select().from(employeeWeeklyShiftPatternDays).where(eq(employeeWeeklyShiftPatternDays.patternId, pattern.id))).length, 7, "Archived pattern history is preserved");
      throw rollback;
    });
  } catch (error) { if (error !== rollback) throw error; }
  assert.deepEqual(await fingerprint(), before, "Every fixture write rolls back");
  console.log("PASS restored schedule workspace: draft isolation/reload, whole-period atomic confirmation, partial defaults, rest/unconfigured/flexible/overnight, frozen breaks, idempotency, stale draft, manager scope, posted protection, archive and rollback");
}
main().then(() => process.exit(0)).catch(error => { console.error(error); process.exit(1); });
