import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { sql, eq, and } from "drizzle-orm";
import { db } from "@/db";
import { accountCode, employeesSalary, employeesLoans, loanInstallments, employeeShiftAssignments, employeeSalaryChanges, employeesRecurringEntries, payrollPeriods, payrollRuns, payrollRunEmployees, payrollRunLines, manualPayrollEntries, manualPayrollEntryLines, sssContributionBrackets, statutoryRuleVersions } from "@/db/schema";
import { loadProvisionalPayroll } from "@/lib/payroll/provisional";
import { loadPayrollCalculation } from "@/lib/payroll/engine";
import { workBatches, workPlans } from "@/db/attendanceWorkbenchSchema";
import { persistAdminDecision } from "@/lib/payroll/attendanceAdminDecisionStore";
import type { WorkDraft, WorkRecord } from "@/lib/payroll/attendanceWorkbenchModel";

async function main() {
  const url=new URL(process.env.DATABASE_URL??"");
  assert.equal(url.hostname,"127.0.0.1","Use the restored loopback fixture only");
  assert.match(url.pathname,/provisional.*_gui$/);
  const fixture=JSON.parse(readFileSync(process.env.PROVISIONAL_FIXTURE_FILE!,"utf8"));
  const checks:string[]=[];
  const before=await db.execute(sql`select json_object_agg(table_name, fingerprint) as value from (
    select table_name, (xpath('/row/value/text()', query_to_xml(format('select md5(coalesce(string_agg(to_jsonb(t)::text, '''' order by to_jsonb(t)::text),'''')) as value from %I t',table_name),false,true,'')))[1]::text as fingerprint
    from information_schema.tables where table_schema='public' and table_type='BASE TABLE'
  ) x`);
  const daily=await loadProvisionalPayroll({periodId:fixture.periodId,group:"Daily",employeeId:fixture.dailyEmployeeId,asOfDate:"2026-10-07"});
  assert.equal(daily.rows.length,1);const row=daily.rows[0];
  assert.equal(row.status,"Available",row.warnings.join(" | "));
  assert.equal(row.recorded?.gross,600,"One completed eight-hour shift earns one daily rate");
  assert.equal(row.days.find(day=>day.date===fixture.missingOutDay)?.status,"Incomplete");
  assert.equal(row.days.find(day=>day.date===fixture.missingOutDay)?.workedMinutes,0);
  assert.equal(row.days.find(day=>day.date===fixture.noWorkDay)?.status,"No work recorded");
  assert(row.days.find(day=>day.date===fixture.completeDay)?.punches.some(punch=>punch.endsWith("08:00:00 · IN")),"Philippine capture display retains 08:00:00 IN: "+JSON.stringify(row.days.find(day=>day.date===fixture.completeDay)?.punches));
  assert(row.days.find(day=>day.date===fixture.completeDay)?.punches.some(punch=>punch.endsWith("17:00:00 · OUT")),"Philippine capture display retains 17:00:00 OUT: "+JSON.stringify(row.days.find(day=>day.date===fixture.completeDay)?.punches));
  assert(row.forecast!.gross>row.recorded!.gross,"Future confirmed shifts produce a separate monetary forecast");
  checks.push("Daily valid work, incomplete/no-work zero, separate confirmed-shift forecast");
  const repeated=await loadProvisionalPayroll({periodId:fixture.periodId,group:"Daily",employeeId:fixture.dailyEmployeeId,asOfDate:"2026-10-07"});
  assert.equal(repeated.inputRevision,daily.inputRevision,"Unchanged inputs have a stable revision");
  checks.push("Stable combined input revision");
  const early=await loadProvisionalPayroll({periodId:fixture.periodId,group:"Daily",employeeId:fixture.dailyEmployeeId,asOfDate:"2026-10-04"});
  assert.equal(early.rows[0].recorded?.gross,0);assert.equal(early.rows[0].recorded?.deductions,0);
  assert.equal(early.rows[0].forecast?.gross,row.forecast?.gross,"Missed past shifts are not invented when cutoff is earlier");
  checks.push("Cutoff affects recorded work; zero earnings collect no deductions; historical gaps remain zero in forecast");
  const monthly=await loadProvisionalPayroll({periodId:fixture.periodId,group:"Monthly",departmentId:fixture.branchId,asOfDate:"2026-10-07"});
  assert.equal(monthly.rows.find(employee=>employee.employeeId===fixture.firstHalfMonthlyEmployeeId)?.recorded?.gross,30000);
  assert.equal(monthly.rows.find(employee=>employee.employeeId===fixture.secondHalfMonthlyEmployeeId)?.status,"Not scheduled this half");
  const second=await loadProvisionalPayroll({periodId:fixture.secondPeriodId,group:"Monthly",departmentId:fixture.branchId,asOfDate:"2026-10-07"});
  assert.equal(second.rows.find(employee=>employee.employeeId===fixture.secondHalfMonthlyEmployeeId)?.recorded?.gross,30000);
  checks.push("Monthly fixed salary without logs in either selected half; alternate half not scheduled");
  const [period]=await db.select().from(payrollPeriods).where(eq(payrollPeriods.id,fixture.periodId));
  const standard=await db.transaction(async tx=>(await loadPayrollCalculation(period,"Daily",tx,{employeeId:fixture.dailyEmployeeId})).calculate(),{isolationLevel:"repeatable read",accessMode:"read only"});
  assert.equal(standard.computations[0].grossPay,row.recorded!.gross,"Canonical estimate agrees with existing prepared payroll computation");
  assert.equal(standard.computations[0].totalDeductions,row.recorded!.deductions);
  checks.push("Normal payroll calculator parity for identical prepared attendance");
  await assert.rejects(()=>loadProvisionalPayroll({periodId:fixture.periodId,group:"Daily",asOfDate:"2026-02-30"}));
  await assert.rejects(()=>loadProvisionalPayroll({periodId:fixture.periodId,group:"Daily",asOfDate:"2099-01-01"}));
  checks.push("Invalid and uncompleted cutoff validation");
  const rollback=new Error("ROLLBACK_PROVISIONAL_REGRESSION");
  try { await db.transaction(async tx=>{
    // Mutations below are fictional arrangements in one rolled-back restored
    // transaction. Estimates themselves use the same reader and never write.
    const database={transaction:async(fn:(client:typeof tx)=>Promise<unknown>)=>fn(tx)} as unknown as typeof db;
    const estimate=(group:"Daily"|"Monthly",employeeId:string,cutoff="2026-10-07")=>loadProvisionalPayroll({periodId:fixture.periodId,group,employeeId,asOfDate:cutoff},database);
    const [salary]=await tx.select().from(employeesSalary).where(eq(employeesSalary.employeeId,fixture.dailyEmployeeId));
    await tx.update(employeesSalary).set({dailyRate:"0"}).where(eq(employeesSalary.employeeId,fixture.dailyEmployeeId));
    const missingRate=await estimate("Daily",fixture.dailyEmployeeId);assert.equal(missingRate.rows[0].recorded,null);assert.equal(missingRate.rows[0].status,"Unavailable");
    const [explicit]=await tx.insert(manualPayrollEntries).values({payrollPeriodId:fixture.periodId,employeeId:fixture.dailyEmployeeId,employeeNoSnapshot:"PV-QA-001",employeeNameSnapshot:"Fictional explicit manual",grossPay:"500",nonTaxablePay:"500",netPay:"500"}).returning();
    await tx.insert(manualPayrollEntryLines).values({manualPayrollEntryId:explicit.id,lineType:"Earning",summaryBucket:"otherIncome",code:"EXPLICIT",description:"Approved explicit earning",amount:"500"});
    const explicitPay=await estimate("Daily",fixture.dailyEmployeeId);assert.equal(explicitPay.rows[0].recorded!.gross,500,"Fully explicit manual earnings need no automatic salary baseline");
    await tx.delete(manualPayrollEntries).where(eq(manualPayrollEntries.id,explicit.id));
    await tx.update(employeesSalary).set({dailyRate:salary.dailyRate}).where(eq(employeesSalary.employeeId,fixture.dailyEmployeeId));
    checks.push("Missing rate is unavailable, never a fabricated zero");
    const [assignment]=await tx.select().from(employeeShiftAssignments).where(and(eq(employeeShiftAssignments.employeeId,fixture.dailyEmployeeId),eq(employeeShiftAssignments.effectiveFrom,fixture.completeDay)));
    assert(assignment.confirmedSchedule);
    await tx.update(employeeShiftAssignments).set({confirmedSchedule:{...assignment.confirmedSchedule,checkInTime:"09:00",checkOutTime:"18:00"}}).where(eq(employeeShiftAssignments.id,assignment.id));
    const changedSchedule=await estimate("Daily",fixture.dailyEmployeeId);
    assert.notEqual(changedSchedule.inputRevision,daily.inputRevision);assert.notEqual(changedSchedule.rows[0].recorded!.gross,600,"Schedule change updates estimate without a persisted DTR rebuild");
    assert.equal(changedSchedule.rows[0].days.find(day=>day.date===fixture.completeDay)?.punches[0],row.days.find(day=>day.date===fixture.completeDay)?.punches[0],"Schedule change does not alter capture values");
    await tx.update(employeeShiftAssignments).set({confirmedSchedule:assignment.confirmedSchedule}).where(eq(employeeShiftAssignments.id,assignment.id));
    checks.push("Schedule revision immediately changes estimate; original punches preserved");
    const [futureShift]=await tx.select().from(employeeShiftAssignments).where(and(eq(employeeShiftAssignments.employeeId,fixture.dailyEmployeeId),eq(employeeShiftAssignments.effectiveFrom,fixture.futureDay)));
    assert(futureShift.confirmedSchedule);
    const revisedBreaks=futureShift.confirmedSchedule.breaks.map(gap=>gap.slotKey==="mid_break"?{...gap,fromTime:"02:00",toTime:"03:00"}:gap);
    await tx.update(employeeShiftAssignments).set({confirmedSchedule:{...futureShift.confirmedSchedule,checkInTime:"22:00",checkOutTime:"07:00",breaks:revisedBreaks}}).where(eq(employeeShiftAssignments.id,futureShift.id));
    const overnight=await estimate("Daily",fixture.dailyEmployeeId);
    assert.equal(overnight.rows[0].recorded!.gross,row.recorded!.gross);
    assert.equal(overnight.rows[0].futureScheduledMinutes,row.futureScheduledMinutes,"Cross-period overnight forecast retains eight regular hours");
    assert.equal(overnight.rows[0].days.find(day=>day.date===fixture.futureDay)!.punches.length,0,"Hypothetical overnight punches never appear as recorded captures");
    const splitBreaks=futureShift.confirmedSchedule.breaks.map(gap=>gap.slotKey==="mid_break"?{...gap,fromTime:"12:00",toTime:"16:00",deductHours:4}:gap);
    await tx.update(employeeShiftAssignments).set({shiftCode:"PV-SPLIT",confirmedSchedule:{...futureShift.confirmedSchedule,checkInTime:"08:00",checkOutTime:"20:00",breakMinutes:240,breaks:splitBreaks}}).where(eq(employeeShiftAssignments.id,futureShift.id));
    const split=await estimate("Daily",fixture.dailyEmployeeId);assert.equal(split.rows[0].futureScheduledMinutes,row.futureScheduledMinutes,"Split forecast uses all required punch segments and configured break");
    await tx.update(employeeShiftAssignments).set({shiftCode:futureShift.shiftCode,confirmedSchedule:futureShift.confirmedSchedule}).where(eq(employeeShiftAssignments.id,futureShift.id));
    checks.push("Overnight cross-period and split-shift forecasts reuse configured break rules without creating attendance");
    await tx.execute(sql`savepoint provisional_approved_future`);
    const draft:WorkDraft={employeeId:fixture.dailyEmployeeId,days:[fixture.futureDay],changes:[],reason:"",ownerId:"fixture",needed:"",rejected:false,version:"fixture"};
    const [decisionBatch]=await tx.insert(workBatches).values({periodId:fixture.periodId,actor:"fixture"}).returning();
    const [decisionPlan]=await tx.insert(workPlans).values({batchId:decisionBatch.id,periodId:fixture.periodId,employeeId:fixture.dailyEmployeeId,draft,state:"Resolved",evidenceVersion:"fixture",ownerId:"fixture"}).returning();
    const decisionArgs={periodId:fixture.periodId,planId:decisionPlan.id,actor:"fixture",employeeNo:"PV-QA-001",draft,sourceRecords:[],warnings:[]};
    await persistAdminDecision(tx,{...decisionArgs,records:[]});
    const approvedNoWork=await estimate("Daily",fixture.dailyEmployeeId);
    assert.equal(approvedNoWork.rows[0].futureScheduledMinutes,row.futureScheduledMinutes-480,"Approved future no-work is not replaced with a hypothetical full shift");
    assert.equal(approvedNoWork.rows[0].recorded!.gross,row.recorded!.gross);
    assert(approvedNoWork.rows[0].days.find(day=>day.date===fixture.futureDay)!.warnings.some(note=>note.includes("Approved attendance decision retained")));
    const partialRecords:WorkRecord[]=[{id:"fixture-in",source:"Manual",employeeId:fixture.dailyEmployeeId,type:"IN",at:`${fixture.futureDay}T08:00:00+08:00`,status:"VALID",clockFlag:false},{id:"fixture-out",source:"Manual",employeeId:fixture.dailyEmployeeId,type:"OUT",at:`${fixture.futureDay}T12:00:00+08:00`,status:"VALID",clockFlag:false}];
    await persistAdminDecision(tx,{...decisionArgs,records:partialRecords});
    const approvedPartial=await estimate("Daily",fixture.dailyEmployeeId);
    assert.equal(approvedPartial.rows[0].futureScheduledMinutes,row.futureScheduledMinutes-240,"Approved partial future work remains four hours, not a full forecast shift");
    assert.equal(approvedPartial.rows[0].forecast!.gross,approvedNoWork.rows[0].forecast!.gross+300);
    assert.notEqual(approvedPartial.inputRevision,approvedNoWork.inputRevision);
    await tx.execute(sql`rollback to savepoint provisional_approved_future`);
    checks.push("Approved future no-work and partial-day decisions remain authoritative in forecasts");
    const monthlyId=fixture.firstHalfMonthlyEmployeeId;
    await tx.update(employeesSalary).set({ignoreContributionDeduction:false}).where(eq(employeesSalary.employeeId,monthlyId));
    const contributions=await estimate("Monthly",monthlyId);assert.equal(contributions.rows[0].recorded!.gross,30000);assert(contributions.rows[0].recorded!.deductions>0);
    await tx.execute(sql`savepoint provisional_missing_rules`);
    await tx.delete(sssContributionBrackets);
    const emptyRules=await estimate("Monthly",monthlyId);assert.equal(emptyRules.rows[0].recorded,null);assert.equal(emptyRules.rows[0].status,"Unavailable");
    await tx.execute(sql`rollback to savepoint provisional_missing_rules`);
    await tx.update(statutoryRuleVersions).set({status:"Draft"}).where(eq(statutoryRuleVersions.ruleType,"SSS"));
    const unpublishedRules=await estimate("Monthly",monthlyId);assert.equal(unpublishedRules.rows[0].recorded,null);
    await tx.execute(sql`rollback to savepoint provisional_missing_rules`);
    checks.push("Missing or unpublished statutory calculation setup is unavailable; explicit manual earnings do not require an automatic salary rate");
    await tx.update(employeesSalary).set({ignoreContributionDeduction:true}).where(eq(employeesSalary.employeeId,monthlyId));
    const loanId=randomUUID(),installmentA=randomUUID(),installmentB=randomUUID();
    await tx.insert(employeesLoans).values({id:loanId,employeeId:monthlyId,loanReferenceNumber:"PROVISIONAL-ROLLBACK",amountGranted:"2000",payrollDateDeduction:"2026-10-15",loanDate:"2026-10-01",paymentTerms:"Always",payableLoan:"2000",loanTotalCredit:"0",amortization:"500",loanBalance:"2000",status:"Active"});
    await tx.insert(loanInstallments).values([{id:installmentA,loanId,payrollPeriodId:fixture.periodId,payrollCode:"2026-10-A",installmentNo:1,dueDate:"2026-10-15",scheduledAmount:"500"},{id:installmentB,loanId,payrollPeriodId:fixture.secondPeriodId,payrollCode:"2026-10-B",installmentNo:2,dueDate:"2026-10-31",scheduledAmount:"500"}]);
    const both=await estimate("Monthly",monthlyId);assert.equal(both.rows[0].recorded!.deductions,1000);
    const priorPeriodId=randomUUID(),priorRun=randomUUID(),priorEmployee=randomUUID();
    await tx.insert(payrollPeriods).values({id:priorPeriodId,code:`PV-${priorPeriodId.slice(0,8)}`,year:2026,month:10,cycle:"A",payrollTerms:"Semi-Monthly",startDate:"2026-10-01",endDate:"2026-10-15",nominalPayDate:"2026-10-15",adjustedPayDate:"2026-10-15",status:"Closed"});
    await tx.insert(payrollRuns).values({id:priorRun,payrollPeriodId:priorPeriodId,runNumber:1,status:"Posted",runType:"Regular",inputSnapshot:{}});
    await tx.insert(payrollRunEmployees).values({id:priorEmployee,payrollRunId:priorRun,employeeId:monthlyId,employeeNoSnapshot:"PV-QA-002",employeeNameSnapshot:"Fictional monthly",regularPay:"15000",grossPay:"15000",taxablePay:"15000",netPay:"14500",totalDeductions:"500"});
    await tx.insert(payrollRunLines).values([{payrollRunEmployeeId:priorEmployee,lineType:"Earning",code:"REG",description:"Earlier salary",amount:"15000"},{payrollRunEmployeeId:priorEmployee,lineType:"Deduction",code:"LOAN",description:"Earlier installment",amount:"500",sourceTable:"loan_installments",sourceId:installmentA}]);
    await tx.update(loanInstallments).set({status:"Paid"}).where(eq(loanInstallments.id,installmentA));
    const credited=await estimate("Monthly",monthlyId);assert.equal(credited.rows[0].recorded!.gross,15000);assert.equal(credited.rows[0].recorded!.deductions,500);assert.equal(credited.rows[0].postedCredits,15000);
    await tx.execute(sql`savepoint provisional_prior_excess`);
    await tx.update(payrollRunEmployees).set({regularPay:"35000",grossPay:"35000"}).where(eq(payrollRunEmployees.id,priorEmployee));
    await tx.update(payrollRunLines).set({amount:"35000"}).where(and(eq(payrollRunLines.payrollRunEmployeeId,priorEmployee),eq(payrollRunLines.code,"REG")));
    const excess=await estimate("Monthly",monthlyId);assert.equal(excess.rows[0].recorded!.gross,0);assert.equal(excess.rows[0].status,"Available");assert(excess.rows[0].warnings.some(note=>note.includes("Unrecovered excess: 5000.00")));
    await tx.execute(sql`rollback to savepoint provisional_prior_excess`);
    checks.push("Whole-month statutory basis and both loan installments; legacy posted salary credited and paid installment never recollected");
    await tx.insert(employeeSalaryChanges).values({employeeId:monthlyId,payrollPeriodId:fixture.periodId,mode:"OnePeriodOverride",reason:"Fictional approved adjustment",createdByUserId:"fixture",afterMonthlyRate:"31000"});
    const salaryChanged=await estimate("Monthly",monthlyId);assert.equal(salaryChanged.rows[0].recorded!.gross,16000);assert.notEqual(salaryChanged.inputRevision,credited.inputRevision);
    const [income]=await tx.select().from(accountCode).where(eq(accountCode.accountType,"Other Income")).limit(1);assert(income);
    await tx.insert(employeesRecurringEntries).values({employeeId:monthlyId,accountCode:income.accountCode,description:"Fictional approved recurring",amount:"1250",status:"Active"});
    const recurring=await estimate("Monthly",monthlyId);assert.equal(recurring.rows[0].recorded!.gross,17250);
    checks.push("Approved salary revision and configured recurring earnings retained with posted credits");
    const beforeRecovery=await estimate("Daily",fixture.dailyEmployeeId);
    const debtPeriod=randomUUID(),debtRun=randomUUID(),debtEmployee=randomUUID();
    await tx.insert(payrollPeriods).values({id:debtPeriod,code:`PV-${debtPeriod.slice(0,8)}`,year:2026,month:9,cycle:"B",payrollTerms:"Semi-Monthly",startDate:"2026-09-16",endDate:"2026-09-30",nominalPayDate:"2026-09-30",adjustedPayDate:"2026-09-30",status:"Closed"});
    await tx.insert(payrollRuns).values({id:debtRun,payrollPeriodId:debtPeriod,runNumber:1,status:"Posted",runType:"Regular",inputSnapshot:{payrollGroup:"Daily",shortfallPolicy:"future-positive-net-v1"}});
    await tx.insert(payrollRunEmployees).values({id:debtEmployee,payrollRunId:debtRun,employeeId:fixture.dailyEmployeeId,employeeNoSnapshot:"PV-QA-001",employeeNameSnapshot:"Fictional Daily",grossPay:"0",totalDeductions:"120",netPay:"-120"});
    const recovery=await estimate("Daily",fixture.dailyEmployeeId),expectedRecovery=Math.min(120,beforeRecovery.rows[0].recorded!.net);
    assert.equal(recovery.rows[0].recorded!.deductions,Math.round((beforeRecovery.rows[0].recorded!.deductions+expectedRecovery)*100)/100);
    assert.equal(recovery.rows[0].recorded!.net,Math.round((beforeRecovery.rows[0].recorded!.net-expectedRecovery)*100)/100);
    assert.equal(recovery.rows[0].recordedLines.find(line=>line.code==="SHORTFALL_RECOVERY")?.amount??0,expectedRecovery);
    const zero=await estimate("Daily",fixture.dailyEmployeeId,"2026-10-04");assert.equal(zero.rows[0].recorded!.deductions,0);
    assert.equal((await tx.select().from(loanInstallments).where(eq(loanInstallments.id,installmentB)))[0].status,"Pending");
    checks.push("Authorized prior shortfall projected against positive net only; estimates never collect loans or debt");
    throw rollback;
  }); } catch(error) { if(error!==rollback)throw error; }
  const after=await db.execute(sql`select json_object_agg(table_name, fingerprint) as value from (
    select table_name, (xpath('/row/value/text()', query_to_xml(format('select md5(coalesce(string_agg(to_jsonb(t)::text, '''' order by to_jsonb(t)::text),'''')) as value from %I t',table_name),false,true,'')))[1]::text as fingerprint
    from information_schema.tables where table_schema='public' and table_type='BASE TABLE'
  ) x`);
  assert.deepEqual(after.rows,before.rows,"Every restored table remains unchanged after reads");
  checks.push("All-table database fingerprints unchanged across complete estimate journeys");
  console.log(JSON.stringify({passed:true,checks,productionAccess:false,rows:daily.rows.length}));
}
main().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});
