import assert from "node:assert/strict";
import { sourceDayEligibility, buildAttendanceDayInput } from "@/lib/payroll/attendanceDayInput";
import { summarizeEmployeeDay } from "@/lib/payroll/attendance";
import { manilaWallTime, type SourcePunch } from "@/lib/payroll/attendanceSourceClient";
const punch=(id:string,type:"IN"|"OUT",at:string,reviewFlags:string[]=[]):SourcePunch=>({eventId:id,employeeId:"PHONE",employeeName:"Fictional",originalEmployeeId:"PHONE",originalEmployeeName:"Fictional",branchId:"QA",type,capturedAt:at,receivedAt:at,updatedAt:at,status:"VALID",clockFlag:false,reviewResolved:false,reviewFlags});
const shift={checkInTime:"08:00",checkOutTime:"17:00",breakMinutes:60,hoursPerDay:8};
const prior=punch("prior","IN","2026-10-05T17:04:37.108+08:00",["CONSECUTIVE_IN","NO_FOLLOWING_OUT"]),inside=punch("in","IN","2026-10-06T07:44:01.126+08:00",["CONSECUTIVE_IN"]),outside=punch("out","OUT","2026-10-06T17:05:22.836+08:00");
const evaluate=(records:SourcePunch[])=>sourceDayEligibility(records,()=>"employee",()=>shift);
assert.equal(evaluate([prior,inside,outside]).get("in")?.eligible,true);
assert.equal(evaluate([prior,inside,outside]).get("prior")?.eligible,false,"Previous malformed day is not silently corrected");
assert.equal(evaluate([{...inside,clockFlag:true},outside]).get("in")?.eligible,false);
assert.equal(evaluate([{...inside,reviewFlags:["IDENTITY_CONFLICT"]},outside]).get("in")?.eligible,false);
assert.equal(evaluate([{...inside,reviewFlags:["CLOSE_PUNCHES_ACROSS_PHONES"]},outside]).get("in")?.eligible,false);
assert.equal(evaluate([inside,punch("duplicate","IN","2026-10-06T08:01:00+08:00",["CONSECUTIVE_IN"]),outside]).get("in")?.eligible,false,"Same-day repeated IN remains ambiguous");
const night=[punch("night-in","IN","2026-10-15T22:00:00+08:00",["NO_FOLLOWING_OUT"]),punch("night-out","OUT","2026-10-16T07:00:00+08:00",["NO_EARLIER_IN"])];
const overnight=sourceDayEligibility(night,()=>"employee",()=>({...shift,checkInTime:"22:00",checkOutTime:"07:00"}));
assert.equal(overnight.get("night-in")?.eligible,true);assert.equal(overnight.get("night-out")?.day,"2026-10-15");
const logs=(records:SourcePunch[])=>records.map(p=>{const wall=manilaWallTime(p.capturedAt);return {employeeNo:"QA",loggedAt:new Date(p.capturedAt),logDate:wall.date,logTime:wall.time,direction:p.type,sourceLine:0,rawText:""};});
const complete=summarizeEmployeeDay("2026-10-06",logs([inside,outside]),shift);assert.equal(complete.regularMinutes,480);assert.deepEqual(complete.anomalyFlags,[]);
const orphanOut=summarizeEmployeeDay("2026-10-06",logs([outside]),shift);assert(orphanOut.anomalyFlags.includes("MISSING_IN"));assert(!orphanOut.anomalyFlags.includes("MISSING_OUT"));
const orphanIn=summarizeEmployeeDay("2026-10-06",logs([inside]),shift);assert(orphanIn.anomalyFlags.includes("MISSING_OUT"));assert(!orphanIn.anomalyFlags.includes("MISSING_IN"));
const untyped=logs([inside,punch("lunch","OUT","2026-10-06T12:00:00+08:00"),punch("return","IN","2026-10-06T13:00:00+08:00")]).map(log=>({...log,direction:"UNSPECIFIED" as const}));
assert(summarizeEmployeeDay("2026-10-06",untyped,shift).anomalyFlags.includes("PARTIAL_VALID_WORK"),"An odd untyped file preserves its complete first pair");
const included=[inside,outside].map(p=>({id:p.eventId,type:p.type,at:p.capturedAt,included:true,reason:null}));
assert.equal(buildAttendanceDayInput(included.map(punch=>({...punch,type:"UNSPECIFIED"}))).complete,true,"Directionless file pairs follow the existing positional calculation");
assert.deepEqual(buildAttendanceDayInput(included.map(punch=>({...punch,type:"UNSPECIFIED"}))).issues,[]);
assert.equal(buildAttendanceDayInput([{...included[0],type:"UNSPECIFIED"}]).missingDirection,null,"Unknown file direction is not falsely labelled as a known missing IN/OUT");
assert.equal(buildAttendanceDayInput(included).complete,true);assert.deepEqual(buildAttendanceDayInput(included).issues,[]);
assert.equal(buildAttendanceDayInput([{...included[0],included:false,reason:"Device clock needs verification"},included[1]]).canConfirmExisting,false);
assert.equal(buildAttendanceDayInput([included[1]]).missingDirection,"IN");
assert.equal(buildAttendanceDayInput([included[0]]).missingDirection,"OUT");
const historical={...included[0],id:"original-voided",at:"2026-10-06T09:00:00+08:00",included:false,reason:"Voided by approved attendance decision",evidenceState:"resolved" as const};
assert.deepEqual(buildAttendanceDayInput([...included,historical]).issues,[],"Reviewed audit evidence cannot add a false missing OUT");
assert.equal(buildAttendanceDayInput([...included,historical]).punches.length,3,"Audit capture remains visible");
for(const evidenceState of ["resolved","voided","excluded"] as const)assert.deepEqual(buildAttendanceDayInput([...included,{...historical,evidenceState,reason:"Retained original evidence"}]).issues,[]);
const pending=buildAttendanceDayInput([...included,{...historical,evidenceState:"pending",reason:"New incoming capture requires review"}]);
assert(pending.issues.some(issue=>issue.includes("New incoming")));assert.equal(pending.missingDirection,"OUT","Unreviewed evidence still participates in the active sequence");
assert.equal(buildAttendanceDayInput([included[0],historical]).missingDirection,"OUT","History never supplies an effective missing OUT");
const excessive=buildAttendanceDayInput([included[0],{...included[1],at:"2026-10-08T09:00:00+08:00"}]);assert.equal(excessive.complete,false);assert(excessive.issues.some(issue=>issue.includes("24 hours")),"Shared findings retain the batch duration guard");
console.log(JSON.stringify({passed:true,checks:23,scope:"Day-scoped source eligibility, effective sequence and visible informational evidence"}));
