import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { eq, sql } from "drizzle-orm";
import { matchingDatabase } from "./attendanceTest/matchingDatabase";
import { employees, payrollPeriods, payrollRuns, attendanceRawLogs } from "@/db/schema";
import { attendanceSourceRuns as runs, attendanceSourceMappings as mappings, attendanceResolutions as resolutions, attendanceResolutionLogs as manualLogs } from "@/db/attendanceSourceSchema";
import { reconcileAttendanceSource } from "@/lib/payroll/attendanceSourceSync";
import { proposeAttendanceResolution, reviewAttendanceResolution, loadAttendanceReadiness, applySourceResolution } from "@/lib/payroll/attendanceResolution";
import { originalPunchDateTime, periodAttendanceScope, validateManualSequence, type ManualPunch, type ResolutionKind } from "@/lib/payroll/attendanceResolutionModel";
import { assertAttendanceSourceReady, attendanceSourceVersion, confirmAttendanceSourceSummaryRefresh } from "@/lib/payroll/attendanceSourceGuard";
import type { SourcePunch } from "@/lib/payroll/attendanceSourceClient";
import type { DbClient } from "@/db";

async function main() {
  process.env.ATTENDANCE_SOURCE_ENABLED = "true";
  process.env.ATTENDANCE_CORRECTION_TOKEN = "synthetic-correction-key-only-".repeat(3);
  const { pg, database, client } = await matchingDatabase();
  const actor = randomUUID(), employeeId = randomUUID(), periodId = randomUUID();
  await database.insert(employees).values({ id: employeeId, employeeNo: "00552", firstName: "Synthetic", lastName: "Employee" });
  await database.insert(payrollPeriods).values({ id: periodId, code: "TEST-2026-09-B", payrollTerms: "Semi-Monthly", cycle: "B", year: 2026, month: 9, startDate: "2026-09-16", endDate: "2026-09-30", nominalPayDate: "2026-09-30", adjustedPayDate: "2026-09-30" });
  await database.insert(mappings).values({ sourceEmployeeId: "552", employeeId, actorUserId: actor, reason: "Verified fixture" });
  let records: SourcePunch[] = [];
  const punch = (type: "IN" | "OUT", local: string, flags: string[] = []): SourcePunch => ({ eventId: randomUUID(), employeeId: "552", employeeName: "Synthetic Employee", originalEmployeeId: "552", originalEmployeeName: "Synthetic Employee", branchId: "TEST", type, capturedAt: new Date(local + "+08:00").toISOString(), receivedAt: "2026-10-01T01:00:00.000Z", updatedAt: "2026-10-01T01:00:00.000Z", status: "VALID", clockFlag: false, reviewFlags: flags, reviewResolved: false, correctionVersion: "original" });
  async function sync() { const id = randomUUID(); await database.insert(runs).values({ id, payrollPeriodId: periodId, actorUserId: actor, state: "Fetching", fromDate: "2026-09-15", throughDate: "2026-10-01", startedAt: sql`clock_timestamp()` }); return reconcileAttendanceSource(database as unknown as Parameters<typeof reconcileAttendanceSource>[0], periodId, id, actor, records); }
  const ready = () => loadAttendanceReadiness(periodId, client);
  async function propose(kind: ResolutionKind, manualPunches: ManualPunch[] = [], eventIds: string[] = []) {
    const person = (await ready()).people[0];
    return database.transaction(tx => proposeAttendanceResolution(tx as unknown as DbClient, actor, { periodId, sourceId: "552", version: person.version, kind, reason: "Supervisor verified the actual work", evidence: "Fixture incident reference 42", confirmed: true, manualPunches, eventIds }));
  }
  const review = (id: string, action: "Approve" | "Reject" | "Reverse") => database.transaction(tx => reviewAttendanceResolution(tx as unknown as DbClient, actor, id, action, "Verified fixture evidence"));
  records = [punch("IN", "2026-10-01T09:00:00", ["NO_FOLLOWING_OUT"])];
  const context = await sync(); assert.equal(context.clearedEmployees, 0); assert.equal(context.withheld, 0); assert.equal((await ready()).people[0].contextOnly, true); assert.equal((await database.select().from(attendanceRawLogs)).length, 0);
  records.unshift(punch("IN", "2026-09-30T21:00:00", ["NO_FOLLOWING_OUT"]));
  const held = await sync(); assert.equal(held.withheld, 1); assert.equal(held.boundaryReview, 1); assert.equal(held.clearedEmployees, 1);
  assert.match(originalPunchDateTime(records[0].capturedAt), /Sep 30, 2026/);
  const overnight: ManualPunch[] = [{ type: "OUT", localDateTime: "2026-10-01T06:00" }];
  assert.equal(validateManualSequence(records, overnight, "2026-09-16", "2026-09-30"), null);
  assert.match(validateManualSequence(records, [], "2026-09-16", "2026-09-30")!, /missing or repeated/);
  assert.match(validateManualSequence(records, [{ type: "OUT", localDateTime: "2026-09-31T06:00" }], "2026-09-16", "2026-09-30")!, /invalid/);
  const pending = await propose("Manual", overnight);
  await assert.rejects(() => assertAttendanceSourceReady(periodId, client), /approval/);
  assert.equal((await database.select().from(attendanceRawLogs)).length, 0, "proposal cannot create paid input");
  await review(pending, "Approve");
  await assert.rejects(() => assertAttendanceSourceReady(periodId, client), /sync again/);
  const applied = await sync(); assert.equal(applied.withheld, 0); assert.equal(applied.boundaryReview, 0); assert.equal(applied.clearedEmployees, 0);
  const input = await database.select().from(attendanceRawLogs); assert.equal(input.length, 2); assert.equal(input.find(p => p.direction === "OUT")?.logDate, "2026-10-01"); assert.match(input.find(p => p.direction === "OUT")!.rawText!, /MANUAL_DTR/); assert.equal((await database.select().from(manualLogs)).length, 1);
  const repeat = await sync(); assert.equal(repeat.projected, 0); assert.deepEqual((await database.select().from(attendanceRawLogs)).map(p => p.id), input.map(p => p.id));
  const version = await attendanceSourceVersion(periodId, client); await database.transaction(tx => confirmAttendanceSourceSummaryRefresh(tx as unknown as DbClient, periodId, version));
  assert.equal((await ready()).ready, true);
  await database.insert(payrollRuns).values({ payrollPeriodId: periodId, runNumber: 1, status: "Reviewed" });
  await review(pending, "Reverse"); assert.equal((await database.select().from(payrollRuns))[0].status, "Stale");
  await sync(); assert.equal((await database.select().from(manualLogs)).length, 0); assert.equal((await database.select().from(attendanceRawLogs)).length, 0); await assert.rejects(() => assertAttendanceSourceReady(periodId, client), /unresolved exceptions/);
  const changed = await propose("Manual", overnight); records[0] = { ...records[0], employeeName: "Evidence changed" }; await sync();
  await assert.rejects(() => review(changed, "Approve"), /already changed/);
  assert.equal((await database.select().from(resolutions).where(eq(resolutions.id, changed)))[0].state, "Expired");
  const second = await propose("Manual", overnight); await review(second, "Approve"); records[0] = { ...records[0], clockFlag: true }; await sync();
  assert.equal((await database.select().from(attendanceRawLogs)).length, 0, "changed clock evidence invalidates approved manual hours");
  await assert.rejects(() => propose("Manual", overnight), /clock warning/);
  records[0] = { ...records[0], clockFlag: false }; await sync();
  const duplicates = [records[0], { ...records[0], eventId: randomUUID(), capturedAt: "2026-09-30T13:01:00.000Z", reviewFlags: ["CONSECUTIVE_IN"] }];
  assert.match(validateManualSequence(duplicates, overnight, "2026-09-16", "2026-09-30")!, /missing or repeated/);
  const missingIn = [punch("OUT", "2026-09-16T08:00:00", ["NO_EARLIER_IN"])];
  assert.equal(validateManualSequence(missingIn, [{ type: "IN", localDateTime: "2026-09-15T23:00" }], "2026-09-16", "2026-09-30"), null);
  const paired = [records[0], punch("OUT", "2026-10-01T06:00:00")]; assert.equal(periodAttendanceScope(paired, "2026-09-16", "2026-09-30").relevant.size, 2, "real overnight partner stays in scope");
  records.push(punch("IN", "2026-09-30T21:01:00", ["CONSECUTIVE_IN"])); await sync();
  await assert.rejects(()=>propose("SourceVoid",[],[records[0].eventId,records[2].eventId]),/read-only/);
  assert.equal((await ready()).sourceCorrectionsEnabled,false);
  process.env.ATTENDANCE_SOURCE_ORIGIN="https://fixture.example.test";
  process.env.ATTENDANCE_SOURCE_TOKEN="fixture-reader-token-".repeat(4);
  const sourceVoid=randomUUID(),requests=[{id:randomUUID(),eventId:records[0].eventId,action:"VOID"},{id:randomUUID(),eventId:records[2].eventId,action:"VOID"}];
  await database.insert(resolutions).values({id:sourceVoid,payrollPeriodId:periodId,sourceEmployeeId:"552",employeeId,kind:"SourceVoid",state:"Failed",sourceVersion:"historical",reason:"Historical fixture",evidence:"Historical fixture",manualPunches:[],eventIds:requests.map(r=>r.eventId),sourceRequests:requests,actorUserId:actor,reviewerUserId:actor});
  let attempts=0;const dbForDelivery=database as unknown as Parameters<typeof applySourceResolution>[3];
  const retired=await applySourceResolution(sourceVoid,actor,false,dbForDelivery,async(input,init)=>{attempts++;assert.equal(init?.method,"GET");assert.equal(new URL(String(input)).pathname,"/v1/integra/receipts");return Response.json({state:attempts===1?"Applied":"Not found",id:new URL(String(input)).searchParams.get("id")});});
  assert.match(retired,/1 of 2 historical applications confirmed/);assert.equal(attempts,2);
  assert.equal((await database.select().from(resolutions).where(eq(resolutions.id,sourceVoid)))[0].state,"Expired");
  assert.equal(await applySourceResolution(sourceVoid,actor,false,dbForDelivery,async()=>{throw Error("Retirement must not repeat source requests");}),retired);
  assert.equal(attempts,2);
  // A later read-only import may observe historical source changes made outside Integra.
  records[2] = { ...records[2], status: "VOID", correctionVersion: randomUUID() };
  records[0] = { ...records[0], status: "VOID", correctionVersion: randomUUID() }; await sync();
  const none = await propose("NoAttendance"); await review(none, "Approve"); assert.equal((await sync()).clearedEmployees, 0);
  await database.update(payrollRuns).set({ status: "Posted" }).where(eq(payrollRuns.payrollPeriodId, periodId));
  await assert.rejects(() => review(none, "Reverse"), /closed or posted/);
  console.log("Attendance resolution: dated original records, context-only scope, real overnight pairing, missing IN/OUT, proposal/approval, immutable manual evidence, retry idempotency, reversal, stale evidence/clock rejection, duplicate hold, no-attendance treatment and posted protection passed.");
  await pg.close();
}
main().catch(error => { console.error(error); process.exitCode = 1; });
