import assert from "node:assert/strict";
import { allocateShortfallRecovery, employeeShortfallAmounts, priorShortfallBalance, recoveryLine, shortfallPolicyText, SHORTFALL_POLICY, type ShortfallBalance } from "@/lib/payroll/shortfallModel";
import { reconcileStoredPayrollAmounts } from "@/lib/payroll/storedAmounts";

const balance = (sourceId: string, amount: number, startDate = "2026-09-16"): ShortfallBalance => ({sourceId, employeeId: "one", periodCode: "2026-09-B", startDate, originalCents: amount, recoveredCents: 0, remainingCents: amount});
const balances = [balance("later", 16695, "2026-10-01"), balance("first", 42008), {...balance("other-person", 99999), employeeId: "two"}];
const before = JSON.stringify(balances);
const first = allocateShortfallRecovery(balances, "one", 200);
assert.deepEqual(first.map(row => [row.sourceId, row.amountCents]), [["first", 20000]]);
assert.deepEqual(allocateShortfallRecovery(balances, "one", 500).map(row => [row.sourceId, row.amountCents]), [["first", 42008], ["later", 7992]]);
assert.equal(allocateShortfallRecovery(balances, "one", 1000).reduce((sum, row) => sum + row.amountCents, 0), 58703);
assert.deepEqual(allocateShortfallRecovery(balances, "one", 0), []);
assert.deepEqual(allocateShortfallRecovery(balances, "one", -10), []);
assert.deepEqual(allocateShortfallRecovery([{...balance("part", 42008), recoveredCents: 20000, remainingCents: 22008}], "one", 500).map(row => row.amountCents), [22008]);
assert.equal(JSON.stringify(balances), before, "Preview never mutates posted balances");
assert.throws(() => allocateShortfallRecovery([{...balance("bad", 100), remainingCents: 110}], "one", 20), /Invalid shortfall/);
const line = recoveryLine(first[0]);
const computed = reconcileStoredPayrollAmounts({regularPay: 1000, grossPay: 1000, taxablePay: 1000, nonTaxablePay: 0, totalDeductions: 800, employeeContributions: 800, employerContributions: 0, netPay: 200, lines: [{lineType: "Earning", code: "REG", amount: 1000}, {lineType: "Deduction", code: "SSS", amount: 800}, line]});
assert.equal(computed.netPay, 0);
assert.equal(computed.employeeContributions, 800, "Recovery is not another statutory contribution or tax charge");
assert.equal(computed.taxablePay, 1000, "Recovery does not reduce taxable income twice");
assert.equal(employeeShortfallAmounts(computed).recovered, 200);
assert.equal(employeeShortfallAmounts({grossPay: "337.50", totalDeductions: "757.58", netPay: "-420.08", lines: []}).collected, 337.50);
assert.equal(employeeShortfallAmounts({grossPay: "337.50", totalDeductions: "757.58", netPay: "-420.08", lines: []}).carriedForward, 420.08);
assert.equal(priorShortfallBalance({shortfallBalances: balances}, "one"), 587.03);
assert.match(shortfallPolicyText({shortfallPolicy: SHORTFALL_POLICY}, "Draft"), /On posting/);
assert.match(shortfallPolicyText({shortfallPolicy: SHORTFALL_POLICY}, "Posted"), /Carried forward/);
assert.match(shortfallPolicyText(null, "Posted"), /not authorized/);
assert.match(shortfallPolicyText(null, "Posted", "Reversal"), /no new/);
console.log("PASS shortfall allocation: FIFO, exact cents, partial/full/zero recovery, employee isolation, immutable previews, statutory/tax preservation and historical policy labels");
