import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ProvisionalReviewDayList, ProvisionalReviewFilters } from "@/app/(ntg)/payroll/provisional/review-filters";
import { reviewFixtureRows as rows, reviewFixtureScope as scope } from "./provisionalReviewFixture";
const html = renderToStaticMarkup(<ProvisionalReviewFilters rows={rows} view="attention" scope={scope} onChange={() => {}}/>);
assert.equal((html.match(/<button/g) ?? []).length, 3, "Only three primary phone filters");
assert.ok(html.includes('aria-pressed="true"') && html.includes("3 employees · 4 days") && html.includes("More filters"));
assert.ok(html.includes("Zero recorded earnings") && html.includes("Scheduled, no attendance"));
assert.ok(!html.includes("No work recorded"), "Do not mislabel zero earnings as missing attendance");
const reasons = renderToStaticMarkup(<ProvisionalReviewDayList row={rows[0]} view="attention" scope={scope} onOpen={() => {}} holdHref={day => `/hold?day=${day}`}/>);
assert.ok(reasons.includes('dateTime="2026-10-02"') && reasons.includes("Review missing attendance") && reasons.includes("Add missing OUT"));
assert.ok(reasons.includes("View 1 more matching workday"), "Long lists remain collapsed on the phone");
assert.ok(!reasons.includes("Absent"), "No attendance is a review prompt, not an absence determination");
const resolved = renderToStaticMarkup(<ProvisionalReviewDayList row={rows[2]} view="attention" scope={scope} onOpen={() => {}} holdHref={() => ""}/>);
assert.equal(resolved, "", "Completed corrections do not retain actionable warning UI");
const history = renderToStaticMarkup(<ProvisionalReviewDayList row={rows[2]} view="corrected" scope={scope} onOpen={() => {}} holdHref={() => ""}/>);
assert.ok(history.includes("Saved attendance correction") && history.includes("Philippine time") && history.includes("View corrected attendance"));
const noAttendance = renderToStaticMarkup(<ProvisionalReviewFilters rows={rows} view="scheduled-no-attendance" scope={scope} onChange={() => {}}/>);
assert.ok(noAttendance.includes("does not establish absence"));
console.log("PASS ProvisionalReviewUi: three primary controls, explicit counts, dated actions, phone disclosure, resolved empty state, correction history and accurate absence wording");
