import assert from "node:assert/strict";
import { insertShiftTableSchema } from "@/zod-schemas/shiftTable";
import { describeSchedule, shiftTableScheduleSnapshot } from "@/lib/scheduling/presentation";
import { emptyShiftEditor, newShiftCode, reviewShiftEditor, shiftEditorFromTable, shiftReadbackMatches, unpaidBreak, type ShiftEditorValues } from "@/lib/scheduling/shift-editor";

const identity = { requestId: "00000000-0000-4000-8000-000000000001", code: newShiftCode("00000000-0000-4000-8000-000000000002") };
assert.equal(identity.code.length, 38);
const ordinary = reviewShiftEditor(emptyShiftEditor(), identity);
assert.ok(insertShiftTableSchema.safeParse(ordinary.payload).success);
assert.equal(ordinary.preview.hoursPerDay, 8);
assert.equal(ordinary.payload.punchPolicy, "outer");
const intended: ShiftEditorValues = { periods: [{ fromTime: "08:00", toTime: "11:00" }, { fromTime: "15:30", toTime: "21:00" }], gaps: [unpaidBreak()], regularBreaks: [], overtimeBreaks: [] };
const sourceCopy = structuredClone(intended);
const split = reviewShiftEditor(intended, identity);
assert.ok(insertShiftTableSchema.safeParse(split.payload).success);
assert.deepEqual(intended, sourceCopy);
assert.equal(split.preview.hoursPerDay, 8.5);
assert.equal(split.payload.punchPolicy, "split_gaps");
assert.equal(split.payload.breaks.filter(row => row.requiresPunches).length, 1);
assert.equal(describeSchedule(shiftTableScheduleSnapshot(split.preview)).periodsLabel, "08:00–11:00 / 15:30–21:00");
assert.match(describeSchedule(shiftTableScheduleSnapshot(split.preview)).label, /8h normal \+ 0.5h OT.*4 punches required/);
const overnight = reviewShiftEditor({ ...intended, periods: [{ fromTime: "22:00", toTime: "02:00" }, { fromTime: "03:00", toTime: "06:00" }] }, identity);
assert.ok(insertShiftTableSchema.safeParse(overnight.payload).success);
assert.equal(overnight.preview.hoursPerDay, 7);
assert.match(describeSchedule(shiftTableScheduleSnapshot(overnight.preview)).periodsLabel, /02:00 \(\+1 day\)/);
const paid = reviewShiftEditor({ ...intended, gaps: [{ pay: "partial", unpaidMinutes: "240" }], regularBreaks: [{ fromTime: "17:00", toTime: "17:30", pay: "paid", unpaidMinutes: "" }], overtimeBreaks: [{ fromTime: "21:30", toTime: "21:45", ...unpaidBreak() }] }, identity);
assert.ok(insertShiftTableSchema.safeParse(paid.payload).success);
assert.equal(paid.preview.hoursPerDay, 9);
assert.equal(paid.preview.paidBreakMinutes, 60);
assert.equal(paid.payload.breaks[0].deductHours, 4);
assert.equal(paid.payload.breaks[1].deduct, false);
assert.equal(paid.payload.breaks[5].deductMinutes, 15);
assert.equal(paid.payload.breaks[5].requiresPunches, false);
assert.deepEqual(reviewShiftEditor(shiftEditorFromTable(paid.preview).values, identity).payload, paid.payload, "Explicit gaps and paid/partial/OT breaks must round trip");
assert.ok(shiftReadbackMatches({ ...paid.preview, id: 800, version: 2, archivedAt: "2026-10-10T00:00:00.000Z" }, paid.preview), "Immutable definition remains verifiable if another admin archives the version after save");
assert.ok(!shiftReadbackMatches({ ...paid.preview, code: "DIFFERENT" }, paid.preview), "Readback verifies hidden identity, not just visible text");
assert.ok(!shiftReadbackMatches({ ...paid.preview, breaks: paid.preview.breaks.map((row, index) => index ? row : { ...row, requiresPunches: false }) }, paid.preview));
const legacy = { ...paid.preview, id: 19, version: 3, code: "SPLIT - N", description: "Existing name", calculationPolicy: "legacy" as const, punchPolicy: "legacy" as const, breaks: paid.preview.breaks.map(row => ({ ...row, requiresPunches: false })) };
const oldCopy = structuredClone(legacy);
const loaded = shiftEditorFromTable(legacy);
assert.equal(loaded.values.periods.length, 2);
assert.equal(loaded.values.regularBreaks.length, 1);
assert.equal(loaded.values.gaps[0].pay, "partial");
assert.equal(loaded.notices.length, 1);
const revised = reviewShiftEditor(loaded.values, { ...identity, id: legacy.id, expectedVersion: legacy.version, code: legacy.code, description: legacy.description });
assert.equal(revised.payload.code, legacy.code);
assert.equal(revised.payload.description, legacy.description);
assert.equal(revised.payload.expectedVersion, 3);
assert.equal(revised.payload.breaks.filter(row => row.requiresPunches).length, 1);
assert.deepEqual(legacy, oldCopy);
const multi = reviewShiftEditor({ ...intended, periods: [{ fromTime: "08:00", toTime: "11:00" }, { fromTime: "12:00", toTime: "15:00" }, { fromTime: "16:00", toTime: "18:00" }], gaps: [unpaidBreak(), unpaidBreak()] }, identity);
assert.match(describeSchedule(shiftTableScheduleSnapshot(multi.preview)).label, /6 punches required/);
assert.throws(() => reviewShiftEditor({ ...intended, periods: [{ fromTime: "08:00", toTime: "08:00" }] }, identity), /gap/);
assert.throws(() => reviewShiftEditor({ ...intended, periods: [{ fromTime: "08:00", toTime: "12:00" }, { fromTime: "11:00", toTime: "21:00" }] }, identity), /chronological/);
assert.throws(() => reviewShiftEditor({ ...intended, periods: [{ fromTime: "08:00", toTime: "12:00" }, { fromTime: "12:00", toTime: "21:00" }] }, identity), /gap/);
assert.throws(() => reviewShiftEditor({ ...intended, periods: [{ fromTime: "25:00", toTime: "11:00" }, intended.periods[1]] }, identity), /valid start/);
assert.throws(() => reviewShiftEditor({ ...intended, regularBreaks: [{ fromTime: "10:30", toTime: "12:00", ...unpaidBreak() }] }, identity), /fit within/);
assert.throws(() => reviewShiftEditor({ ...intended, gaps: [{ pay: "partial", unpaidMinutes: "270" }] }, identity), /partly paid/);
assert.throws(() => reviewShiftEditor({ ...intended, regularBreaks: [{ fromTime: "17:00", toTime: "18:00", ...unpaidBreak() }], overtimeBreaks: [{ fromTime: "17:30", toTime: "18:30", ...unpaidBreak() }] }, identity), /overlap/);
assert.throws(() => reviewShiftEditor({ ...intended, regularBreaks: Array.from({ length: 5 }, () => ({ fromTime: "17:00", toTime: "18:00", ...unpaidBreak() })) }, identity), /five regular/);
assert.throws(() => reviewShiftEditor({ ...intended, overtimeBreaks: Array.from({ length: 3 }, () => ({ fromTime: "21:00", toTime: "22:00", ...unpaidBreak() })) }, identity), /two overtime/);
console.log("PASS shift editor: regular/split/overnight timelines, 8+OT preview, explicit punch gaps, paid/partial/OT round trip, legacy inference, stable revision identity, validation and immutability");
