"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ProvisionalPayroll, ProvisionalAmounts, ProvisionalEmployee, ProvisionalLine, ProvisionalGroup, ProvisionalDay } from "@/lib/payroll/provisionalTypes";
import { formatWorkday } from "@/lib/payroll/dateDisplay";
import { DaySchedule } from "../attendance-source/day-schedule";
import { DayCorrection } from "./day-correction";
import { PayrollWorkspaceNav } from "../PayrollPageNav";

const button = "inline-flex min-h-11 items-center justify-center rounded-lg border px-3 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 disabled:opacity-50";
const field = "mt-1 block min-h-11 w-full min-w-0 rounded-lg border bg-background px-3 py-2 text-sm";
const money = (value: number | null | undefined) => value == null ? "Unavailable" : new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(value);
const hours = (minutes: number) => `${Math.floor(minutes / 60)}h ${Math.round(minutes % 60)}m`;
const stamp = (value: string) => new Intl.DateTimeFormat("en-PH", { timeZone: "Asia/Manila", month: "short", day: "numeric", hour: "numeric", minute: "2-digit", second: "2-digit" }).format(new Date(value));
type Scope = { periodId: string; group: ProvisionalGroup; asOfDate: string; departmentId: string; employeeId: string; day: string; q: string; edit: "attendance" | "schedule" | ""; view: "attention" | "all" | "no-work"; year: string; runId: string };
type Props = { periods: { id: string; code: string; startDate: string; endDate: string }[]; departments: { id: number; name: string }[]; initial: Record<string, string | undefined>; today: string };
function scopeFrom(params: Record<string, string | undefined>, fallback: string): Scope { return { periodId: params.periodId || fallback, group: params.group === "Monthly" ? "Monthly" : "Daily", asOfDate: params.asOfDate || "", departmentId: params.departmentId || "", employeeId: params.employeeId || "", day: params.day || "", q: params.q || "", edit: params.edit === "attendance" || params.edit === "schedule" ? params.edit : "", view: params.view === "attention" || params.view === "no-work" ? params.view : "all", year: params.year || "", runId: params.runId || "" }; }
function queryFor(scope: Scope) { return new URLSearchParams(Object.entries(scope).filter(([, value]) => !!value)); }
function needsAttention(day: ProvisionalDay) { return !["Future", "In progress"].includes(day.status) && (day.payrollHold || day.status === "Incomplete" || (day.status === "Schedule missing" && day.punches.length > 0) || !!day.attendance?.issues.length); }
function attendanceAction(day: ProvisionalDay) { return day.attendance?.canConfirmExisting ? "Review existing punches" : day.attendance?.missingDirection ? `Add missing ${day.attendance.missingDirection}` : day.status === "Incomplete" ? "Review attendance issue" : "View attendance"; }
function attendanceNote(value: string) { const labels: Record<string, string> = { MISSING_IN: "Missing IN", MISSING_OUT: "Missing OUT", ODD_PUNCH_COUNT: "Unpaired punch", INCOMPLETE_SEQUENCE: "Incomplete IN/OUT sequence", MISSING_SCHEDULE: "Set this day’s schedule to calculate work", NO_SCHEDULE: "Set this day’s schedule to calculate work" }; return labels[value] || value.replaceAll("_", " ").toLowerCase().replace(/^./, char => char.toUpperCase()); }
function sum(rows: ProvisionalEmployee[], scenario: "recorded" | "forecast"): ProvisionalAmounts { return rows.reduce((total, row) => { const amount = row[scenario]; return amount ? { gross: total.gross + amount.gross, deductions: total.deductions + amount.deductions, net: total.net + amount.net, shortfall: total.shortfall + amount.shortfall } : total; }, { gross: 0, deductions: 0, net: 0, shortfall: 0 }); }
function Lines({ lines }: { lines: ProvisionalLine[] }) { return <ul className="divide-y">{lines.map((line, index) => <li key={`${line.code}:${index}`} className="flex min-w-0 items-start justify-between gap-4 py-2 text-sm"><span className="min-w-0 break-words">{line.description || line.code}<small className="block text-muted-foreground">{line.code} · {line.lineType}{line.quantity != null ? ` · ${line.quantity} × ${money(line.rate)}` : ""}</small></span><span className="shrink-0 tabular-nums">{money(line.amount)}</span></li>)}</ul>; }

export function ProvisionalWorkspace({ periods, departments, initial, today }: Props) {
  const lastCompletedDay=new Date(Date.parse(`${today}T00:00:00Z`)-86400000).toISOString().slice(0,10);
  const [scope, setScope] = useState(() => scopeFrom(initial, periods[0]?.id ?? ""));
  const [data, setData] = useState<ProvisionalPayroll | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const [loadedScope, setLoadedScope] = useState("");
  const repair = scope.edit;
  const [notice, setNotice] = useState(""), [stale, setStale] = useState(false);
  const active = useRef(0), abort = useRef<AbortController | null>(null), errorRef = useRef<HTMLDivElement>(null), detailRef = useRef<HTMLDivElement>(null);
  const { periodId, group, asOfDate, departmentId } = scope;
  const readScope = `${periodId}:${group}:${asOfDate}:${departmentId}`;
  const latestScope = useRef(readScope); latestScope.current = readScope;
  const viewKey = `${readScope}:${scope.employeeId}:${scope.day}:${scope.edit}`;
  const latestView = useRef(viewKey); latestView.current = viewKey;
  const reload = useCallback(async () => {
    if (!periodId) return;
    const id = ++active.current;
    abort.current?.abort(); const controller = new AbortController(); abort.current = controller;
    setLoading(true); setError("");
    try {
      const query = new URLSearchParams({ periodId, group, ...(asOfDate ? { asOfDate } : {}), ...(departmentId ? { departmentId } : {}) });
      const response = await fetch(`/api/payroll/provisional?${query}`, { cache: "no-store", credentials: "same-origin", signal: AbortSignal.any([controller.signal, AbortSignal.timeout(55000)]) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "The estimate could not load.");
      if (id !== active.current) return;
      setData(result as ProvisionalPayroll); setLoadedScope(readScope); setStale(false); return result as ProvisionalPayroll;
    } catch (cause) {
      if (controller.signal.aborted || id !== active.current) return;
      const message = cause instanceof Error && cause.name !== "TimeoutError" ? cause.message : "The estimate read timed out. Retry here; no payroll was created.";
      setError(message); setStale(true); throw new Error(message);
    } finally { if (id === active.current) setLoading(false); }
  }, [periodId, group, asOfDate, departmentId, readScope]);
  useEffect(() => { void reload().catch(() => {}); return () => abort.current?.abort(); }, [reload]);
  useEffect(() => { if (error) errorRef.current?.focus(); }, [error]);
  useEffect(() => { const back = () => setScope(scopeFrom(Object.fromEntries(new URLSearchParams(location.search)), periods[0]?.id ?? "")); window.addEventListener("popstate", back); return () => window.removeEventListener("popstate", back); }, [periods]);
  function navigate(patch: Partial<Scope>, replace = false) { const next = { ...scope, edit: "" as const, ...patch }; if(patch.periodId && patch.periodId !== scope.periodId || patch.group && patch.group !== scope.group)next.runId=""; setScope(next); setNotice(""); history[replace ? "replaceState" : "pushState"](null, "", `/payroll/provisional?${queryFor(next)}`); }
  async function changed(outcome?: string) { if(latestScope.current!==readScope)throw new Error("The selected period changed. The saved correction remains available in its original period."); setStale(true); if(latestView.current===viewKey)setNotice("Change saved · Updating estimate. Previous amounts are shown until the read completes."); try { const result=await reload(); if(!result||latestScope.current!==readScope)throw new Error("Estimate read superseded."); if(latestView.current===viewKey){ navigate({ edit: "" }, true); setNotice(outcome || (repair === "schedule" ? "Schedule saved · Estimate updated. Payroll is unchanged." : "Correction saved · Attendance and estimate updated. Payroll is unchanged.")); setTimeout(() => detailRef.current?.focus(), 0); } } catch { if(latestView.current===viewKey)setNotice("Change saved · Estimate update pending. Retry the estimate read; do not save the correction again."); throw new Error("Change saved, estimate update pending."); } }
  const current = loadedScope === readScope && data?.period.id === periodId && data.group === group && (!asOfDate || data.asOfDate === asOfDate) ? data : null;
  const rows = current?.rows.filter(row => !scope.departmentId || String(row.departmentId) === scope.departmentId) ?? [];
  const attentionDays = rows.flatMap(row => row.days.filter(needsAttention).map(day => ({ row, day })));
  const visible = rows.filter(row => `${row.name} ${row.employeeNo}`.toLowerCase().includes(scope.q.toLowerCase()) && (scope.view === "all" || scope.view === "attention" && (row.status === "Unavailable" || row.days.some(needsAttention)) || scope.view === "no-work" && row.status === "No work — ₱0"));
  const employee = current?.rows.find(row => row.employeeId === scope.employeeId);
  const selectedDay = employee?.days.find(day => day.date === scope.day);
  const recorded = sum(rows, "recorded"), forecast = sum(rows, "forecast"), unavailable = rows.filter(row => !row.recorded || !row.forecast).length;
  const period = periods.find(item => item.id === periodId);
  const payrollHref = `/payroll?${new URLSearchParams({ periodId, group, ...(period ? { year: period.startDate.slice(0, 4) } : {}) })}`;
  const returnTo = `/payroll/provisional?${queryFor(scope)}`;
  const reviewQuery = new URLSearchParams({ periodId, group, ...(period ? { year: period.startDate.slice(0, 4) } : {}), ...(scope.departmentId ? { departmentId: scope.departmentId } : {}), employeeId: scope.employeeId, day: scope.day, returnTo });
  const reviewHref = `/payroll/attendance-batch?${reviewQuery}`;
  function holdHref(employeeId: string, day: string) { return `/payroll/attendance-hold?${new URLSearchParams({ periodId, group, year:period?.startDate.slice(0,4)||scope.year, employeeId, day })}`; }
  function pickEmployee(id: string) { navigate({ employeeId: id, day: "" }); setTimeout(() => detailRef.current?.focus(), 0); }
  return <div className="mx-auto w-full min-w-0 max-w-[1440px] space-y-5 pb-12">
    <PayrollWorkspaceNav activeSection="estimate" context={{...scope, year:period?.startDate.slice(0,4)}} />
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Provisional payroll</h1><p className="mt-1 text-sm text-muted-foreground">Recorded earnings and the period’s possible cost, before payroll day.</p></div><Link className={button} href={`/schedules?${new URLSearchParams({ periodId, group, ...(scope.departmentId ? { departmentId: scope.departmentId } : {}), ...(scope.employeeId ? {employeeId:scope.employeeId} : {}), ...(scope.day ? {day:scope.day} : {}), view: "period" })}`}>Schedules</Link></header>
    <div className="flex flex-wrap gap-2" aria-label="Attendance tools"><Link className={button} href={reviewHref}>Batch changes</Link><Link className={button} href={`${reviewHref}&view=history#attendance-history`}>History</Link><Link className={button} href={`/payroll/attendance-sources?${reviewQuery}`}>Attendance sources</Link></div>
    <div className="grid min-w-0 gap-3 rounded-xl border bg-muted/20 p-3 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_auto]">
      <label className="min-w-0 text-xs font-medium">Payroll period<select className={field} value={periodId} onChange={event => navigate({ periodId: event.target.value, employeeId: "", day: "", asOfDate: "", runId: "", year: periods.find(item=>item.id===event.target.value)?.startDate.slice(0,4) || "" })}>{periods.map(item => <option key={item.id} value={item.id}>{item.code} · {item.startDate} – {item.endDate}</option>)}</select></label>
      <label className="min-w-0 text-xs font-medium">Branch<select className={field} value={scope.departmentId} onChange={event => navigate({ departmentId: event.target.value, employeeId: "", day: "" })}><option value="">All branches</option>{departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="min-w-0 text-xs font-medium">Recorded through<input className={field} type="date" value={scope.asOfDate || current?.asOfDate || ""} max={lastCompletedDay} onChange={event => navigate({ asOfDate: event.target.value })} /><span className="mt-1 block text-xs font-normal text-muted-foreground">Philippine workday · Defaults to yesterday</span></label>
      <button className={`${button} self-start sm:self-center`} disabled={loading || !periodId} onClick={() => void reload().then(result => {if(result&&latestScope.current===readScope&&latestView.current===viewKey)setNotice("Estimate refreshed. Payroll is unchanged.");}).catch(() => {})}>{loading ? "Calculating estimate…" : "Refresh estimate"}</button>
    </div>
    <div className="flex flex-wrap gap-2" role="tablist" aria-label="Payroll group" onKeyDown={event => { if (!event.ctrlKey && !event.metaKey && !event.altKey && ["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) { event.preventDefault(); const next = event.key === "Home" ? "Daily" : event.key === "End" ? "Monthly" : group === "Daily" ? "Monthly" : "Daily"; navigate({ group: next, employeeId: "", day: "" }); document.getElementById(`provisional-${next}`)?.focus(); } }}>
      {(["Daily", "Monthly"] as const).map(item => <button role="tab" id={`provisional-${item}`} aria-selected={item === group} aria-controls="provisional-panel" tabIndex={item === group ? 0 : -1} key={item} className={`${button} ${item === group ? "bg-blue-700 text-white" : ""}`} onClick={() => navigate({ group: item, employeeId: "", day: "" })}>{item === "Daily" ? "Daily payroll" : "Monthly salary"}</button>)}
    </div>
    {notice && <p role="status" className="rounded-lg border border-blue-300 p-3 text-sm">{notice}</p>}
    {error && <div ref={errorRef} role="alert" tabIndex={-1} className="space-y-2 rounded-lg border border-red-400 p-3 text-sm focus:ring-2 focus:ring-red-500"><p>{error}</p>{current && <p>Previous estimate shown. It has not been confirmed against the latest inputs.</p>}<button className={button} disabled={loading} onClick={() => void reload().catch(() => {})}>Retry estimate</button></div>}
    {!periodId && <p>No payroll periods are available.</p>}
    {loading && <p role="status" className="text-sm">Reading attendance, schedules and configured pay rules… No payroll draft is created.</p>}
    {current && <section id="provisional-panel" role="tabpanel" aria-labelledby={`provisional-${group}`} className="min-w-0 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><p>{stale || loading ? "Previous estimate · update pending" : "Estimate updated"} · {stamp(current.generatedAt)} Philippine time</p><p>Recorded through {formatWorkday(current.asOfDate)} · Earning month {current.period.earningMonth}</p></div>
      {current.postedRun && <p className="rounded-lg border p-3 text-sm">This group has a posted payroll. These are current-input estimates, separate from the posted statement. <Link className="underline" href={`${payrollHref}&runId=${current.postedRun.id}`}>View posted payroll</Link>.</p>}
      {!!current.warnings.length && <details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-semibold">Calculation notes · {current.warnings.length}</summary><ul className="mt-2 list-inside list-disc">{current.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul></details>}
      {employee ? <div ref={detailRef} tabIndex={-1} className="min-w-0 space-y-4 outline-none">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><button className={`${button} mb-2`} onClick={() => navigate({ employeeId: "", day: "" })}>← All employees</button><h2 className="text-xl font-semibold">{employee.name}</h2><p className="text-sm text-muted-foreground">{employee.employeeNo} · {employee.departmentName || "No branch"}{group === "Monthly" ? ` · Pays in ${employee.payoutHalf === "A" ? "first" : "second"} half` : ""}</p></div><span className="rounded-full border px-3 py-1 text-sm">{employee.status}</span></div>
        {repair && selectedDay ? <div className="space-y-4"><button className={button} onClick={() => navigate({ edit: "" }, true)}>← Back to employee estimate</button>{repair === "attendance" ? <DayCorrection key={`${periodId}:${employee.employeeId}:${selectedDay.date}`} period={{ ...current.period, posted: !!current.postedRun }} employeeId={employee.employeeId} day={selectedDay.date} reviewHref={reviewHref} payrollHold={selectedDay.payrollHold} holdHref={holdHref(employee.employeeId,selectedDay.date)} onSaved={changed} /> : <div><h3 className="text-xl font-semibold">Change schedule · {formatWorkday(selectedDay.date)}</h3><p className="mb-3 text-sm">{employee.name} · Attendance punches stay unchanged.</p><DaySchedule key={`${employee.employeeId}:${selectedDay.date}`} employeeId={employee.employeeId} day={selectedDay.date} periodId={periodId} label="Edit this day’s schedule" expanded onSaved={changed} /></div>}</div> : <>
          <AmountCards group={group} recorded={employee.recorded} forecast={employee.forecast} />
          {employee.postedCredits > 0 && <p className="text-sm">Previously posted earnings: {money(employee.postedCredits)}. Posted payments are preserved.</p>}
          {!!employee.warnings.length && <ul className="list-inside list-disc rounded-lg border border-amber-400 p-3 text-sm">{employee.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul>}
          <div className="grid gap-3 lg:grid-cols-2"><details className="rounded-lg border p-3"><summary className="flex min-h-11 cursor-pointer items-center font-semibold">Recorded calculation and deductions</summary><Lines lines={employee.recordedLines} /></details><details className="rounded-lg border p-3"><summary className="flex min-h-11 cursor-pointer items-center font-semibold">Forecast calculation and deductions</summary><p className="text-xs text-muted-foreground">{current.forecastAssumption}</p><Lines lines={employee.forecastLines} /></details></div>
          <h3 className="font-semibold">Workdays</h3><p className="text-xs text-muted-foreground">{group === "Monthly" ? "Fixed monthly salary is not reduced by missing logs. " : ""}No recorded work requires no correction. Future schedules are a forecast.</p>
          <div className="space-y-2">{employee.days.map(day => <WorkdayCard key={day.date} day={day} holdHref={holdHref(employee.employeeId,day.date)} onOpen={edit => navigate({ day: day.date, edit }, true)} />)}</div>
        </>}
      </div> : <>
        {scope.employeeId && <p role="status" className="rounded border p-3 text-sm">This employee is not in the selected payroll group. Choose another employee or switch groups.</p>}
        <p className="text-xs text-muted-foreground">{scope.departmentId ? departments.find(item => String(item.id) === scope.departmentId)?.name : "All branches"} · Totals for all {rows.length} {group.toLowerCase()} employees{scope.q ? " · Search does not change these totals" : ""}</p>
        <AmountCards group={group} recorded={recorded} forecast={forecast} />
        {unavailable > 0 && <p className="rounded-lg border border-amber-400 p-3 text-sm">{unavailable} employee estimate(s) unavailable and excluded from totals. Open their details for the reason.</p>}
        <div className="flex flex-wrap gap-2" aria-label="Employee view">{([{ value: "all", label: `All employees · ${rows.length}` }, { value: "attention", label: `Needs attention · ${attentionDays.length} days${unavailable ? ` · ${unavailable} unavailable estimates` : ""}` }, { value: "no-work", label: `No work recorded · ${rows.filter(row=>row.status==="No work — ₱0").length}` }] as const).map(item=><button key={item.value} className={`${button} ${scope.view===item.value?"bg-blue-700 text-white":""}`} aria-pressed={scope.view===item.value} onClick={()=>navigate({view:item.value},true)}>{item.label}</button>)}</div>
        <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Employees · {visible.length} shown</h2><label className="w-full text-xs sm:w-72">Find employee<input className={field} type="search" placeholder="Name or employee number" value={scope.q} onChange={event => navigate({ q: event.target.value }, true)} /></label></div>
        <div className="divide-y overflow-hidden rounded-xl border">{visible.length ? visible.map(row => <div key={row.employeeId} className="p-4"><div className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1.5fr)_repeat(3,minmax(0,1fr))]"><div className="min-w-0"><button className="min-h-11 text-left font-semibold text-blue-700 underline dark:text-blue-300" onClick={() => pickEmployee(row.employeeId)}>{row.name} →</button><p className="text-xs text-muted-foreground">{row.employeeNo} · {row.departmentName || "No branch"}</p><p className="mt-1 text-xs">{row.status !== "Available" ? row.status : group === "Monthly" ? "Full salary · scheduled this half" : row.days.some(needsAttention) ? `${row.days.filter(needsAttention).length} day(s) need attention` : "Recorded work and future schedule shown"}</p></div><Amount label={group === "Monthly" ? "Salary due" : "Recorded gross"} value={row.recorded?.gross} /><Amount label="Forecast gross" value={row.forecast?.gross} /><Amount label="Forecast payout" value={row.forecast?.net} bold /></div>{scope.view==="attention"&&<ul className="mt-3 space-y-2">{row.days.filter(needsAttention).map(day=><li key={day.date} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-muted/30 px-3 py-2 text-sm"><div><time dateTime={day.date}>{formatWorkday(day.date)}</time><p className="text-xs text-muted-foreground">{day.payrollHold?"Attendance time held by administrator decision":day.status==="Schedule missing"?"Schedule needed to calculate work":day.attendance?.issues.map(attendanceNote).join(" · ")||"Review the IN/OUT sequence"}</p></div>{day.payrollHold?<Link className={button} href={holdHref(row.employeeId,day.date)}>Review held time</Link>:<button className={button} onClick={()=>navigate({employeeId:row.employeeId,day:day.date,edit:day.status==="Schedule missing"?"schedule":"attendance"})}>{day.status==="Schedule missing"?"Set schedule":attendanceAction(day)}</button>}</li>)}</ul>}</div>) : <p className="p-5 text-sm">{scope.view==="attention"?"No attention items match this branch, group and search.":"No employees match this branch, group and search."}</p>}</div>
      </>}
      <details className="rounded-lg border bg-muted/20 p-3 text-sm"><summary className="flex min-h-11 cursor-pointer items-center font-semibold">How this estimate works</summary><p>{current.forecastAssumption}</p><p className="mt-2">Missing or uncalculable attendance contributes no attendance-based work. Approved leave, holiday rules and configured earnings still apply. No deductions are collected, loans marked paid, or financial drafts saved by viewing this screen.</p><p className="mt-2">{group === "Monthly" ? "Monthly salary uses the selected payout half and whole-month deductions, including unpaid installments from both halves. Prior posted earnings and deductions are credited." : "Daily employees with no earnings have no deduction collection. Existing carry-forward rules are included without collecting a balance."}</p><p className="mt-2 break-all text-xs text-muted-foreground">Input revision: {current.inputRevision}</p></details>
    </section>}
  </div>;
}
function WorkdayCard({ day, onOpen, holdHref }: { day: ProvisionalDay; onOpen: (edit: "attendance" | "schedule") => void; holdHref: string }) {
  const issues = [...new Set([...(day.attendance?.issues ?? []), ...day.warnings.map(attendanceNote)])];
  return <section aria-label={`Workday ${formatWorkday(day.date)}`} className="grid min-w-0 gap-3 rounded-xl border p-3 xl:grid-cols-[160px_1fr_1.5fr_1fr_auto]">
    <time dateTime={day.date} className="min-w-0 text-sm font-semibold">{formatWorkday(day.date)}</time>
    <div className="min-w-0 text-sm"><p>{day.isRestDay ? "Rest day" : day.scheduleIn && day.scheduleOut ? `${day.scheduleIn}–${day.scheduleOut}` : "Schedule unconfigured"}</p><p className="text-xs text-muted-foreground">{day.scheduleSource}</p><button className="min-h-11 text-left text-sm font-semibold text-blue-700 underline dark:text-blue-300" onClick={() => onOpen("schedule")}>Change schedule</button></div>
    <div className="min-w-0 break-words text-sm">{day.attendance?.punches.length ? day.attendance.punches.map(punch => <p key={punch.id}>{punch.type} · {stamp(punch.at)}{!punch.included && <span className="block text-xs text-amber-700 dark:text-amber-300">Not counted · {punch.reason || "Review required"}</span>}</p>) : day.punches.length ? day.punches.map((punch, index) => <p key={index}>{punch}</p>) : <p className="text-muted-foreground">No recorded punches</p>}{issues.length > 0 && <details className="mt-1 text-xs"><summary className="min-h-9 cursor-pointer text-amber-700 dark:text-amber-300">{issues[0]}{issues.length>1?` · ${issues.length-1} more note(s)`:""}</summary><ul className="space-y-1">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul></details>}</div>
    <div className="text-sm"><p>{day.attendance?.complete && day.status === "Recorded" ? "Complete" : day.status}</p><p className="mt-1 text-xs text-muted-foreground">{day.status === "Future" ? `${hours(day.scheduledMinutes)} planned` : `${hours(day.workedMinutes)} recorded`}</p>{day.attendance?.complete && day.status === "Recorded" && !needsAttention(day) && <p className="mt-1 text-xs text-muted-foreground">No correction needed</p>}</div>
    <div className="flex flex-wrap gap-2 self-start">{day.payrollHold&&<Link className={button} href={holdHref}>Review held time</Link>}<button className={button} onClick={() => onOpen("attendance")}>{attendanceAction(day)}</button></div>
  </section>;
}
function Amount({ label, value, bold = false }: { label: string; value?: number | null; bold?: boolean }) { return <div className="flex items-baseline justify-between gap-3 text-sm sm:block"><p className="text-xs text-muted-foreground">{label}</p><p className={`${bold ? "font-bold" : "font-medium"} mt-1 break-words tabular-nums`}>{money(value)}</p></div>; }
function AmountCards({ group, recorded, forecast }: { group: ProvisionalGroup; recorded: ProvisionalAmounts | null; forecast: ProvisionalAmounts | null }) { return <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{group === "Monthly" ? "Salary due this half" : "Recorded gross"}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{money(recorded?.gross)}</p><p className="mt-1 text-xs text-muted-foreground">After estimated deductions: {money(recorded?.net)}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Forecast period gross</p><p className="mt-2 text-2xl font-semibold tabular-nums">{money(forecast?.gross)}</p><p className="mt-1 text-xs text-muted-foreground">{group === "Monthly" ? "Missing phone logs do not reduce salary" : "Recorded earnings + future scheduled work"}</p></div><div className="rounded-xl border border-blue-400 bg-blue-50 p-4 text-blue-950 dark:bg-blue-950 dark:text-blue-50"><p className="text-xs">Forecast payout</p><p className="mt-2 text-2xl font-semibold tabular-nums">{money(forecast?.net)}</p><p className="mt-1 text-xs">After {money(forecast?.deductions)} estimated deductions{forecast?.shortfall ? ` · ${money(forecast.shortfall)} shortfall` : ""}</p></div></div>; }
