"use client";

import { useState } from "react";
import Link from "next/link";
import { originalPunchDateTime, type AttendanceReadiness, type ManualPunch, type ResolutionKind, type ResolutionPerson } from "@/lib/payroll/attendanceResolutionModel";
import { attendancePeriodUrl } from "@/lib/payroll/attendanceSourcePeriods";
import { proposeAttendanceResolutionAction, reviewAttendanceResolutionAction, retryAttendanceSourceCorrectionAction, attendanceReadinessAction } from "@/app/actions/attendanceSourceAction";

const button = "min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50";
const input = "mt-1 block min-h-11 w-full min-w-0 rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900";
const box = "rounded-xl border border-slate-200 bg-white p-4 sm:p-5";
type Result = { ok: true; data: string } | { ok: false; error: string };

export function AttendanceReadinessCard({ data, error, compact = false }: { data: AttendanceReadiness; error?: string | null; compact?: boolean }) {
  const base = attendancePeriodUrl("/payroll/attendance-source", Number(data.startDate.slice(0, 4)), data.periodId);
  const cases = data.people.filter(p => p.issues.length && !p.contextOnly).length;
  return <section aria-label="Payroll attendance readiness" className={`${box} space-y-3 ${data.ready && !error ? "border-emerald-300" : "border-amber-300 bg-amber-50"}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><h2 className="text-lg font-semibold">{data.code} {data.ready && !error ? "attendance is ready for payroll review" : "payroll needs attendance review"}</h2><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold">{data.ready ? "DTR refreshed" : "Action needed"}</span></div>
    {error && <p role="alert" className="font-medium text-red-800">{error}</p>}
    {!data.ready && <p className="font-medium">Payroll was not recomputed by this check. Your existing run is unchanged.</p>}
    <div className="flex flex-wrap gap-2 text-sm"><span>{cases} employee cases</span><span>·</span><span>{data.counts.withheld ?? 0} punches withheld</span><span>·</span><span>{data.counts.boundaryReview ?? 0} boundary flags</span><span>·</span><span>{data.summariesOutdated ? "DTR summaries outdated" : "DTR freshness checked"}</span></div>
    {!compact && data.blockers.map((b, i) => <p key={i} className="text-sm leading-6">{b}</p>)}
    <p className="text-xs leading-5 text-slate-600">Flags can refer to the same records; counts are not added together. {data.syncedAt ? `Last completed sync: ${originalPunchDateTime(data.syncedAt)} (Philippine time).` : "No completed sync for this period."}</p>
    <div className="flex flex-wrap gap-2"><Link className={`${button} bg-blue-700 text-white`} href={base + "#attendance-review"}>View affected records</Link><Link className={button} href={base + "#reconcile-title"}>Sync and check again</Link></div>
  </section>;
}

function OriginalSequence({ person }: { person: ResolutionPerson }) {
  return <section className={box}><h3 className="font-semibold">Original attendance · Philippine time (UTC+8)</h3><p className="mt-1 text-sm text-slate-600">Capture date and time are shown for every record. Adjacent-day context and voided records remain visible.</p><ol className="mt-4 space-y-3">{person.records.map(p => <li key={p.eventId} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><strong>{p.type} · {originalPunchDateTime(p.capturedAt)}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{p.status === "VOID" ? "Voided · original retained" : person.relevantIds.includes(p.eventId) ? "Original capture" : "Adjacent-day context"}</span></div><p className="mt-1 text-sm">{p.employeeId} · {p.employeeName} · Branch {p.branchId}</p><p className="mt-1 text-xs text-slate-600">{p.clockFlag ? "Device clock warning. " : ""}{p.reviewResolved ? "Source flag acknowledged; paid hours still require review." : p.reviewFlags.join(" · ").replaceAll("_", " ") || "No source warning"}</p><details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer">Record details</summary><p className="mt-2 break-all">Record {p.eventId}</p><p>Uploaded {originalPunchDateTime(p.receivedAt)}</p></details></li>)}</ol></section>;
}

export function AttendanceReview({ data, refresh }: { data: AttendanceReadiness; refresh: () => void }) {
  const [tab, setTab] = useState<"review" | "coverage" | "history">("review");
  const [filter, setFilter] = useState("Needs review"), [page, setPage] = useState(0), [selected, setSelected] = useState<string | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [history, setHistory] = useState(data.history), [historyPage, setHistoryPage] = useState(0), [more, setMore] = useState(data.historyHasMore);
  const person = data.people.find(p => p.sourceId === selected);
  const people = data.people.filter(p => !p.contextOnly && (filter === "All people" || filter === "Test punches" && p.classification === "TestOnly" || filter === "Needs review" && p.issues.length || filter === "Pending approval" && p.resolution?.state === "Pending"));
  async function perform(fn: () => Promise<Result>) {
    setBusy(true); setMessage("");
    try { const result = await fn(); setMessage(result.ok ? result.data : result.error); if (result.ok) refresh(); }
    catch { setMessage("The request could not be confirmed. Your choices are retained. Refresh or sign in again, then check history before retrying."); }
    finally { setBusy(false); }
  }
  return <section id="attendance-review" className="scroll-mt-4 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Attendance review</h2><p className="mt-1 text-sm text-slate-600">{data.code} · {data.startDate}–{data.endDate}</p></div><nav aria-label="Attendance review views" className="flex flex-wrap gap-2">{([['review','Review records'],['coverage','Period coverage'],['history','Resolution history']] as const).map(([value, label]) => <button className={`${button} ${tab === value ? "bg-slate-900 text-white" : "bg-white"}`} aria-pressed={tab === value} key={value} onClick={() => setTab(value)}>{label}</button>)}</nav></div>
    {message && <div role="status" className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm leading-6">{message}</div>}
    {!data.periodOpen && <p className="rounded-lg bg-amber-50 p-4 text-sm">This period is closed or has posted payroll. Records are available for review; corrections require a linked payroll adjustment.</p>}
    {tab === "review" && <>
      <div className="flex flex-wrap gap-2">{["Needs review", "Test punches", "Pending approval", "All people"].map(label => <button key={label} aria-pressed={filter === label} className={`${button} ${filter === label ? "bg-blue-700 text-white" : "bg-white"}`} onClick={() => { setFilter(label); setPage(0); setSelected(null); }}>{label}</button>)}</div>
      {person ? <><button className={button} onClick={() => setSelected(null)}>← Back to cases</button><header className={box}><h3 className="text-lg font-semibold">{person.name} · Attendance ID {person.sourceId}</h3><p className="mt-2 text-sm">Integra: {person.employeeNo ? `${person.employeeNo} · ${person.employeeName}` : "Employee match needed"}</p><p className="mt-2 text-sm text-amber-800">{person.issues.join(" · ") || "No unresolved source warnings"}</p></header><OriginalSequence person={person} /><ResolutionForm key={`${person.sourceId}:${person.version}:${person.resolution?.state}`} person={person} data={data} busy={busy} perform={perform} /></> : <>
        <p className="text-sm text-slate-600">{people.length} employee cases. Select a case to see every original date, time and related warning.</p>
        <div className="grid gap-3 md:grid-cols-2">{people.slice(page * 20, page * 20 + 20).map(p => <article className={`${box} flex flex-col gap-3`} key={p.sourceId}><h3 className="font-semibold">{p.name} <span className="font-normal text-slate-600">· ID {p.sourceId}</span></h3><p className="text-sm">{p.employeeNo ? `Integra ${p.employeeNo} · ${p.employeeName}` : "Employee match needed"}</p><p className="text-xs text-slate-600">{p.records.filter(r => p.relevantIds.includes(r.eventId)).map(r => r.capturedAt.slice(0, 10)).length} period / overnight records</p><p className="text-sm leading-6 text-amber-800">{p.issues.join(" · ") || "No outstanding source warnings"}</p><button className={`${button} mt-auto self-start`} onClick={() => setSelected(p.sourceId)}>View dates and review</button></article>)}</div>
        {!people.length && <p className={box}>No cases in this view. Sync and check DTR freshness before returning to payroll.</p>}
        <div className="flex items-center gap-3"><button className={button} disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span className="text-sm">Page {page + 1} of {Math.max(1, Math.ceil(people.length / 20))}</span><button className={button} disabled={(page + 1) * 20 >= people.length} onClick={() => setPage(page + 1)}>Next</button></div>
      </>}
    </>}
    {tab === "coverage" && <div className={box}><h3 className="font-semibold">Which work belongs to {data.code}?</h3><p className="mt-2 text-sm leading-6">An adjacent-day record alone does not block this period. An IN/OUT pair that crosses a period boundary stays available for DTR. This is calculated from the records; there is no manual dismiss button.</p>{data.people.filter(p => p.records.some(r => !p.relevantIds.includes(r.eventId))).map(p => <div key={p.sourceId} className="mt-4 border-t pt-4"><strong>{p.employeeNo ?? p.sourceId} · {p.name}</strong><p className="mt-1 text-sm font-medium text-emerald-800">{p.contextOnly ? "Context only — not a blocker for this period" : "Period records and neighboring context"}</p>{p.records.map(r => <p className="mt-2 text-sm" key={r.eventId}>{r.type} · {originalPunchDateTime(r.capturedAt)} · {p.relevantIds.includes(r.eventId) ? "Relevant period / overnight record" : "Adjacent-day context"}</p>)}</div>)}{!data.people.some(p => p.records.some(r => !p.relevantIds.includes(r.eventId))) && <p className="mt-4 text-sm">No context-only records in this snapshot.</p>}</div>}
    {tab === "history" && <div className="space-y-3"><p className="text-sm leading-6">Reversing an approved manual decision reopens review and makes DTR/payroll stale. To reverse a source VOID, open the person under All people, select the original record and propose Restore. Source changes affect every period using that record.</p>{[...new Map([...history, ...data.history].map(h => [h.id, h])).values()].map(h => <article className={box} key={h.id}><div className="flex flex-wrap justify-between gap-2"><strong>ID {h.sourceId} · {h.kind === "Manual" ? "Manual DTR review" : h.kind === "NoAttendance" ? "No period attendance" : h.kind === "SourceVoid" ? "Void source records" : "Restore source records"}</strong><span>{h.state}</span></div><p className="mt-2 text-sm">{originalPunchDateTime(h.createdAt)} · Proposed by {h.actor}</p><p className="mt-1 text-sm">Reason: {h.reason}</p><p className="mt-1 text-sm">Evidence: {h.evidence}</p>{h.manualPunches.map((p, i) => <p className="mt-1 text-sm" key={i}>Manual {p.type} · {p.localDateTime.replace("T", " ")} (Philippine time)</p>)}{h.reviewer && <p className="mt-2 text-xs text-slate-600">Reviewer {h.reviewer} · Updated {originalPunchDateTime(h.updatedAt)}</p>}{h.result && <p className="mt-2 text-sm">{h.result}</p>}<button className={`${button} mt-3`} onClick={() => { setSelected(h.sourceId); setTab("review"); }}>Open employee records</button>{["Sending", "Failed"].includes(h.state) && <button disabled={busy || !data.periodOpen} className={`${button} ml-2 mt-3`} onClick={() => perform(() => retryAttendanceSourceCorrectionAction(h.id))}>Retry source delivery</button>}</article>)}{more && <button disabled={busy} className={button} onClick={async () => { setBusy(true); try { const r = await attendanceReadinessAction(data.periodId, historyPage + 1); if (r.ok) { setHistory(h => [...h, ...r.data.history]); setMore(r.data.historyHasMore); setHistoryPage(historyPage + 1); } else setMessage(r.error); } finally { setBusy(false); } }}>Load older history</button>}</div>}
  </section>;
}

function ResolutionForm({ person, data, busy, perform }: { person: ResolutionPerson; data: AttendanceReadiness; busy: boolean; perform: (fn: () => Promise<Result>) => void }) {
  const [kind, setKind] = useState<ResolutionKind>(person.classification === "TestOnly" ? "SourceVoid" : "Manual");
  const [manual, setManual] = useState<ManualPunch[]>([]), [eventIds, setEventIds] = useState<string[]>([]);
  const [reason, setReason] = useState(""), [evidence, setEvidence] = useState(""), [confirmed, setConfirmed] = useState(false), [reviewReason, setReviewReason] = useState("");
  const decision = person.resolution, active = decision && ["Pending", "Approved", "Sending", "Failed"].includes(decision.state);
  const disabled = busy || !data.periodOpen;
  if (active) return <section className={`${box} space-y-4`}><h3 className="font-semibold">{decision.state === "Pending" ? "Review proposed treatment" : `Treatment: ${decision.state}`}</h3><p className="text-sm">{decision.kind} · {decision.reason}</p><p className="text-sm">Evidence: {decision.evidence}</p>{decision.eventIds.map(id => { const p = person.records.find(r => r.eventId === id); return <p className="rounded-lg border border-amber-300 p-3 text-sm" key={id}><strong>Selected for {decision.kind === "SourceVoid" ? "VOID" : "RESTORE"}</strong> - {p ? `${p.type} - ${originalPunchDateTime(p.capturedAt)}` : "Record changed"}<span className="mt-1 block break-all text-xs">{id}</span></p>; })}{decision.manualPunches.map((p, i) => <p key={i} className="rounded-lg bg-blue-50 p-3 text-sm"><strong>Manual DTR {p.type}</strong> · {p.localDateTime.replace("T", " ")} · Philippine time. This is not an original capture.</p>)}<p className="text-sm leading-6">Approve only after checking the original dates and evidence above. Source void/restore changes every use of the selected records. Sync each affected period after confirmation; approval does not compute or approve payroll.</p><label className="block text-sm font-medium">Review / reversal reason<textarea className={input} maxLength={500} value={reviewReason} onChange={e => setReviewReason(e.target.value)} /></label><div className="flex flex-wrap gap-2">{decision.state === "Pending" && <><button disabled={disabled || reviewReason.trim().length < 3} className={`${button} bg-blue-700 text-white`} onClick={() => perform(() => reviewAttendanceResolutionAction(decision.id, "Approve", reviewReason))}>Approve treatment</button><button disabled={disabled || reviewReason.trim().length < 3} className={button} onClick={() => perform(() => reviewAttendanceResolutionAction(decision.id, "Reject", reviewReason))}>Reject proposal</button></>}{decision.state === "Approved" && <button disabled={disabled || reviewReason.trim().length < 3} className={button} onClick={() => perform(() => reviewAttendanceResolutionAction(decision.id, "Reverse", reviewReason))}>Reverse and reopen review</button>}{decision.state === "Failed" && <button disabled={disabled || reviewReason.trim().length < 3} className={button} onClick={() => perform(() => reviewAttendanceResolutionAction(decision.id, "Reject", reviewReason))}>Stop retrying; retain confirmed source changes</button>}{["Sending", "Failed"].includes(decision.state) && <button disabled={disabled} className={button} onClick={() => perform(() => retryAttendanceSourceCorrectionAction(decision.id))}>Retry source delivery</button>}</div><a className="inline-block text-sm text-blue-700 underline" href="#reconcile-title">Continue to Attendance & sync</a></section>;
  return <section className={`${box} space-y-4`}><h3 className="font-semibold">Propose a treatment</h3>{decision?.state === "Expired" && <p className="rounded-lg bg-amber-50 p-3 text-sm">The earlier evidence changed. This requires a fresh review; the old approval cannot authorize the new records.</p>}
    <label className="block text-sm font-medium">What needs to be resolved?<select className={input} value={kind} disabled={disabled} onChange={e => { setKind(e.target.value as ResolutionKind); setManual([]); setEventIds([]); setConfirmed(false); }}><option value="Manual">Review sequence / add verified missing IN or OUT</option><option value="SourceVoid">Void specific duplicate or test punches</option><option value="SourceRestore">Restore a previously voided original punch</option><option value="NoAttendance">Confirm no usable attendance for this period</option></select></label>
    {kind === "Manual" ? <><p className="text-sm leading-6">Ask the branch to upload an existing original record first. If a punch was never captured, add only a verified time supported by evidence. A schedule is not proof. Unknown time stays unresolved. Resolve actual duplicates before approving this sequence.</p>{manual.map((p, i) => <div key={i} className="grid min-w-0 gap-2 rounded-lg border p-3 sm:grid-cols-[90px_1fr_auto]"><label className="text-sm">Direction<select className={input} value={p.type} onChange={e => { const value = e.currentTarget.value as "IN" | "OUT"; setManual(v => v.map((r, n) => n === i ? { ...r, type: value } : r)); setConfirmed(false); }}><option>IN</option><option>OUT</option></select></label><label className="min-w-0 text-sm">Verified date and time · Philippine time<input className={input} type="datetime-local" value={p.localDateTime} onInput={e => { const value = e.currentTarget.value; setManual(v => v.map((r, n) => n === i ? { ...r, localDateTime: value } : r)); setConfirmed(false); }} /></label><button className={`${button} self-end`} onClick={() => { setManual(v => v.filter((_, n) => i !== n)); setConfirmed(false); }}>Remove</button></div>)}<button disabled={disabled || manual.length >= 62} className={button} onClick={() => { setManual(v => [...v, { type: "OUT", localDateTime: "" }]); setConfirmed(false); }}>+ Add verified missing IN / OUT</button><p className="text-xs text-slate-600">Keep this empty only if the entire original sequence is complete and supported by the review evidence.</p></> : kind === "NoAttendance" ? <p className="text-sm leading-6">Use only when every period punch was voided and you verified that no source attendance remains. This does not grant paid leave or waive DTR/payroll rules. Review the resulting absence/leave treatment in DTR.</p> : <><p className="text-sm leading-6">Select only the records verified as practice/duplicates, or the voided record to restore. Original evidence is retained. This correction applies at the source and affects every period using the event; closed/posted payroll requires a separate adjustment.</p>{!data.sourceCorrectionsEnabled && <p className="text-sm text-amber-800">Source corrections are awaiting connection configuration.</p>}{person.records.filter(p => person.relevantIds.includes(p.eventId) && p.status === (kind === "SourceVoid" ? "VALID" : "VOID")).map(p => <label className="flex items-start gap-3 rounded-lg border p-3 text-sm" key={p.eventId}><input type="checkbox" className="mt-1 h-5 w-5 shrink-0" checked={eventIds.includes(p.eventId)} onChange={e => { setEventIds(v => e.target.checked ? [...v, p.eventId] : v.filter(id => id !== p.eventId)); setConfirmed(false); }} /><span><strong>{p.type} · {originalPunchDateTime(p.capturedAt)}</strong><span className="mt-1 block break-all text-xs text-slate-500">{p.eventId} · {p.branchId}</span></span></label>)}</>}
    <label className="block text-sm font-medium">Verification evidence / reference<textarea className={input} placeholder="For example: supervisor confirmation and incident or upload reference" value={evidence} maxLength={500} onChange={e => { setEvidence(e.target.value); setConfirmed(false); }} /></label><label className="block text-sm font-medium">Reason for this treatment<textarea className={input} maxLength={500} value={reason} onChange={e => { setReason(e.target.value); setConfirmed(false); }} /></label><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span>I checked the original capture dates, the selected records/times and the evidence. This proposal needs approval before it affects attendance.</span></label><button className={`${button} bg-blue-700 text-white`} disabled={disabled || !confirmed || reason.trim().length < 3 || evidence.trim().length < 3 || kind.startsWith("Source") && (!eventIds.length || !data.sourceCorrectionsEnabled)} onClick={() => perform(() => proposeAttendanceResolutionAction({ periodId: data.periodId, sourceId: person.sourceId, version: person.version, kind, reason, evidence, confirmed, manualPunches: manual, eventIds }))}>Save proposal for review</button><p className="text-xs text-slate-600">If the correct time is unknown, leave the case open and obtain evidence. Nothing is invented or automatically approved.</p>
  </section>;
}
