"use client";

import { useState } from "react";
import Link from "next/link";
import { originalPunchDateTime, type AttendanceReadiness, type ResolutionPerson } from "@/lib/payroll/attendanceResolutionModel";
import { workDate } from "@/lib/payroll/attendanceWorkbenchModel";
import { attendancePeriodUrl } from "@/lib/payroll/attendanceSourcePeriods";
import { attendanceReadinessAction } from "@/app/actions/attendanceSourceAction";

const button = "min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50";
const box = "rounded-xl border border-slate-200 bg-white p-4 sm:p-5";

export function AttendanceReadinessCard({ data, error, compact = false }: { data: AttendanceReadiness; error?: string | null; compact?: boolean }) {
  const base = attendancePeriodUrl("/payroll/attendance-source", Number(data.startDate.slice(0, 4)), data.periodId);
  const cases = data.people.filter(p => p.issues.length && !p.contextOnly).length;
  return <section aria-label="Payroll attendance readiness" className={`${box} space-y-3 ${data.ready && !error ? "border-emerald-300" : "border-amber-300 bg-amber-50"}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><h2 className="text-lg font-semibold">{data.code} {data.ready && !error ? "attendance is ready for payroll review" : "payroll needs attendance review"}</h2><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold">{data.ready ? "DTR refreshed" : "Action needed"}</span></div>
    {error && <p role="alert" className="font-medium text-red-800">{error}</p>}
    {!data.ready && <p className="font-medium">Payroll was not recomputed by this check. Your existing run is unchanged.</p>}
    <div className="flex flex-wrap gap-2 text-sm"><span>{cases} employee cases</span><span>·</span><span>{data.counts.withheld ?? 0} punches withheld</span><span>·</span><span>{data.counts.boundaryReview ?? 0} boundary flags</span><span>·</span><span>{data.summariesOutdated ? "DTR summaries outdated" : "DTR freshness checked"}</span></div>
    {!compact && data.blockers.map((b, i) => <p key={i} className="text-sm leading-6">{b}</p>)}
    <p className="text-xs leading-5 text-slate-600">Flags can refer to the same records; counts are not added together. {data.syncedAt ? `Last sync attempt: ${data.runState??"Unknown"} · ${originalPunchDateTime(data.syncedAt)} (Philippine time).` : "No completed sync attempt for this period."}</p>
    <div className="flex flex-wrap gap-2"><Link className={`${button} bg-blue-700 text-white`} href={base + "#attendance-review"}>View affected records</Link><Link className={button} href={base + "#reconcile-title"}>Sync and check again</Link></div>
  </section>;
}

function OriginalSequence({ person }: { person: ResolutionPerson }) {
  return <section className={box}><h3 className="font-semibold">Original attendance · Philippine time (UTC+8)</h3><p className="mt-1 text-sm text-slate-600">Capture date and time are shown for every record. Adjacent-day context and voided records remain visible.</p><ol className="mt-4 space-y-3">{person.records.map(p => <li key={p.eventId} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><strong>{p.type} · {originalPunchDateTime(p.capturedAt)}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{p.status === "VOID" ? "Voided · original retained" : person.relevantIds.includes(p.eventId) ? "Original capture" : "Adjacent-day context"}</span></div><p className="mt-1 text-sm">{p.employeeId} · {p.employeeName} · Branch {p.branchId}</p><p className="mt-1 text-xs text-slate-600">{p.clockFlag ? "Device clock warning. " : ""}{p.reviewResolved ? "Source flag acknowledged; paid hours still require review." : p.reviewFlags.join(" · ").replaceAll("_", " ") || "No source warning"}</p><details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer">Record details</summary><p className="mt-2 break-all">Record {p.eventId}</p><p>Uploaded {originalPunchDateTime(p.receivedAt)}</p></details></li>)}</ol></section>;
}

export function AttendanceReview({ data, anchorId = "attendance-review" }: { data: AttendanceReadiness; refresh: () => void; anchorId?: string }) {
  const [tab, setTab] = useState<"review" | "coverage" | "history">("review");
  const [filter, setFilter] = useState("Needs review"), [page, setPage] = useState(0), [selected, setSelected] = useState<string | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [history, setHistory] = useState(data.history), [historyPage, setHistoryPage] = useState(0), [more, setMore] = useState(data.historyHasMore);
  const person = data.people.find(p => p.sourceId === selected);
  const people = data.people.filter(p => !p.contextOnly && (filter === "All people" || filter === "Test punches" && p.classification === "TestOnly" || filter === "Needs review" && p.issues.length || filter === "Pending approval" && p.resolution?.state === "Pending"));
  return <section id={anchorId} className="scroll-mt-4 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Attendance review</h2><p className="mt-1 text-sm text-slate-600">{data.code} · {data.startDate}–{data.endDate}</p></div><nav aria-label="Attendance review views" className="flex flex-wrap gap-2">{([['review','Review records'],['coverage','Period coverage'],['history','Resolution history']] as const).map(([value, label]) => <button className={`${button} ${tab === value ? "bg-slate-900 text-white" : "bg-white"}`} aria-pressed={tab === value} key={value} onClick={() => setTab(value)}>{label}</button>)}</nav></div>
    {message && <div role="status" className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm leading-6">{message}</div>}
    {!data.periodOpen && <p className="rounded-lg bg-amber-50 p-4 text-sm">This period is closed or has posted payroll. Records are available for review; corrections require a linked payroll adjustment.</p>}
    {tab === "review" && <>
      <div className="flex flex-wrap gap-2">{["Needs review", "Test punches", "Pending approval", "All people"].map(label => <button key={label} aria-pressed={filter === label} className={`${button} ${filter === label ? "bg-blue-700 text-white" : "bg-white"}`} onClick={() => { setFilter(label); setPage(0); setSelected(null); }}>{label}</button>)}</div>
      {person ? <><button className={button} onClick={() => setSelected(null)}>← Back to cases</button><header className={box}><h3 className="text-lg font-semibold">{person.name} · Attendance ID {person.sourceId}</h3><p className="mt-2 text-sm">Integra: {person.employeeNo ? `${person.employeeNo} · ${person.employeeName}` : "Employee match needed"}</p><p className="mt-2 text-sm text-amber-800">{person.issues.join(" · ") || "No unresolved source warnings"}</p></header><OriginalSequence person={person} /><ResolutionForm key={`${person.sourceId}:${person.version}:${person.resolution?.state}`} person={person} data={data} /></> : <>
        <p className="text-sm text-slate-600">{people.length} employee cases. Select a case to see every original date, time and related warning.</p>
        <div className="grid gap-3 md:grid-cols-2">{people.slice(page * 20, page * 20 + 20).map(p => <article className={`${box} flex flex-col gap-3`} key={p.sourceId}><h3 className="font-semibold">{p.name} <span className="font-normal text-slate-600">· ID {p.sourceId}</span></h3><p className="text-sm">{p.employeeNo ? `Integra ${p.employeeNo} · ${p.employeeName}` : "Employee match needed"}</p><p className="text-xs text-slate-600">{p.records.filter(r => p.relevantIds.includes(r.eventId)).map(r => r.capturedAt.slice(0, 10)).length} period / overnight records</p><p className="text-sm leading-6 text-amber-800">{p.issues.join(" · ") || "No outstanding source warnings"}</p><button className={`${button} mt-auto self-start`} onClick={() => setSelected(p.sourceId)}>View dates and review</button></article>)}</div>
        {!people.length && <p className={box}>No cases in this view. Sync and check DTR freshness before returning to payroll.</p>}
        <div className="flex items-center gap-3"><button className={button} disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span className="text-sm">Page {page + 1} of {Math.max(1, Math.ceil(people.length / 20))}</span><button className={button} disabled={(page + 1) * 20 >= people.length} onClick={() => setPage(page + 1)}>Next</button></div>
      </>}
    </>}
    {tab === "coverage" && <div className={box}><h3 className="font-semibold">Which work belongs to {data.code}?</h3><p className="mt-2 text-sm leading-6">An adjacent-day record alone does not block this period. An IN/OUT pair that crosses a period boundary stays available for DTR. This is calculated from the records; there is no manual dismiss button.</p>{data.people.filter(p => p.records.some(r => !p.relevantIds.includes(r.eventId))).map(p => <div key={p.sourceId} className="mt-4 border-t pt-4"><strong>{p.employeeNo ?? p.sourceId} · {p.name}</strong><p className="mt-1 text-sm font-medium text-emerald-800">{p.contextOnly ? "Context only — not a blocker for this period" : "Period records and neighboring context"}</p>{p.records.map(r => <p className="mt-2 text-sm" key={r.eventId}>{r.type} · {originalPunchDateTime(r.capturedAt)} · {p.relevantIds.includes(r.eventId) ? "Relevant period / overnight record" : "Adjacent-day context"}</p>)}</div>)}{!data.people.some(p => p.records.some(r => !p.relevantIds.includes(r.eventId))) && <p className="mt-4 text-sm">No context-only records in this snapshot.</p>}</div>}
    {tab === "history" && <div className="space-y-3"><p className="text-sm leading-6">Historical approvals and original captures are retained here. New corrections are reviewed in the current attendance workspace and saved only in Integra; phone attendance is unchanged.</p>{[...new Map([...history, ...data.history].map(h => [h.id, h])).values()].map(h => <article className={box} key={h.id}><div className="flex flex-wrap justify-between gap-2"><strong>ID {h.sourceId} · {h.kind === "Manual" ? "Manual DTR review" : h.kind === "NoAttendance" ? "No period attendance" : h.kind === "SourceVoid" ? "Void source records" : "Restore source records"}</strong><span>{h.state}</span></div><p className="mt-2 text-sm">{originalPunchDateTime(h.createdAt)} · Proposed by {h.actor}</p><p className="mt-1 text-sm">Reason: {h.reason}</p><p className="mt-1 text-sm">Evidence: {h.evidence}</p>{h.manualPunches.map((p, i) => <p className="mt-1 text-sm" key={i}>Manual {p.type} · {p.localDateTime.replace("T", " ")} (Philippine time)</p>)}{h.reviewer && <p className="mt-2 text-xs text-slate-600">Reviewer {h.reviewer} · Updated {originalPunchDateTime(h.updatedAt)}</p>}{h.result && <p className="mt-2 text-sm">{h.result}</p>}<button className={`${button} mt-3`} onClick={() => { setSelected(h.sourceId); setTab("review"); }}>Open employee records</button></article>)}{more && <button disabled={busy} className={button} onClick={async () => { setBusy(true); try { const r = await attendanceReadinessAction(data.periodId, historyPage + 1); if (r.ok) { setHistory(h => [...h, ...r.data.history]); setMore(r.data.historyHasMore); setHistoryPage(historyPage + 1); } else setMessage(r.error); } finally { setBusy(false); } }}>Load older history</button>}</div>}
  </section>;
}

function ResolutionForm({ person, data }: { person: ResolutionPerson; data: AttendanceReadiness }) {
 const first=person.records.find(record=>person.relevantIds.includes(record.eventId)&&workDate(record.capturedAt)>=data.startDate&&workDate(record.capturedAt)<=data.endDate);
 const day=first?workDate(first.capturedAt):data.startDate;
 const base=attendancePeriodUrl("/payroll/attendance-source",Number(data.startDate.slice(0,4)),data.periodId);
 const href=person.employeeId?`${base}&employeeId=${encodeURIComponent(person.employeeId)}&day=${day}#attendance-review`:`${base}#attendance-review`;
 return <section className={`${box} space-y-3`}><h3 className="font-semibold">Correct payroll attendance in Integra</h3><p className="text-sm">Open this employee’s day, enter the actual correction, review it, then confirm. Notes are optional. Original captures and historical notes are retained; phone attendance is read-only.</p>{person.resolution&&<details><summary className="min-h-11 cursor-pointer text-sm">Earlier proposal · {person.resolution.state}</summary><p className="text-sm">{person.resolution.kind} · {person.resolution.reason||"No note"}</p>{person.resolution.evidence&&<p className="text-sm">Saved evidence: {person.resolution.evidence}</p>}{person.resolution.manualPunches.map((p,index)=><p key={index} className="text-sm">Proposed {p.type} · {p.localDateTime.replace("T"," ")} Philippine time</p>)}</details>}<Link href={href} className={`${button} inline-flex items-center bg-blue-700 text-white`}>{person.employeeId?"Open employee attendance review":"Open attendance review and match employee"}</Link></section>;
}
