"use client";
import { useEffect, useRef, useState } from "react";
import { attendanceScheduleOptionsAction } from "@/app/actions/attendanceWorkbenchAction";
import { previewBulkDaySchedulesAction, saveBulkDaySchedulesAction, getBulkDayScheduleResultAction } from "@/app/actions/shiftAssignmentAction";
import { generateUUID } from "@/lib/uuid";
import { dayTargetKey, type DayTarget } from "@/lib/payroll/attendanceStage6Model";
import { workDate, type WorkBoard } from "@/lib/payroll/attendanceWorkbenchModel";
import { originalPunchDateTime } from "@/lib/payroll/attendanceResolutionModel";

const button="min-h-11 rounded border px-3 py-2 text-sm font-semibold disabled:opacity-50";
type Preview=Awaited<ReturnType<typeof previewBulkDaySchedulesAction>>;
export function BulkDays({board,onNoWork,onSaved}:{board:WorkBoard;onNoWork:(targets:DayTarget[],note:string)=>Promise<void>;onSaved:()=>Promise<void>}) {
 const [selected,setSelected]=useState<DayTarget[]>([]),[search,setSearch]=useState(""),[empty,setEmpty]=useState(false),[limit,setLimit]=useState(50);
 const [note,setNote]=useState(""),[shift,setShift]=useState(""),[options,setOptions]=useState<Awaited<ReturnType<typeof attendanceScheduleOptionsAction>>>([]);
 const [preview,setPreview]=useState<Preview|null>(null),[requestId,setRequestId]=useState(generateUUID),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[uncertain,setUncertain]=useState(false),[hydrated,setHydrated]=useState(false);
 const errorRef=useRef<HTMLParagraphElement>(null),pending=useRef(false),storage=`integra-bulk-days:${board.period.id}`;
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storage)??'null');if(saved){setSelected(saved.selected??[]);setNote(saved.note??'');setShift(saved.shift??'');setRequestId(saved.requestId??generateUUID());setUncertain(!!saved.pending);}}catch{}setHydrated(true);void attendanceScheduleOptionsAction().then(setOptions).catch(()=>setError("Schedules could not load. Reopen Bulk days to retry."));},[storage]);
 useEffect(()=>{if(hydrated)try{sessionStorage.setItem(storage,JSON.stringify({selected,note,shift,requestId,pending:uncertain}));}catch{}},[storage,hydrated,selected,note,shift,requestId,uncertain]);
 useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 const rows=board.employees.filter(e=>`${e.name} ${e.no}`.toLowerCase().includes(search.toLowerCase())).flatMap(e=>e.days.filter(d=>empty||d.records.length>0).map(d=>({employee:e,context:d,employeeId:e.id,day:d.day})));
 const chosen=selected.map(t=>({target:t,employee:board.employees.find(e=>e.id===t.employeeId)})).map(t=>({...t,context:t.employee?.days.find(d=>d.day===t.target.day)}));
 function editSelection(next:DayTarget[]){setSelected(next);setPreview(null);setRequestId(generateUUID());setMessage("");setError("");}
 async function act(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError("");try{await fn();}catch(cause){setError(cause instanceof Error?cause.message:"Could not complete this action. Selections are retained.");}finally{setBusy(false);pending.current=false;}}
 async function checkStatus(){const result=await getBulkDayScheduleResultAction(requestId);if(result){setUncertain(false);setPreview(null);setMessage(`${result.saved} date schedules saved. This receipt was recovered from history.`);await onSaved();return true;}setError("No saved receipt yet. You may review and retry this same request safely; a completed request will not be applied twice.");return false;}
 const input={requestId,periodId:board.period.id,targets:selected,shiftTableId:Number(shift)};
 return <section aria-label="Bulk employee days" className="min-w-0 space-y-3 rounded border bg-white p-3">
  <h3 className="font-bold">Selected employee days</h3><p className="text-sm">Choose up to 100 dates across 20 employees to confirm schedules or review test/no-work captures. Ordinary days without attendance need no action.</p>
  <label className="block text-sm">Find employees<input className="block min-h-11 w-full min-w-0 rounded border p-2" value={search} onChange={e=>{setSearch(e.target.value);setLimit(50);}}/></label>
  <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={empty} onChange={e=>{setEmpty(e.target.checked);setLimit(50);}}/>Include days without records</label>
  <div className="flex flex-wrap gap-2"><button className={button} disabled={busy||uncertain} onClick={()=>editSelection([...new Map([...selected,...rows.map(({employeeId,day})=>({employeeId,day}))].map(t=>[dayTargetKey(t),t])).values()])}>Select all {rows.length} matching dates</button><button className={button} disabled={busy||uncertain||!selected.length} onClick={()=>editSelection([])}>Clear selection</button></div>
  <div className="max-h-80 overflow-y-auto rounded border">{rows.slice(0,limit).map(row=><label key={dayTargetKey(row)} className="flex min-h-11 items-start gap-2 border-b p-2 text-sm"><input className="mt-1" type="checkbox" disabled={busy||uncertain} checked={selected.some(t=>dayTargetKey(t)===dayTargetKey(row))} onChange={e=>editSelection(e.target.checked?[...selected,{employeeId:row.employeeId,day:row.day}]:selected.filter(t=>dayTargetKey(t)!==dayTargetKey(row)))}/><span><strong>{row.employee.name}</strong> · {row.employee.no}<br/>{row.day} · {row.context.records.filter(r=>r.status==='VALID'&&!r.excluded).length} effective captures · {row.context.schedule?'Scheduled':'No schedule'}</span></label>)}{rows.length>limit&&<button className={button} onClick={()=>setLimit(n=>n+50)}>Show 50 more dates</button>}</div>
  <p role="status" className="font-semibold">{selected.length} dates selected across {new Set(selected.map(t=>t.employeeId)).size} employees. Filters do not change this selection.</p>
  <details><summary className="min-h-11 cursor-pointer py-2">Review exact selected dates and captures</summary>{chosen.map(({target,employee,context})=><div key={dayTargetKey(target)} className="border-t py-2 text-sm"><strong>{employee?.name??'Employee unavailable'} · {target.day}</strong>{context?.records.filter(r=>r.status==='VALID'&&!r.excluded).map(r=><p key={r.id}>{r.type} · {originalPunchDateTime(r.at)}{workDate(r.at)!==target.day?' · Check adjacent-date context':''}</p>)}</div>)}</details>
  {board.period.posted&&<p className="text-sm text-amber-900">This period has posted payroll. Schedule changes are protected; attendance decisions use the existing reviewed adjustment path.</p>}
  <label className="block text-sm">Schedule for selected dates<select className="block min-h-11 w-full min-w-0 rounded border p-2" value={shift} disabled={busy||uncertain} onChange={e=>{setShift(e.target.value);setPreview(null);setRequestId(generateUUID());}}><option value="">Select schedule</option>{options.map(o=><option key={o.id} value={o.id}>{o.code} · {o.start}–{o.end} · {o.name}</option>)}</select></label>
  <button className={button} disabled={busy||uncertain||!selected.length||!shift||board.period.posted} onClick={()=>void act(async()=>{setPreview(await previewBulkDaySchedulesAction(input));setMessage("");})}>Review selected schedules</button>
  {preview&&<div className="space-y-2 rounded border-2 border-blue-600 p-3 text-sm"><strong>{preview.rows.length} dates → {preview.shiftLabel}</strong><ul>{preview.rows.map(r=><li key={dayTargetKey(r)}>{r.name} · {r.day} · {r.existing?.shiftCode??'No date override'} → {preview.shiftLabel}</li>)}</ul><button className={button+" bg-blue-700 text-white"} disabled={busy||uncertain} onClick={()=>void act(async()=>{setUncertain(true);try{const result=await saveBulkDaySchedulesAction(input,preview.digest);setUncertain(false);setPreview(null);if(!result.ok){setError(result.error);return;}const saved=result.data;setMessage(`${saved.saved} date schedules saved. DTR summaries updated: ${saved.rebuiltSummaryCount}.`);await onSaved();}catch(cause){if(!await checkStatus())throw cause;}})}>Confirm all {preview.rows.length} date schedules</button></div>}
  <label className="block text-sm">No-work reason and evidence<input className="block min-h-11 w-full min-w-0 rounded border p-2" value={note} disabled={busy||uncertain} placeholder="approved" onChange={e=>setNote(e.target.value)}/></label><p className="text-xs">Review no work confirms this note for the selected dates. It stages exact capture exclusions and a no-work decision for final approval; original captures remain in history.</p>
  <button className={button} disabled={busy||uncertain||!selected.length||note.trim().length<3} onClick={()=>void act(()=>onNoWork(selected,note))}>Review selected dates as no work</button>
  {busy&&<p role="status">Working on the selected dates… Inputs are retained.</p>}{message&&<p role="status" className="rounded border border-green-600 p-2">{message}</p>}{error&&<p ref={errorRef} tabIndex={-1} role="alert" className="rounded border border-red-500 p-2 text-sm">{error}</p>}
  {uncertain&&<div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void act(async()=>{await checkStatus();})}>Check schedule save status</button><button className={button} disabled={busy} onClick={()=>void act(async()=>{if(!await checkStatus()){setPreview(await previewBulkDaySchedulesAction(input));setUncertain(false);setError("");}})}>Review same request before retry</button></div>}
 </section>;
}
