"use client";
import Link from "next/link";
import { originalPunchDateTime } from "@/lib/payroll/attendanceResolutionModel";
import { workDate } from "@/lib/payroll/attendanceWorkbenchModel";
import type { DuplicateBoard } from "@/lib/payroll/attendanceDuplicateModel";

const button="inline-flex min-h-11 items-center rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold";
export function DuplicateReview({periodId,initial:board}:{periodId:string;initial:DuplicateBoard;refresh:()=>void}) {
 const review=(sourceId:string,at:string)=>`/payroll/attendance-source?year=${workDate(at).slice(0,4)}&periodId=${encodeURIComponent(periodId)}&sourceId=${encodeURIComponent(sourceId)}&day=${workDate(at)}#attendance-review`;
 return <section id="obvious-duplicates" aria-label="Obvious duplicates" className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-5">
  <h2 className="text-lg font-semibold">Duplicate suggestions</h2><p className="text-sm">Review repeated INs or OUTs in the employee’s attendance view. Corrections are saved only in Integra; phone attendance is read-only. Automatic source changes and source-delivery retries are retired.</p>
  <h3 className="font-semibold">Suggested · {board.candidates.length} groups</h3>
  {!board.candidates.length&&<p className="text-sm">No duplicate suggestions for this period. Historical corrections remain below.</p>}
  {board.candidates.map(c=><article key={c.id} className="min-w-0 space-y-2 rounded-lg border p-3"><h4 className="font-semibold">{c.name} · Attendance ID {c.sourceId}</h4><p className="text-sm">First capture: {c.kept.type} · {originalPunchDateTime(c.kept.capturedAt)}</p>{c.removed.map(p=><p key={p.eventId} className="text-sm">Repeated capture: {p.type} · {originalPunchDateTime(p.capturedAt)}</p>)}<p className="text-xs text-slate-600">{c.gapSeconds.toFixed(1)} seconds from the first capture · Branch {c.kept.branchId}</p><ul className="text-xs text-amber-900">{c.warnings.map(w=><li key={w}>{w}</li>)}</ul><Link className={button} href={review(c.sourceId,c.kept.capturedAt)}>Review employee’s duplicate punches</Link><details className="text-xs"><summary className="min-h-8 cursor-pointer">Original capture references</summary>{[c.kept,...c.removed].map(p=><p className="break-all py-1" key={p.eventId}>{originalPunchDateTime(p.capturedAt)} · {p.type} · Record {p.eventId}</p>)}</details></article>)}
  <h3 className="font-semibold">Historical duplicate corrections</h3><p className="text-xs text-slate-600">Prior source changes remain recorded. New corrections or reversals are reviewed as Integra overrides and do not alter the phone database.</p>
  {!board.history.length&&<p className="text-sm">No earlier duplicate corrections for this period.</p>}
  {board.history.map(h=><article key={h.id} className="space-y-2 rounded-lg border p-3 text-sm"><p className="font-semibold">{h.restored?"Previously restored":h.automatic?"Previously automatic":"Previously administrator approved"} · {h.state} · {h.kept.employeeName}</p><p>Kept {h.kept.type} · {originalPunchDateTime(h.kept.capturedAt)}</p><p>{h.removed.length} records · {originalPunchDateTime(h.createdAt)}</p><p>{h.reason}</p>{h.result&&<p className="text-xs">{h.result}</p>}<details className="text-xs"><summary className="min-h-8 cursor-pointer">Correction audit details</summary><p className="break-all">Rule: {h.ruleVersion} · Approved by: {h.actor} · Source group: {h.groupId}</p>{[h.kept,...h.removed].map(p=><p className="break-all py-1" key={p.eventId}>{p.eventId===h.kept.eventId?"Kept":"Selected repeat"}: {p.type} · {originalPunchDateTime(p.capturedAt)} · Record {p.eventId} · Prior version {p.correctionVersion??"unknown"}</p>)}</details><Link className={button} href={review(h.kept.employeeId,h.kept.capturedAt)}>Review current attendance</Link></article>)}
 </section>;
}
