"use client";
import { useState } from "react";
import { duplicateBoardAction, duplicatePolicyAction, approveDuplicateBatchAction, undoDuplicateAction } from "@/app/actions/attendanceDuplicateAction";
import { retryAttendanceSourceCorrectionAction } from "@/app/actions/attendanceSourceAction";
import { originalPunchDateTime } from "@/lib/payroll/attendanceResolutionModel";
import type { DuplicateBoard, DuplicateMode } from "@/lib/payroll/attendanceDuplicateModel";

const button="min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed";
const field="block w-full min-w-0 rounded-lg border border-slate-300 bg-white p-3 text-sm";
export function DuplicateReview({periodId,initial,refresh}:{periodId:string;initial:DuplicateBoard;refresh:()=>void}) {
 const [board,setBoard]=useState(initial),[mode,setMode]=useState<DuplicateMode>(initial.policy.mode),[policyConfirmed,setPolicyConfirmed]=useState(false);
 const [selected,setSelected]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(false);
 const [undoId,setUndoId]=useState<string|null>(null),[undoReason,setUndoReason]=useState("");
 async function perform(work:()=>Promise<{ok:true;data:string}|{ok:false;error:string}>) {
  setBusy(true);setError(false);setMessage("");
  try {const r=await work();if(!r.ok){setError(true);setMessage(r.error);return;}setMessage(r.data);setSelected([]);setConfirmed(false);setPolicyConfirmed(false);setUndoId(null);const next=await duplicateBoardAction(periodId);if(next.ok){setBoard(next.data);setMode(next.data.policy.mode);}refresh();}catch{setError(true);setMessage("The result could not be confirmed. Refresh and check history before retrying; confirmed corrections keep the same request IDs.");}finally{setBusy(false);}
 }
 const current=board.candidates.filter(c=>selected.includes(c.id));
 return <section id="obvious-duplicates" aria-label="Obvious duplicates" className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-5">
  <h2 className="text-lg font-semibold">Obvious duplicates</h2><p className="text-sm leading-6">Keep the first verified capture. Review repeated INs or OUTs within five minutes. Automatic handling uses a 60-second window and checks the phone, branch, uploads, surrounding sequence and payroll effect.</p>
  <div className="space-y-3 rounded-lg bg-slate-50 p-3"><label className="block text-sm font-medium">Handling mode<select className={field} value={mode} disabled={busy} onChange={e=>{setMode(e.target.value as DuplicateMode);setPolicyConfirmed(false);}}><option value="Off">Off</option><option value="Suggest">Suggest only</option><option value="Automatic">Automatically handle eligible duplicates</option></select></label><p className="text-xs leading-5">Historical punches always require approval. Enabling automatic handling sets a new start time for future captures. Payroll is never automatically recomputed or approved.</p><label className="flex items-start gap-2 text-sm"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={policyConfirmed} disabled={busy} onChange={e=>setPolicyConfirmed(e.target.checked)}/>I reviewed this policy and its effect on future captures.</label><button className={button} disabled={busy||!policyConfirmed} onClick={()=>perform(()=>duplicatePolicyAction(mode,board.policy.revision,policyConfirmed))}>Save handling mode</button></div>
  <div className={`rounded-lg p-3 text-sm ${error?"bg-red-50 text-red-800":"bg-blue-50 text-blue-900"}`} role={error?"alert":"status"}>{busy?"Checking source records and saving…":message||"No records are changed by viewing suggestions. Original captures and photos are retained."}</div>
  <p className="text-xs text-slate-600">Saved mode: {board.policy.mode}{board.policy.enabledAfter ? `; automatic checks apply to captures after ${originalPunchDateTime(board.policy.enabledAfter)}` : "; automatic handling is disabled"}. Approved deliveries already in progress must finish.</p><h3 className="font-semibold">Suggested · {board.candidates.length} groups</h3>
  {!board.candidates.length&&<p className="text-sm">{board.policy.mode==="Off"?"Suggestions are off. Existing correction history remains below.":"No consecutive same-direction captures within five minutes in this period."}</p>}
  <div className="space-y-3">{board.candidates.map(c=><article key={c.id} className="min-w-0 space-y-2 rounded-lg border p-3"><label className="flex items-start gap-3"><input aria-label={`Select duplicate group for ${c.name}`} className="mt-1 h-5 w-5 shrink-0" type="checkbox" disabled={busy||!c.canApprove} checked={selected.includes(c.id)} onChange={e=>{setSelected(v=>e.target.checked?[...v,c.id]:v.filter(id=>id!==c.id));setConfirmed(false);}}/><span className="font-semibold">{c.name} · Attendance ID {c.sourceId}</span></label><p className="text-sm"><strong>Keep:</strong> {c.kept.type} · {originalPunchDateTime(c.kept.capturedAt)}</p>{c.removed.map(p=><p key={p.eventId} className="text-sm"><strong>Proposed void:</strong> {p.type} · {originalPunchDateTime(p.capturedAt)}</p>)}<p className="text-xs text-slate-600">{c.gapSeconds.toFixed(1)} seconds from first capture · Branch {c.kept.branchId} · Phone {c.kept.deviceId?.slice(-8)??"unknown — sync to update"}</p><ul className="space-y-1 text-xs text-amber-900">{c.warnings.map(w=><li key={w}>{w}</li>)}</ul>{c.eligible&&<p className="text-xs text-blue-800">Candidate for automatic checks. Upload completion is checked with Attendance and payroll impact with Integra.</p>}<div className="rounded bg-slate-50 p-2 text-xs"><p className="font-semibold">Sequence after the proposed void</p>{c.resultingSequence.map(p=><p key={p.eventId}>{p.type} · {originalPunchDateTime(p.capturedAt)}</p>)}</div><details className="text-xs"><summary className="min-h-8 cursor-pointer">Compare phones and record details</summary>{[c.kept,...c.removed].map(p=><p className="break-all py-1" key={p.eventId}>{originalPunchDateTime(p.capturedAt)} · {p.type} · Branch {p.branchId} · Phone {p.deviceId??"unknown"} · Record {p.eventId}</p>)}</details></article>)}</div>
  {!!board.candidates.length&&<div className="space-y-3 border-t pt-4"><label className="block text-sm font-medium">Verification evidence and reason<textarea className={field} maxLength={400} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);setConfirmed(false);}} placeholder="Explain why these are repeated captures; include the supervisor or incident reference."/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>I verified the selected records, the capture to retain, the highlighted warnings and the evidence. This approves voiding the selected repeats at the source.</label><p className="text-xs">Select at most 20 groups, one per employee. Other missing or incorrect punches remain in Needs review.</p><button className={`${button} bg-blue-700 text-white`} disabled={busy||!current.length||current.length>20||!confirmed||reason.trim().length<3} onClick={()=>perform(()=>approveDuplicateBatchAction(periodId,current.map(c=>({id:c.id,version:c.version})),reason,confirmed))}>Approve {current.length} selected groups</button></div>}
  <a className="inline-block min-h-11 py-3 text-sm font-semibold text-blue-700 underline" href="#reconcile-title">Sync this period and check again</a>
  <h3 className="font-semibold">Automatically handled &amp; approved history</h3><p className="text-xs text-slate-600">Undo restores through source history and prevents automatic re-voiding. Sync before undo so the latest source version is checked.</p>
  {!board.history.length&&<p className="text-sm">No duplicate corrections for this period.</p>}
  {board.history.map(h=><article key={h.id} className="space-y-2 rounded-lg border p-3 text-sm"><p className="font-semibold">{h.restored?"Restored; excluded from automation":h.automatic?"Automatic":"Administrator approved"} · {h.state} · {h.kept.employeeName}</p><p>Kept {h.kept.type} · {originalPunchDateTime(h.kept.capturedAt)}</p><p>{h.removed.length} record(s) · {originalPunchDateTime(h.createdAt)}</p><p>{h.reason}</p>{h.result&&<p className="text-xs">{h.result}</p>}<details className="text-xs"><summary className="min-h-8 cursor-pointer">Correction audit details</summary><p className="break-all">Rule: {h.ruleVersion} · Approved by: {h.actor} · Source group: {h.groupId}</p>{[h.kept,...h.removed].map(p=><p className="break-all py-1" key={p.eventId}>{p.eventId===h.kept.eventId?"Kept":"Selected repeat"}: {p.type} · {originalPunchDateTime(p.capturedAt)} · Record {p.eventId} · Prior version {p.correctionVersion??"unknown"}</p>)}</details>{["Sending","Failed"].includes(h.state)&&<button className={button} disabled={busy} onClick={()=>perform(()=>retryAttendanceSourceCorrectionAction(h.id))}>Check / retry delivery</button>}{h.canUndo&&<button className={button} disabled={busy} onClick={()=>{setUndoId(h.id);setUndoReason("");}}>Undo this correction</button>}{undoId===h.id&&<div className="space-y-2"><label className="block">Reason for restoring<textarea className={field} maxLength={400} value={undoReason} onChange={e=>setUndoReason(e.target.value)}/></label><button className={button} disabled={busy||undoReason.trim().length<3} onClick={()=>perform(()=>undoDuplicateAction(h.id,undoReason))}>Confirm restore and exclude from automation</button><button className={button} disabled={busy} onClick={()=>setUndoId(null)}>Cancel</button></div>}</article>)}
 </section>;
}
