"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { attendanceReadinessAction } from "@/app/actions/attendanceSourceAction";
import { originalPunchDateTime, type AttendanceReadiness } from "@/lib/payroll/attendanceResolutionModel";
/** Retains the earlier resolution ledger without reintroducing a second day editor. */
export function LegacyAttendanceHistory({data}:{data:AttendanceReadiness}) {
 const [rows,setRows]=useState(data.history),[page,setPage]=useState(0),[more,setMore]=useState(data.historyHasMore),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const pending=useRef(false),errorRef=useRef<HTMLParagraphElement>(null);
 async function older(){if(pending.current)return;pending.current=true;setBusy(true);setError("");try{const result=await attendanceReadinessAction(data.periodId,page+1);if(!result.ok)throw Error(result.error);setRows(current=>[...new Map([...current,...result.data.history].map(row=>[row.id,row])).values()]);setPage(value=>value+1);setMore(result.data.historyHasMore);}catch(cause){setError(cause instanceof Error?cause.message:"History could not load. Retry here.");setTimeout(()=>errorRef.current?.focus(),0);}finally{pending.current=false;setBusy(false);}}
 return <details className="rounded-lg border p-3"><summary className="min-h-11 cursor-pointer font-semibold">Earlier attendance approvals & proposals</summary><p className="mb-3 text-sm text-muted-foreground">Original historical notes and source receipts remain available. New payroll decisions stay in Integra.</p><div className="space-y-2">{rows.map(row=>{const person=data.people.find(person=>person.sourceId===row.sourceId);return <article key={row.id} className="rounded border p-3 text-sm"><strong>{person?.employeeName??person?.name??`Attendance ID ${row.sourceId}`} · {row.state}</strong><p>{row.kind} · {originalPunchDateTime(row.createdAt)} Philippine time</p>{row.reason&&<p>Saved note: {row.reason}</p>}{row.evidence&&<details><summary className="min-h-9 cursor-pointer py-1">Saved evidence</summary><p className="break-words">{row.evidence}</p></details>}{row.manualPunches.map((punch,index)=><p key={index}>{punch.type} · {punch.localDateTime.replace("T"," ")} Philippine time</p>)}{row.result&&<p>{row.result}</p>}<Link className="mt-2 inline-flex min-h-11 items-center text-blue-700 underline" href={`/payroll/attendance-batch?periodId=${data.periodId}&sourceId=${encodeURIComponent(row.sourceId)}&view=add`}>Open current batch context</Link></article>;})}</div>{!rows.length&&<p className="text-sm">No earlier resolutions for this period.</p>}{error&&<p ref={errorRef} tabIndex={-1} role="alert" className="my-2 text-sm text-red-700">{error}</p>}{more&&<button disabled={busy} className="mt-3 min-h-11 rounded border px-3 py-2 text-sm font-semibold" onClick={()=>void older()}>{busy?"Loading earlier history…":"Load earlier history"}</button>}</details>;
}
