"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { syncAttendanceSourceAction, saveAttendanceSourceMappingAction } from "@/app/actions/attendanceSourceAction";
import { refreshAttendancePeriodSummariesAction } from "@/app/actions/attendanceImportAction";
import type { SourcePunch } from "@/lib/payroll/attendanceSourceClient";
import { attendancePeriodUrl, selectAttendanceSourcePeriod, type AttendanceSourcePeriod } from "@/lib/payroll/attendanceSourcePeriods";
type Props = { initialYear: number; initialPeriodId: string; today: string; inbox: SourcePunch[]; periods: AttendanceSourcePeriod[]; employees: { id: string; label: string }[]; mappings: { sourceId: string; employeeId: string }[]; runs: { id: string; state: string; startedAt: string; counts: string; error: string | null }[] };
export function AttendanceSourcePanel(props: Props) {
  const router = useRouter();
  const [changingPeriod, startPeriodChange] = useTransition();
  const [sourceId, setSourceId] = useState(""), [employee, setEmployee] = useState(""), [reason, setReason] = useState(""), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const busy = saving || changingPeriod;
  const period = props.initialPeriodId, year = props.initialYear;
  const periods = selectAttendanceSourcePeriod(props.periods, { year: String(year), periodId: period }, props.today).periods;
  const years = [...new Set([year, ...props.periods.map(p => p.year)])].sort((a, b) => b - a);
  function changePeriod(nextYear: number, nextPeriod: string) {
    startPeriodChange(() => router.replace(attendancePeriodUrl("/payroll/attendance-source", nextYear, nextPeriod), { scroll: false }));
  }
  async function perform(fn: () => Promise<unknown>) { setSaving(true); setMessage(""); try { const result = await fn(); setMessage(result ? JSON.stringify(result) : "Saved. Run attendance sync to reconcile this mapping."); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed"); } finally { setSaving(false); } }
  return <main className="mx-auto min-w-0 max-w-4xl space-y-6 p-6"><Link href={attendancePeriodUrl("/payroll", year, period)}>Back to payroll</Link><h1 className="text-2xl font-semibold">Attendance connection</h1><p>Pull the whole payroll period again to pick up late uploads, voids and identity corrections. Closed periods and posted payroll stay unchanged; late changes appear in sync history.</p>
    <section className="space-y-3 rounded border p-4"><h2 className="font-semibold">Reconcile attendance</h2>
      <label className="block">Payroll year<select className="mt-1 block max-w-full border p-2" value={year} disabled={busy} onChange={e => { const next = selectAttendanceSourcePeriod(props.periods, { year: e.target.value }, props.today); changePeriod(next.year, next.periodId); }}>{years.map(y => <option key={y} value={y}>{y}</option>)}</select></label>
      <label className="block">Payroll period<select className="mt-1 block max-w-full border p-2" value={period} onChange={e => changePeriod(year, e.target.value)} disabled={busy || !periods.length}>{!periods.length && <option value="">No periods for this year</option>}{periods.map(p => <option key={p.id} value={p.id}>{p.code} · {p.startDate} – {p.endDate}</option>)}</select></label>
      <div className="flex flex-wrap gap-3"><button className="rounded bg-blue-700 px-4 py-2 text-white" disabled={busy || !period} onClick={() => perform(() => syncAttendanceSourceAction(period))}>Sync attendance now</button><button className="rounded border px-4 py-2" disabled={busy || !period} onClick={() => perform(() => refreshAttendancePeriodSummariesAction(period))}>Refresh attendance summaries</button></div><p>After changed input, refresh summaries and review the DTR before recomputing payroll. Unmapped employees and unresolved source flags remain withheld. Resolve overlapping file imports before switching an employee/date to this source.</p></section>
    <section className="space-y-3 rounded border p-4"><h2 className="font-semibold">Verify an employee mapping</h2><label className="block">Attendance employee ID<input className="ml-3 border p-2" value={sourceId} onChange={e => setSourceId(e.target.value)} maxLength={64}/></label><label className="block">Payroll employee<select className="ml-3 max-w-full border p-2" value={employee} onChange={e => setEmployee(e.target.value)}><option value="">Select employee</option>{props.employees.map(e => <option key={e.id} value={e.id}>{e.label}</option>)}</select></label><label className="block">Verification reason<input className="ml-3 border p-2" value={reason} onChange={e => setReason(e.target.value)} maxLength={500}/></label><button className="rounded border px-4 py-2" disabled={busy || !sourceId || !employee || !reason.trim()} onClick={() => perform(() => saveAttendanceSourceMappingAction(sourceId, employee, reason))}>Save verified mapping</button><ul>{props.mappings.map(m => <li key={m.sourceId}>{m.sourceId} → {props.employees.find(e => e.id === m.employeeId)?.label ?? m.employeeId}</li>)}</ul></section>
    <section className="space-y-3"><h2 className="font-semibold">Recent source punches</h2><p>Latest 500 punches across reconciled periods. IDs stay unchanged even when a punch is corrected. Resolve source review flags in the attendance dashboard, then sync again.</p><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Captured (Manila)</th><th>Source employee</th><th>Punch</th><th>Review</th></tr></thead><tbody>{props.inbox.map(p=><tr key={p.eventId} className="border-t"><td className="p-2">{new Date(p.capturedAt).toLocaleString("en-PH",{timeZone:"Asia/Manila"})}</td><td className="p-2">{p.employeeId} · {p.employeeName}</td><td className="p-2">{p.type} · {p.branchId} · {p.status}</td><td className="p-2">{!props.mappings.some(m=>m.sourceId===p.employeeId)?"Employee mapping needed. ":""}{p.clockFlag?"Clock review. ":""}{p.reviewResolved?"Source review resolved":p.reviewFlags.join(", ")}</td></tr>)}</tbody></table></div></section>
    <p role="status" className="break-words">{busy ? "Working…" : message}</p><section><h2 className="font-semibold">Recent syncs</h2><ul className="divide-y">{props.runs.map(r => <li key={r.id} className="py-3"><strong>{r.state}</strong> · {r.startedAt}<p className="break-words">{r.error ?? r.counts}</p></li>)}</ul></section></main>;
}
