"use client";
import { useRef, useState } from "react";
import { generateUUID } from "@/lib/uuid";
import type { WorkChange } from "@/lib/payroll/attendanceWorkbenchModel";
export function QuickPunch({day,busy,initialDirection="IN",onReview,onEdit}:{day:string;busy:boolean;initialDirection?:"IN"|"OUT";onEdit:()=>void;onReview:(change:WorkChange,note:string)=>Promise<void>}) {
 const [type,setType]=useState<"IN"|"OUT">(initialDirection),[date,setDate]=useState(day),[time,setTime]=useState(""),[note,setNote]=useState("");
 const changeId=useRef(generateUUID());
 return <section aria-label="Add actual punch" className="my-3 space-y-2 rounded border border-blue-300 bg-blue-50 p-3"><h4 className="font-semibold">Add missing IN or OUT</h4><fieldset disabled={busy} className="grid gap-2 sm:grid-cols-4"><label className="text-sm">Direction<select className="block min-h-11 w-full rounded border bg-white p-2" value={type} onChange={e=>{onEdit();setType(e.target.value as 'IN'|'OUT');}}><option>IN</option><option>OUT</option></select></label><label className="min-w-0 text-sm">Capture date<input className="block min-h-11 w-full min-w-0 rounded border bg-white p-2" type="date" value={date} onChange={e=>{onEdit();setDate(e.target.value);}}/></label><label className="min-w-0 text-sm">Actual Philippine time<input className="block min-h-11 w-full min-w-0 rounded border bg-white p-2" type="time" step="1" value={time} onChange={e=>{onEdit();setTime(e.target.value);}}/></label><label className="text-sm">Note (optional)<input className="block min-h-11 w-full rounded border bg-white p-2" value={note} placeholder="Add context if useful" onChange={e=>{onEdit();setNote(e.target.value);}}/></label></fieldset><p className="text-xs">Review the actual time before confirming. Notes are optional. Every selected change for this employee is included; final confirmation is separate.</p><button disabled={busy||!time||!date} className="min-h-11 rounded bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" onClick={()=>void onReview({id:changeId.current,day,kind:'Manual',type,at:`${date}T${time}`,reason:note.trim(),evidence:"",verified:false},note)}>Review correction</button></section>;
}
