"use client";
import { useEffect, useRef, useState } from "react";
import { DaySchedule } from "./day-schedule";
import { BatchReview, changeLabels as labels } from "./batch-review";
import Link from "next/link";
import { generateUUID } from "@/lib/uuid";
import type { WorkBoard, WorkDraft, WorkChange, WorkKind, WorkRecord, WorkEmployee, WorkDay } from "@/lib/payroll/attendanceWorkbenchModel";
import { simulateWork, sequenceProblems, missingDateRanges, retainedDraftVersion, reconcileDraftVerification, verificationIssues, draftRecords, workDate } from "@/lib/payroll/attendanceWorkbenchModel";
import { originalPunchDateTime } from "@/lib/payroll/attendanceResolutionModel";
import { saveWorkDraftAction, previewWorkBatchAction, approveWorkBatchAction, retryWorkBatchAction, refreshWorkBoardAction, closeAttendanceAdjustmentAction, reopenWorkPlanAction, undoWorkPlanAction, keepAdminAttendanceAction } from "@/app/actions/attendanceWorkbenchAction";
import { syncAttendanceSourceAction, refreshAttendanceSourceSummariesAction } from "@/app/actions/attendanceSourceAction";

const button="min-h-11 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-blue-600";
const primary=button+" !bg-blue-700 !text-white !border-blue-700";
const field="block w-full min-w-0 rounded-lg border border-slate-300 bg-white p-2 text-sm";
type BatchPreview={batchId:string;revision:number;digest:string;prepared:{id:string;draft:WorkDraft;preview:{errors:string[];warnings:string[];records:WorkRecord[]};impacts:string[];periodEvidence?:{id:string;code:string;posted:boolean}[]}[]};
function SuggestionDetails({day,index=0}:{day:WorkDay;index?:number}) {
 const suggestion=day.suggestions[index];
 return <span className="col-start-2 text-sm md:col-auto">
  <strong className="block">{suggestion.label}</strong>
  {suggestion.changes.map((change,index)=>{
   const record=day.records.find(r=>change.eventId?r.id===change.eventId:change.rawLogId!==undefined&&r.rawLogId===change.rawLogId);
   if(record)return <span key={index} className="mt-1 block text-slate-700">
    <span className="block">{originalPunchDateTime(record.at)} · Philippine time</span>
    <span className="block">{record.type}{change.kind==="Direction"?` → ${change.type} · time unchanged`:""}</span>
    {(record.originalType&&record.originalType!==record.type||record.originalAt&&record.originalAt!==record.at)&&<span className="block text-xs">Original capture: {record.originalType??record.type} · {originalPunchDateTime(record.originalAt??record.at)}</span>}
   </span>;
   if(change.kind==="Manual")return <span key={index} className="mt-1 block text-slate-700">Missing {change.type??"IN/OUT"} · {change.day??day.day}<span className="block">Time unknown — verification required</span></span>;
   return <span key={index} className="mt-1 block text-slate-700">Punch details unavailable — refresh before review.</span>;
  })}
 </span>;
}
export function AttendanceWorkbench({initial}:{initial:WorkBoard}) {
 const [board,setBoard]=useState(initial),[search,setSearch]=useState(""),[filter,setFilter]=useState("Needs review"),[employeeId,setEmployeeId]=useState(""),[day,setDay]=useState("");
 const [drafts,setDrafts]=useState<WorkDraft[]>([]),[batch,setBatch]=useState<{id:string;revision:number}|undefined>(),[preview,setPreview]=useState<BatchPreview|null>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("Suggestions");
 const [hydrated,setHydrated]=useState(false);
 const batchEditor=useRef<HTMLDivElement>(null),errorPanel=useRef<HTMLDivElement>(null);
 const [reviewEmployees,setReviewEmployees]=useState<string[]|null>(null);
 useEffect(()=>{if(error){errorPanel.current?.scrollIntoView({block:"center"});errorPanel.current?.focus({preventScroll:true});}},[error]);
 useEffect(()=>{if(tab==="Batch review"){batchEditor.current?.scrollIntoView({block:"start"});batchEditor.current?.focus({preventScroll:true});}},[tab]);
 const storage=`integra-attendance-review:${board.period.id}`;
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storage)??"null");if(saved){setDrafts(reconcileDraftVerification([],saved.drafts??[],initial.employees));setBatch(saved.batch);setSearch(saved.search??"");setFilter(saved.filter??"Needs review");setEmployeeId(saved.employeeId??"");setDay(saved.day??"");}}catch{}setHydrated(true);},[storage,initial.employees]);
 useEffect(()=>{if(hydrated)sessionStorage.setItem(storage,JSON.stringify({drafts,batch,search,filter,employeeId,day}));},[storage,hydrated,drafts,batch,search,filter,employeeId,day]);
 const person=board.employees.find(p=>p.id===employeeId),selectedDay=person?.days.find(d=>d.day===day),draft=drafts.find(d=>d.employeeId===employeeId);
 const selected=drafts.reduce((n,d)=>n+d.changes.length,0);
 const incomplete=drafts.reduce((n,d)=>n+d.changes.filter(c=>verificationIssues(board.employees.find(p=>p.id===d.employeeId),d,c,board.employees).length>0).length,0);
 const approvalDrafts=drafts.filter(d=>reviewEmployees===null||reviewEmployees.includes(d.employeeId));
 const approvalIncomplete=approvalDrafts.some(d=>d.rejected||d.changes.some(c=>!c.verified||verificationIssues(board.employees.find(p=>p.id===d.employeeId),d,c,board.employees).length));
 const unverified=drafts.reduce((n,d)=>n+d.changes.filter(c=>!c.verified).length,0);
 function changeDrafts(next:WorkDraft[]){setReviewEmployees(null);setDrafts(reconcileDraftVerification(drafts,next,board.employees));setPreview(null);setAck(false);}
 function editDraft(id:string,patch:Partial<WorkDraft>){changeDrafts(drafts.map(d=>d.employeeId===id?{...d,...patch}:d));}
 async function run<T>(fn:()=>Promise<{ok:true;data:T}|{ok:false;error:string}>,success?:(data:T)=>void){
  setBusy(true);setError("");try{const result=await fn();if(!result.ok)setError(result.error);else await success?.(result.data);}
  catch{
   setPreview(null);setAck(false);
   try{
    const latest=await refreshWorkBoardAction(board.period.id);
    if(!latest.ok)throw Error("Status unavailable");
    setBoard(latest.data);
    const attempted=new Set(preview?.prepared.map(p=>p.id)??[]),confirmed=latest.data.plans.filter(p=>attempted.has(p.id)&&p.approved);
    if(confirmed.length){
     setDrafts(current=>current.filter(d=>!confirmed.some(p=>p.draft.employeeId===d.employeeId)));
     setBatch({id:confirmed[0].batchId,revision:confirmed[0].revision});setReviewEmployees(null);setTab("Progress & history");
     setNotice(`${confirmed.length} employee decisions are approved. Approval was confirmed by a status check after the interrupted response. Source delivery is separate.`);
    }else setError("The response was interrupted. Status was checked; your inputs are retained. Review the saved batch before retrying approval.");
   }catch{setError("The response and status check were interrupted. Your inputs are retained. Open progress to check the saved result before retrying; approval may already be recorded.");}
  }finally{setBusy(false);}
 }
 async function reload(){const r=await refreshWorkBoardAction(board.period.id);if(r.ok){setBoard(r.data);setDrafts(current=>reconcileDraftVerification(current,current,r.data.employees));setPreview(null);setAck(false);}else setError(r.error);}
 function add(kind:WorkKind,record?:WorkRecord,values:Partial<WorkChange>={}, targetEmployee=employeeId,targetDay=day) {
  const person=board.employees.find(p=>p.id===targetEmployee),selectedDay=person?.days.find(d=>d.day===targetDay),draft=drafts.find(d=>d.employeeId===targetEmployee),employeeId=targetEmployee,day=targetDay;
  if(!person||!selectedDay)return;
  const c:WorkChange={id:generateUUID(),day,kind,reason:"",evidence:"",verified:false,...(record?.source==="API"?{eventId:record.id}:{rawLogId:record?.rawLogId}),...(kind==="Direction"?{type:record?.type==="IN"?"OUT":"IN"}:{}),...values};
  const previous=draft??{employeeId,days:[],changes:[],reason:"",ownerId:"",needed:"",rejected:false,version:""};
  // The server calculates the evidence digest before saving; the individual versions are retained here.
  const days=[...new Set([...previous.days,day])].sort();
  const next={...previous,days,changes:[...previous.changes,c],version:retainedDraftVersion(person,days,previous)};
  changeDrafts(draft?drafts.map(d=>d.employeeId===employeeId?next:d):[...drafts,next]);
 }
 function editChange(employee:string,id:string,patch:Partial<WorkChange>){
  const next=drafts.map(d=>d.employeeId===employee?{...d,changes:d.changes.map(c=>c.id===id?{...c,...patch}:c)}:d);
  if(patch.targetEmployeeId){const target=board.employees.find(p=>p.id===patch.targetEmployeeId)!,c=next.find(d=>d.employeeId===employee)!.changes.find(c=>c.id===id)!;const existing=next.find(d=>d.employeeId===target.id);
   if(!target.days.some(d=>d.day===c.day)){setError("The receiving employee is not eligible for that workday. Review employment dates.");return;}
   if(!existing?.days.includes(c.day)){const days=[...new Set([...(existing?.days??[]),c.day])].sort();const linked:WorkDraft={employeeId:target.id,days,changes:[...(existing?.changes??[]),{id:generateUUID(),day:c.day,kind:"ReopenDay",reason:"Review the receiving employee and remaining sequence",evidence:"",verified:false}],reason:existing?.reason??"",ownerId:existing?.ownerId??"",needed:"Verify the receiving employee and resulting sequence",rejected:false,version:retainedDraftVersion(target,days,existing)};if(existing)next.splice(next.indexOf(existing),1,linked);else next.push(linked);}
  }
  changeDrafts(next);
 }
 function draftMissingRange(p:WorkEmployee,days:string[]){
  const existing=drafts.find(d=>d.employeeId===p.id),fresh=days.filter(day=>!existing?.changes.some(c=>c.day===day));
  const changes=[...(existing?.changes??[]),...fresh.flatMap(day=>(["IN","OUT"] as const).map(type=>({id:generateUUID(),day,kind:"Manual" as const,type,reason:"",evidence:"",verified:false})))];
  if(selected+fresh.length*2>200||!existing&&drafts.length>=20){setError("Divide this range explicitly: a batch supports 20 employees and 200 changes. No dates were added.");return;}
  const allDays=[...new Set(changes.map(c=>c.day))].sort();changeDrafts([...drafts.filter(d=>d.employeeId!==p.id),{employeeId:p.id,days:allDays,changes,reason:existing?.reason??"",ownerId:existing?.ownerId??"",needed:"Check uploads, schedule and leave. Supply actual times or use the day review to confirm no attendance.",rejected:false,version:retainedDraftVersion(p,allDays,existing)}]);setTab("Batch review");
 }
 const records=person&&draft?draftRecords(person,draft).filter(r=>selectedDay?.records.some(x=>x.id===r.id)||day===workDate(r.at)||selectedDay?.decision?.incomingRecords.some(x=>x.id===r.id)):selectedDay?.records??[],simulation=person&&draft?simulateWork(records,draft.changes.filter(c=>c.day===day),person.id):{records,errors:[]},sequence=sequenceProblems(simulation.records,selectedDay?.schedule??null);
 async function save(showPreview=false){
  await run(()=>saveWorkDraftAction(board.period.id,drafts,batch),async saved=>{
   setBatch(saved);setNotice("Draft saved. Attendance and payroll have not changed.");
   const latest=await refreshWorkBoardAction(board.period.id);
   if(!latest.ok){setError(latest.error);return;}setBoard(latest.data);
   if(showPreview){const ids=latest.data.plans.filter(p=>p.batchId===saved.id&&approvalDrafts.some(d=>d.employeeId===p.draft.employeeId)).map(p=>p.id);
    await run(()=>previewWorkBatchAction(board.period.id,saved.id,saved.revision,ids),p=>{setPreview(p);setAck(false);setTab("Batch review");});}
  });
 }
 const filtered=board.employees.filter(p=>`${p.no} ${p.name} ${p.sourceIds.join(" ")}`.toLowerCase().includes(search.toLowerCase())).filter(p=>filter==="All people"||p.days.some(d=>filter==="No work recorded"?d.status==="No work recorded":d.issues.length>0));
 function selectSuggestion(p:WorkEmployee,d:WorkDay,checked:boolean){
  const existing=drafts.find(x=>x.employeeId===p.id),key=`suggestion:${p.id}:${d.day}`;
  const changes=(existing?.changes??[]).filter(c=>!c.id.startsWith(key));
  if(checked)for(const [i,c] of d.suggestions[0].changes.entries())changes.push({id:`${key}:${i}`,day:d.day,kind:c.kind!,reason:"",evidence:"",verified:false,...c});
  const days=[...new Set(changes.map(c=>c.day))].sort(),next:WorkDraft={employeeId:p.id,days,changes,ownerId:existing?.ownerId??"",reason:existing?.reason??"",needed:existing?.needed??"",rejected:false,version:retainedDraftVersion(p,days,existing)};
  changeDrafts([...drafts.filter(x=>x.employeeId!==p.id),...(changes.length?[next]:[])]);
 }
 return <section id="attendance-review" className="min-w-0 max-w-full scroll-mt-20 space-y-4 rounded-xl border bg-slate-50 p-3 pb-8 [overflow-wrap:anywhere] sm:p-5" aria-label="Attendance resolution workspace">
  <div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Attendance review & sync</p><h2 className="text-xl font-bold">{board.period.code} · Resolve attendance</h2><p className="text-sm text-slate-600">{board.period.startDate} – {board.period.endDate} · Philippine time (UTC+8)</p></div>
  <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{Object.entries(board.statuses).map(([key,value])=><div key={key} className="rounded-lg border bg-white p-3"><div className="text-xs font-semibold uppercase">{{sync:"Source sync",review:"Attendance review",delivery:"Correction delivery",dtr:"DTR freshness",payroll:"Payroll"}[key]}</div><div className="mt-1 text-sm">{value}</div></div>)}</div>
  <p className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm">Payroll has not been recomputed by this workflow. Review and approve corrections explicitly, then inspect refreshed DTR before recomputing.</p>
  {error&&<div ref={errorPanel} tabIndex={-1} role="alert" className="rounded-lg border-2 border-red-600 bg-red-50 p-3"><strong>Action needs attention</strong><p>{error}</p><p className="mt-2 text-sm">Your draft is retained. Check delivery progress before retrying.</p><button className={button+" mt-2"} onClick={()=>{setTab("Progress & history");void reload();}}>Open progress</button></div>}
  {notice&&<div role="status" className="rounded-lg border border-blue-300 bg-white p-3 text-sm">{notice}</div>}
  <nav className="flex flex-wrap gap-2" aria-label="Review sections">{["Suggestions","Coverage","Batch review","Progress & history"].map(t=><button key={t} className={tab===t?primary:button} aria-pressed={tab===t} onClick={()=>{setTab(t);if(t==="Progress & history")void reload();}}>{t}</button>)}</nav>
  <div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>run(()=>syncAttendanceSourceAction(board.period.id),async message=>{setNotice(message);await reload();})}>Check uploads / Sync this period</button><button className={button} disabled={busy} onClick={()=>run(()=>refreshAttendanceSourceSummariesAction(board.period.id),async message=>{setNotice(typeof message==="string"?message:"DTR refreshed. Inspect it before recomputing.");await reload();})}>Refresh DTR</button><Link className={button} href={`/payroll/attendance-imports?periodId=${board.period.id}`}>Inspect DTR</Link><Link className={button} href={`/payroll?periodId=${board.period.id}`}>Recompute → Review payroll</Link></div>
  {(tab==="Suggestions"||tab==="Coverage")&&<>
   <p className="text-sm text-slate-600">Select the suggested changes you want to review, then choose Open batch review below. Selection does not approve a correction.</p>
   <div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Find employee<input className={field} value={search} onChange={e=>{setSearch(e.target.value);setEmployeeId("");}} placeholder="Name, payroll or attendance ID"/></label><label className="text-sm">Show<select className={field} value={filter} onChange={e=>setFilter(e.target.value)}>{["Needs review","No work recorded","All people"].map(v=><option key={v}>{v}</option>)}</select></label></div>
   {!person&&tab==="Suggestions"&&<div className="overflow-hidden rounded-xl border bg-white"><div className="hidden grid-cols-[2rem_1fr_1fr_2fr] gap-3 bg-slate-100 p-3 text-xs font-semibold md:grid"><span/><span>Employee / workday</span><span>Suggested action</span><span>Why / verification needed</span></div>{filtered.flatMap(p=>p.days.filter(d=>d.issues.length&&d.suggestions.length).map(d=><label key={`${p.id}:${d.day}`} className="grid grid-cols-[2rem_1fr] gap-3 border-t p-3 md:grid-cols-[2rem_1fr_1fr_2fr]"><input className="mt-1 h-5 w-5" type="checkbox" aria-label={`Select suggestion for ${p.name} ${d.day}`} checked={drafts.some(x=>x.employeeId===p.id&&x.changes.some(c=>c.id.startsWith(`suggestion:${p.id}:${d.day}`)))} onChange={e=>selectSuggestion(p,d,e.target.checked)}/><span className="text-sm"><strong>{p.name}</strong><span className="block">{p.no} · {d.day}</span></span><SuggestionDetails day={d}/><span className="col-start-2 text-sm text-slate-600 md:col-auto">{d.suggestions[0].explanation} Evidence is required before approval.</span></label>))}</div>}
   {!person&&tab==="Coverage"&&<div className="space-y-3"><h3 className="font-semibold">Missing date ranges</h3><p className="text-sm">All eligible employees are checked, including people without punches. Future days, ongoing shifts, approved leave and rest days are shown separately in All people.</p>{filtered.flatMap(p=>missingDateRanges(p.days).map(range=><article key={`${p.id}:${range.from}`} className="rounded-xl border bg-white p-4"><strong>{p.name} · {p.no}</strong><p>{range.from}{range.through!==range.from?` – ${range.through}`:""} · {range.days.length} missing workdays</p><div className="mt-2 flex flex-wrap gap-2"><button className={button} onClick={()=>{setEmployeeId(p.id);setDay(range.from);}}>Review dates, schedule and leave</button><button className={button} onClick={()=>draftMissingRange(p,range.days)}>Draft verified shifts for this range</button></div><p className="mt-2 text-xs">Dates and directions are supplied; actual times and evidence remain blank. This does not record attendance.</p></article>))}</div>}
   {!person?<div className="grid gap-3 lg:grid-cols-2">{filtered.map(p=><article key={p.id} className="rounded-xl border bg-white p-4"><h3 className="font-semibold">{p.name} · {p.no}</h3><p className="text-xs text-slate-600">Attendance {p.sourceIds.join(", ")||"not matched"}</p><p className="my-2 text-sm">{p.days.filter(d=>d.issues.length).length} workdays need review</p><div className="flex flex-wrap gap-2">{p.days.filter(d=>filter==="All people"||d.issues.length||filter==="No work recorded"&&d.status==="No work recorded").map(d=><button key={d.day} className={button} onClick={()=>{setEmployeeId(p.id);setDay(d.day);}}>{d.day}<span className="block text-xs font-normal">{d.status}</span></button>)}</div></article>)}{!filtered.length&&<p>No employees in this filter.</p>}</div>:<>
    <button className={button} onClick={()=>setEmployeeId("")}>← All employee cases</button>
    <div className="rounded-xl border bg-white p-4"><h3 className="text-lg font-bold">{person.name} · {person.no}</h3><label className="mt-3 block text-sm">Workday<select className={field} value={day} onChange={e=>setDay(e.target.value)}>{person.days.map(d=><option key={d.day} value={d.day}>{d.day} · {d.status}</option>)}</select></label>
    <p className="my-2 text-sm text-amber-800">{selectedDay?.issues.join(" · ")||"No unresolved issues on this workday"}</p>
    <div className="my-3 flex flex-wrap gap-2"><Link className={button} href={`/payroll/attendance-source?periodId=${board.period.id}#employee-matching`}>Employee matching</Link><Link className={button} href="/employeeLeaves">Leave records</Link></div>
    <DaySchedule key={person.id+day} employeeId={person.id} day={day} onSaved={reload}/>
    {selectedDay?.decision&&<div className="my-2 rounded border border-blue-200 bg-blue-50 p-3 text-sm"><strong>{selectedDay.decision.payrollRunId?"Payroll attendance retained":"Admin decision approved"}</strong><p>{selectedDay.decision.reason} · {originalPunchDateTime(selectedDay.decision.approvedAt)}</p>
     {selectedDay.decision.lateConflict&&<><p className="my-2 text-amber-900">Incoming attendance differs. Your approved decision and payroll are unchanged.</p><details><summary className="min-h-11 cursor-pointer">Compare incoming attendance</summary>{selectedDay.decision.incomingRecords.map(r=><p key={r.id}>{r.type} · {originalPunchDateTime(r.at)} · {r.status}</p>)}</details><div className="flex flex-wrap gap-2">
      <button className={button} disabled={busy} onClick={()=>run(()=>keepAdminAttendanceAction(board.period.id,person.id,day,selectedDay.decision!.incomingDigest),async message=>{setNotice(message);await reload();})}>Keep admin decision</button>
      <button className={button} disabled={busy} onClick={()=>{const previous=draft??{employeeId:person.id,days:[],changes:[],reason:"",ownerId:"",needed:"",rejected:false,version:""};const incomingDays=[...new Set([day,...selectedDay.decision!.incomingRecords.map(r=>workDate(r.at))])].filter(date=>person.days.some(d=>d.day===date));const days=[...new Set([...previous.days,...incomingDays])];const next={...previous,days,version:retainedDraftVersion(person,days,previous),incomingVersions:{...previous.incomingVersions,[day]:selectedDay.decision!.incomingDigest},changes:[...previous.changes.filter(c=>!incomingDays.includes(c.day)),...incomingDays.map(date=>({id:generateUUID(),day:date,kind:"ReopenDay" as const,reason:"",evidence:"",verified:false}))]};changeDrafts([...drafts.filter(d=>d.employeeId!==person.id),next]);setTab("Batch review");}}>Review incoming attendance</button>
     </div></>}
    </div>}
    {selectedDay?.suggestions.map((suggestion,i)=><div key={i} className="my-2 rounded-lg border border-blue-200 bg-blue-50 p-3"><SuggestionDetails day={selectedDay!} index={i}/><p className="text-sm">{suggestion.explanation}</p><button className={button+" mt-2"} onClick={()=>{const c=suggestion.changes[0];add(c.kind!,records.find(r=>r.id===c.eventId),c);}}>Add to review</button></div>)}
    <h4 className="mt-4 font-semibold">Original and currently effective attendance</h4><p className="mb-2 text-xs text-slate-600">Every capture retains its full date, exact time and history. Adjacent dates remain visible.</p>
    {records.map(r=><article key={r.id} className="my-2 rounded-lg border p-3"><div className="font-semibold">{r.type} · {originalPunchDateTime(r.at)}</div><p className="text-xs">{r.source} · {r.status}{r.excluded?" · Excluded from DTR":""}</p>{r.originalAt&&(r.originalAt!==r.at||r.originalType!==r.type)&&<p className="mt-1 text-sm">Original: {r.originalType} · {originalPunchDateTime(r.originalAt)}</p>}{r.clockFlag&&<p className="text-sm text-amber-800">Original device clock warning{r.clockVerified?" · Effective time verified":" · Needs verified time"}</p>}<details className="my-2 text-xs"><summary>Capture details and photo reference</summary><p className="break-all">{r.id}</p><p>Attendance employee: {r.sourceEmployeeId??"Manual / file evidence"}</p><p>Photo reference: {r.source==="API"?r.id:"No original camera capture"}</p></details><div className="flex flex-wrap gap-2">{(r.source==="API"?["Direction","Time","Employee",r.status==="VALID"?"Void":"Restore",r.excluded?"Retain":"Exclude"]:r.excluded?["Retain"]:["Exclude"]).map(k=><button key={k} className={button} onClick={()=>add(k as WorkKind,r)}>{labels[k as WorkKind]}</button>)}</div></article>)}
    {!records.length&&<p className="my-4 rounded-lg border border-dashed p-4">No work recorded. This does not block payroll. Add actual times only when you have evidence.</p>}
    <div className="flex flex-wrap gap-2">{["Manual","ConfirmSequence","NoAttendance"].map(k=><button key={k} className={button} onClick={()=>add(k as WorkKind)}>{labels[k as WorkKind]}</button>)}</div>
    {draft&&<div className="mt-4 rounded-lg border border-blue-300 bg-blue-50 p-3"><h4 className="font-semibold">Proposed sequence</h4>{simulation.records.filter(r=>r.status==="VALID"&&!r.excluded).map(r=><p key={r.id} className="text-sm">{r.type} · {originalPunchDateTime(r.at)}</p>)}<p className="mt-2 text-sm text-amber-900">{[...simulation.errors,...sequence.errors,...sequence.warnings].join(" · ")||"Sequence pairs correctly. Verification and batch approval are still required."}</p></div>}
    </div>
   </>}
  </>}
  {tab==="Batch review"&&<div ref={batchEditor} tabIndex={-1} aria-label="Batch editor" className="scroll-mt-20 space-y-3 outline-none"><div className="rounded border bg-white p-3"><h3 className="font-semibold">Include in final approval</h3><p className="text-xs">Unselected plans stay in this saved batch. Shared evidence and verification still cover every draft change.</p>{drafts.map(d=><label key={d.employeeId} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={reviewEmployees===null||reviewEmployees.includes(d.employeeId)} onChange={e=>{setReviewEmployees(e.target.checked?[...(reviewEmployees??drafts.map(x=>x.employeeId)),d.employeeId]:(reviewEmployees??drafts.map(x=>x.employeeId)).filter(id=>id!==d.employeeId));setPreview(null);setAck(false);}}/>{board.employees.find(p=>p.id===d.employeeId)?.name} · {d.changes.length} changes</label>)}</div><BatchReview board={board} drafts={drafts} busy={busy} onChange={changeDrafts} editDraft={editDraft} editChange={editChange} onNotice={setNotice} onAdd={(employee,date,kind,record)=>add(kind,record,{},employee,date)} onScheduleSaved={reload}/>
   {preview&&<div className="space-y-3 rounded-xl border-2 border-blue-700 bg-white p-4"><h3 className="text-lg font-bold">Final batch preview</h3>{preview.prepared.map(p=><div key={p.id}><strong>{board.employees.find(e=>e.id===p.draft.employeeId)?.name}</strong><p className="text-sm">{p.draft.changes.length} changes · {p.impacts.length} affected payroll periods</p><p className="text-sm">{p.periodEvidence?.map(period=>`${period.code}${period.posted?" · Linked adjustment required":""}`).join("; ")}</p>{p.preview.warnings.map(w=><p key={w} className="text-sm text-amber-800">{w}</p>)}{p.preview.records.filter(r=>r.status==="VALID"&&!r.excluded).map(r=><p key={r.id} className="text-sm">{r.type} · {originalPunchDateTime(r.at)}</p>)}</div>)}{board.period.posted&&<p className="font-semibold text-amber-900">Posted payroll stays unchanged. Linked adjustment cases will require review.</p>}<label className="flex items-start gap-2"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I reviewed every selected change, highlighted warning, affected period and required adjustment.</label><button className={primary} disabled={!ack||busy} onClick={()=>run(()=>approveWorkBatchAction(board.period.id,preview.batchId,preview.revision,preview.digest,preview.prepared.map(p=>p.id)),async ()=>{setNotice("Decision approved for payroll. Source delivery continues separately. Refresh DTR before computing payroll.");const remaining=drafts.filter(d=>!preview.prepared.some(p=>p.draft.employeeId===d.employeeId));setTab("Progress & history");setPreview(null);setAck(false);setDrafts(remaining);setBatch(remaining.length?{id:preview.batchId,revision:preview.revision+1}:undefined);setReviewEmployees(null);await reload();})}>Approve payroll attendance</button></div>}
  </div>}
  {tab==="Progress & history"&&<div className="space-y-3"><p className="text-sm">Approval records the payroll decision immediately. Source delivery and DTR refresh have separate progress; retry preserves the decision and original request ID.</p>{board.plans.map(p=><article key={p.id} className="rounded-xl border bg-white p-4"><h3 className="font-semibold">{board.employees.find(e=>e.id===p.draft.employeeId)?.name} · {p.approved?"Decision approved":p.state}</h3>{p.approved&&<p className="text-sm">Attendance source: {p.state==="Resolved"?"Up to date":p.state==="Source conflict"?"Conflicting evidence — admin decision retained":"Update pending"} · DTR: {board.statuses.dtr}</p>}<p className="text-sm">Reason: {p.draft.reason||p.draft.changes.map(c=>c.reason).filter(Boolean).join("; ")}</p><p className="my-2 text-sm">{p.result??p.draft.needed}</p><p className="text-xs">Updated {originalPunchDateTime(p.updatedAt)}</p><ol className="my-2 space-y-1 text-xs">{board.history?.filter(h=>h.planId===p.id).map(h=><li key={h.id} className="break-words">{h.action} · {originalPunchDateTime(h.at)} · {board.owners.find(o=>o.id===h.actor)?.name??h.actor}</li>)}</ol><details className="my-2 text-sm"><summary>Changes and evidence</summary>{p.draft.changes.map(c=><p key={c.id}>{c.day} · {labels[c.kind]} · {c.evidence}</p>)}</details><div className="flex flex-wrap gap-2">{p.state==="Resolved"&&<button className={button} disabled={busy} onClick={()=>run(()=>undoWorkPlanAction(p.id),d=>{setDrafts(d);setBatch(undefined);setPreview(null);setAck(false);setTab("Batch review");setNotice("Undo is a new reviewed plan. Verify its evidence and impact before approving.");})}>Prepare audited Undo</button>}{["Approved","Applying","Failed","Sync pending"].includes(p.state)&&<button disabled={busy} className={primary} onClick={()=>run(()=>retryWorkBatchAction(p.batchId),async ()=>{setNotice("Delivery retry queued. Check progress for the result; the approved payroll decision is retained.");await reload();})}>Retry unfinished work</button>}{["Needs fresh review","Rejected","Needs evidence","Ready for approval"].includes(p.state)&&<button className={button} disabled={busy} onClick={()=>run(()=>reopenWorkPlanAction(p.id),result=>{setDrafts(result.drafts??[result.draft]);setBatch(result.existing);setPreview(null);setAck(false);setTab("Batch review");setNotice("Retained your draft. Review current dates, times and evidence; verification was reset.");})}>Review changed evidence / Resume draft</button>}</div></article>)}{board.adjustments.map(a=><Adjustment key={a.id} item={a} reload={reload}/>)}</div>}
  {selected>0&&tab!=="Progress & history"&&<div className="sticky bottom-0 z-20 flex flex-wrap items-center gap-2 rounded-xl border border-blue-300 bg-white p-3 shadow-lg"><span className="mr-auto text-sm font-semibold">{drafts.length} employees · {selected} changes<span className="block text-xs font-normal">{drafts.flatMap(d=>d.changes).filter(c=>c.verified).length} verified · {drafts.flatMap(d=>d.changes).filter(c=>!c.verified).length} remaining</span></span><button className={button} disabled={busy} onClick={()=>save()}>Save draft</button><button className={primary} disabled={busy||tab==="Batch review"&&(drafts.length>20||selected>200||!approvalDrafts.length||approvalIncomplete)} onClick={()=>tab==="Batch review"?void save(true):setTab("Batch review")}>{tab==="Batch review"?(busy?"Working…":"Preview batch"):"Open batch review"}</button>{tab==="Batch review"&&(incomplete>0||unverified>0)&&<button type="button" className="min-h-11 w-full text-left text-xs font-semibold text-amber-900 underline" onClick={()=>{const target=incomplete>0?batchEditor.current?.querySelector<HTMLElement>('[data-review-incomplete="true"]'):batchEditor.current;target?.scrollIntoView({block:"start"});target?.focus({preventScroll:true});}}>{incomplete>0?`${incomplete} ${incomplete===1?"change needs":"changes need"} information · Show next`:`${unverified} ${unverified===1?"change awaits":"changes await"} verification · Go to verification`}</button>}</div>}
 </section>;
}
function Adjustment({item,reload}:{item:WorkBoard["adjustments"][number];reload:()=>Promise<void>}) {
 const [reference,setReference]=useState(""),[evidence,setEvidence]=useState(""),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState("");
 return <article className="space-y-2 rounded-xl border border-amber-300 bg-white p-4"><h3 className="font-semibold">Posted payroll adjustment · {item.state}</h3><p className="text-xs break-all">Case {item.id}</p><details><summary>Original and corrected DTR impact</summary><div className="space-y-2">{Array.isArray(item.impact)?item.impact.map((row:{day:string;before:{workedMinutes:number;regularMinutes:number};proposed:{workedMinutes:number;regularMinutes:number}})=><div key={row.day} className="rounded border p-2 text-sm"><strong>{row.day}</strong><p>Worked time: {row.before.workedMinutes} → {row.proposed.workedMinutes} minutes</p><p>Regular time: {row.before.regularMinutes} → {row.proposed.regularMinutes} minutes</p><p>Inspect DTR and the posted run before recording your conclusion.</p></div>):<p className="text-sm">Awaiting corrected attendance and DTR comparison.</p>}</div></details>{item.state==="Open"&&<><label className="block text-sm">Adjustment reference<input className={field} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);}} placeholder="Existing adjustment entry/reference"/></label><label className="block text-sm">Evidence and conclusion<textarea aria-label="Evidence and conclusion" className={field} value={evidence} onChange={e=>{setEvidence(e.target.value);setConfirmed(false);}}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the adjustment, or confirmed and evidenced no payroll impact.</label><button className={button} disabled={!confirmed} onClick={async()=>{const r=await closeAttendanceAdjustmentAction(item.id,reference,evidence,confirmed);setMessage(r.ok?r.data:r.error);if(r.ok)await reload();}}>Record conclusion</button></>}{message&&<p role="status">{message}</p>}</article>;
}
