import { pgTable, uuid, text, integer, timestamp, jsonb, boolean, date, primaryKey } from "drizzle-orm/pg-core";
import { employees, payrollPeriods, attendanceRawLogs } from "./schema";
const stamp = (name: string) => timestamp(name, { withTimezone: true }).notNull().defaultNow();
export const workBatches = pgTable("attendance_work_batches", {
 id: uuid("id").primaryKey().defaultRandom(), periodId: uuid("period_id").notNull().references(()=>payrollPeriods.id), actor:text("actor").notNull(), revision:integer("revision").notNull().default(1), state:text("state").notNull().default("Draft"), acknowledgedDigest:text("acknowledged_digest"), createdAt:stamp("created_at"), updatedAt:stamp("updated_at"),
});
export const workPlans = pgTable("attendance_work_plans", {
 id:uuid("id").primaryKey().defaultRandom(),batchId:uuid("batch_id").notNull().references(()=>workBatches.id),periodId:uuid("period_id").notNull().references(()=>payrollPeriods.id),employeeId:uuid("employee_id").notNull().references(()=>employees.id),draft:jsonb("draft").notNull(),state:text("state").notNull().default("Draft"),sourceRequest:jsonb("source_request"),sourceResult:jsonb("source_result"),impactedPeriodIds:jsonb("impacted_period_ids").notNull().default([]),evidenceVersion:text("evidence_version").notNull(),ownerId:text("owner_id").notNull(),result:text("result"),attempts:integer("attempts").notNull().default(0),leaseUntil:timestamp("lease_until",{withTimezone:true}),createdAt:stamp("created_at"),updatedAt:stamp("updated_at"),
});
export const workTreatments = pgTable("attendance_work_treatments", {
 id:uuid("id").primaryKey().defaultRandom(),planId:uuid("plan_id").notNull().references(()=>workPlans.id),periodId:uuid("period_id").notNull().references(()=>payrollPeriods.id),employeeId:uuid("employee_id").notNull().references(()=>employees.id),day:date("day").notNull(),version:text("version").notNull(),payload:jsonb("payload").notNull(),active:boolean("active").notNull().default(true),createdAt:stamp("created_at"),
});
export const workHistory=pgTable("attendance_work_history",{id:uuid("id").primaryKey().defaultRandom(),planId:uuid("plan_id").references(()=>workPlans.id),actor:text("actor").notNull(),action:text("action").notNull(),details:jsonb("details").notNull(),createdAt:stamp("created_at")});
export const adjustmentCases=pgTable("attendance_adjustment_cases",{id:uuid("id").primaryKey().defaultRandom(),planId:uuid("plan_id").notNull().references(()=>workPlans.id),periodId:uuid("period_id").notNull().references(()=>payrollPeriods.id),employeeId:uuid("employee_id").notNull().references(()=>employees.id),state:text("state").notNull().default("Open"),beforeEvidence:jsonb("before_evidence").notNull(),afterEvidence:jsonb("after_evidence"),impact:jsonb("impact"),adjustmentReference:text("adjustment_reference"),conclusion:text("conclusion"),closedBy:text("closed_by"),createdAt:stamp("created_at"),updatedAt:stamp("updated_at")});
export const workRawLogs=pgTable("attendance_work_raw_logs",{planId:uuid("plan_id").notNull().references(()=>workPlans.id),changeId:text("change_id").notNull(),rawLogId:integer("raw_log_id").notNull().references(()=>attendanceRawLogs.id)},t=>[primaryKey({columns:[t.planId,t.changeId]})]);
export const workExclusions=pgTable("attendance_work_exclusions",{rawLogId:integer("raw_log_id").primaryKey().references(()=>attendanceRawLogs.id),planId:uuid("plan_id").notNull().references(()=>workPlans.id),reason:text("reason").notNull(),active:boolean("active").notNull().default(true)});
export const workSourceExclusions=pgTable("attendance_work_source_exclusions",{periodId:uuid("period_id").notNull().references(()=>payrollPeriods.id),eventId:uuid("event_id").notNull(),planId:uuid("plan_id").notNull().references(()=>workPlans.id),reason:text("reason").notNull(),version:text("version").notNull(),active:boolean("active").notNull().default(true)},t=>[primaryKey({columns:[t.periodId,t.eventId]})]);
